DECLARE
begin
EXECUTE IMMEDIATE Q'/CREATE OR REPLACE VIEW SPF_V_SPFFMAINYJ AS
SELECT FM.FIRAGENCYNAME,
       FM.SPFGROUP_NAME,
       FM.SPFNAME,
       FM.PROJTYPENAME,
       FM.SPFCODE,
       FM.DEPTID,
       FM.DEPTNAME,
       FM.FIRAGENCYID,
       FM.EXPFUNCNAME,
       FM.BEGINYEAR,
       FM.ENDYEAR,
       FM.CREATETIME,
       FM.PROJTYPEID,
       FM.DISTRICTID,
       FM.AGENCYID,
       FM.SETUPSTATUS,
       FM.EXPFUNCCODE,
       FM.EXPFUNCID,
       FM.AGENCYNAME,
       FM.SPFID,
       FM.DATAKEY,
       FM.ISTEMP,
       FM.ISRELEASE,
       FM.FUNDMANAGE
  FROM SPF_V_FMAIN FM
    WHERE 1 = 1 AND (PROJTYPEID IN (SELECT PROJTYPEID
      FROM SPF_T_PROJECTTYPE WHERE PROJTYPE in ('2', '9')))/';
			
end;-----SPF_V_SPFFMAINYJ
--SPF_V_SPFFMAINYJ
