BEGIN
  EXECUTE IMMEDIATE Q'/
    CREATE OR REPLACE VIEW SPF_V_CUSTODY AS
      SELECT T.DATAKEY,
         T.BEGINYEAR,
         T.DEPTID,
         FB.SETUPSTATUS,
         (SELECT PROJTYPENAME FROM P#SPF_T_PROJECTTYPE TP WHERE TP.PROJTYPEID = T.PROJTYPEID AND ROWNUM < 2 ) PROJTYPEID,
         T.SPFNAME,
         T.APPROVALTYPE,
         T.AGENCYID,
         T.SPFCODE,
         T.ISPUBSHOW,
         T.DISTRICTID,
         T.FUNDMANAGE,
         T.ENDYEAR,
         T.FIRAGENCYID,
         T.SPFID,
         T.FUNDLEVEL,
         T.EXPFUNCID,
         T.CREATEUSER,
         (SELECT CUSRODYDEPT FROM SPF_T_CUSTODY c WHERE T.SPFID = C.SPFID AND c.DISTRICTID =(SELECT GUID FROM CODE_T_DISTRICT_SPF WHERE CODE = GLOBAL_MULTYear_CZ.Secu_f_Global_Parm('DIVID'))) CUSRODYDEPT ,
         (SELECT CUSTODYDEPTID FROM SPF_T_CUSTODY c WHERE T.SPFID = C.SPFID AND c.DISTRICTID =(SELECT GUID FROM CODE_T_DISTRICT_SPF WHERE CODE = GLOBAL_MULTYear_CZ.Secu_f_Global_Parm('DIVID'))) CUSTODYDEPTID ,
         (SELECT CUSTODYDECLRANGE FROM SPF_T_CUSTODY c WHERE T.SPFID = C.SPFID AND c.DISTRICTID =(SELECT GUID FROM CODE_T_DISTRICT_SPF WHERE CODE = GLOBAL_MULTYear_CZ.Secu_f_Global_Parm('DIVID'))) CUSTODYDECLRANGE ,
         (SELECT DISTRICTID FROM SPF_T_CUSTODY c WHERE T.SPFID = C.SPFID AND c.DISTRICTID =(SELECT GUID FROM CODE_T_DISTRICT_SPF WHERE CODE = GLOBAL_MULTYear_CZ.Secu_f_Global_Parm('DIVID'))) CDISTRICTID
      FROM P#SPF_T_FBASEINFO T,P#SPF_T_FBASESTATUS FB
       WHERE T.STATUS = '1' AND T.FUNDMANAGE <> '2' AND FB.SETUPSTATUS = '2'  AND T.SPFID = FB.SPFID
       AND FB.YEAR = GLOBAL_MULTYear_CZ.Secu_f_Global_Parm('YEAR')
     /';
END;
--托管脚本查询专项类别修改
