DECLARE 
viewNumber NUMBER;

BEGIN
  
  --删除类型
  DELETE FROM DICT_T_DEALTYPE WHERE DEALID ='XMCXOA' AND APPID ='SPF';
  --添加类型
  INSERT INTO DICT_T_DEALTYPE (APPID, DEALID, DEALNAME, ORDERID, NEEDCONFIG, ISUNIQUE)
  VALUES ('SPF', 'XMCXOA', '项目查询OA', 18, '0', '0');
  
  --删除缺省列
  DELETE FROM DICT_T_DEFAULTCOL WHERE DEALID ='XMCXOA';
  
  --添加缺省列
  insert into DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS, DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  values ('XMCXOA', 1, '行标志', 'DATAKEY', 3, 32, null, null, '1', '1', '41DE7424A34072DCE0533A06A8C0E045', '1',  'sys_guid()', null, '080001', '0', '0');
  
  --删除菜单
  DELETE FROM FASP_T_PUBMENU WHERE GUID ='11200206'  AND APPID ='spf';
  
  --添加菜单
  insert into fasp_t_pubmenu (GUID, LEVELNO, ISLEAF, STATUS, CODE, NAME, PARENTID, URL, MENUORDER, REMARK, APPSYSID, PROVINCE, YEAR, APPID, PARAM1, PARAM2, PARAM3, PARAM4, PARAM5, SSOFLAG, ADMINTYPE, ALIAS)
  values ('11200206', 2, 1, '1', '004001029', '项目查看(OA)', '120002', '/spf/spf/project/selectoaproj/selectmain.do?dealtype=XMCXOA', 9, 'remark', 1, null, null, 'spf', null, null, null, null, null, null, 1, null);

  --判断查询项目OA视图
  SELECT COUNT(1) INTO viewNumber FROM USER_VIEWS WHERE VIEW_NAME='SPF_V_SELECTPROJECT';
    IF viewNumber > 0 THEN
    --删除已删除项目查询视图
    EXECUTE IMMEDIATE Q'{
      DROP VIEW SPF_V_SELECTPROJECT
    }';
  END IF;
  
  --创建查询项目OA视图
  EXECUTE IMMEDIATE Q'{
    CREATE OR REPLACE VIEW SPF_V_SELECTPROJECT AS
      SELECT AGENCYID,
        (SELECT SPFNAME FROM SPF_T_FBASEINFO T WHERE T.SPFID = T1.SPFID) SPFNAME,
        (SELECT PROJTYPENAME FROM SPF_T_PROJECTTYPE WHERE PROJTYPEID = T1.PROJTYPEID) PROJTYPEID,
        (SELECT NAME FROM FASP_V_PUBEXPFUNC WHERE GUID = EXPFUNCID) EXPFUNCID,
        (SELECT NAME FROM CODE_T_AGENCY_SPF WHERE GUID = T1.DISTRICTID) DISTRICTID,
        CREATEUSER,
        STATUS,
        PROJECTID,
        DATAKEY,
        PROJNAME,
        PROJCODE,
        SPFID,
        CREATETIME,
        STARTYEAR,
        ENDYEAR,
        CREATEUSERNAME
       FROM SPF_T_PBASEINFO T1
  }';
  
  --删除 model 数据
  DELETE FROM P#DICT_T_MODEL WHERE TABLEID ='41DE7424A32F72DCE0533A06A8C0E045';
  
  --删除 factor 数据
  DELETE FROM P#DICT_T_FACTOR WHERE TABLEID='41DE7424A32F72DCE0533A06A8C0E045';
  
  FOR v_row IN (SELECT * FROM PUB_T_PARTITION_DIVID T WHERE T.YEAR <> '*') LOOP
    
    --添加model数据
    INSERT INTO P#DICT_T_MODEL (YEAR, PROVINCE,TABLEID, APPID, DBTABLENAME, NAME, DEALTYPE, EXTPROP, INPUTLVL, ISADD, ISMAN, ISPARTITION, ISRESERVED, ISSHOW, ISTASK, ISSUMTAB, MAINUPTAB, ORDERID, RELATAB, REMARK, SECUSQL, BGTLVL, INITSQL, INITSQLTIME, SHORTTITLE, STATUS, SUITID, TABLETYPE, TABSWHERE, ISBAK, ISALLDISTRICT, ISALLYEAR, INITSQLBTNNAME, ISEXCELIMP, ISREADONLY, DESCFILE)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', 'SPF', 'SPF_V_SELECTPROJECT', '项目查询OA', 'XMCXOA', '0000000000000000000000000000000', '3', '0', '0', '0', '0', '1', null, '0', null, 1, null, null, null, null, null, '1', null, '1', 'FB12E708FE56425F82EF3D89FDE0D0EF', '2', null, null, null, null, null, null, '0', null);

    --添加factor数据
    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33072DCE0533A06A8C0E045', '单位编码', 'AGENCYID', 3, 32, null, '0', null, null, '0', 1, '0', '1', 1, null, null, null, null, '0', '0', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33172DCE0533A06A8C0E045', '专项名称', 'SPFNAME', 3, 200, null, '1', null, null, '0', 2, '0', '1', 1, null, null, null, null, '0', '1', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33272DCE0533A06A8C0E045', '项目类别', 'PROJTYPEID', 3, 100, null, '1', null, null, '0', 3, '0', '1', 1, null, null, null, null, '0', '1', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33372DCE0533A06A8C0E045', '功能科目', 'EXPFUNCID', 3, 120, null, '1', null, null, '0', 4, '0', '1', 1, null, null, null, null, '0', '1', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33472DCE0533A06A8C0E045', '报送地区', 'DISTRICTID', 3, 457, null, '1', null, null, '0', 5, '0', '1', 1, null, null, null, null, '0', '1', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33572DCE0533A06A8C0E045', '项目申报人ID', 'CREATEUSER', 3, 32, null, '1', null, null, '0', 6, '0', '1', 1, null, null, null, null, '0', '0', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33672DCE0533A06A8C0E045', '删除状态', 'STATUS', 3, 1, null, '0', null, null, '0', 7, '0', '1', 1, null, null, null, null, '0', '0', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33772DCE0533A06A8C0E045', '项目ID', 'PROJECTID', 3, 32, null, '1', null, null, '0', 8, '0', '1', 1, null, null, null, null, '0', '0', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33872DCE0533A06A8C0E045', 'DATAKEY', 'DATAKEY', 3, 32, null, '0', null, null, '0', 9, '0', '1', 1, null, null, null, null, '0', '0', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33972DCE0533A06A8C0E045', '项目名称', 'PROJNAME', 3, 200, null, '1', null, null, '0', 10, '0', '1', 1, null, null, null, null, '0', '1', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33A72DCE0533A06A8C0E045', '项目编码', 'PROJCODE', 3, 60, null, '1', null, null, '0', 11, '0', '1', 1, null, null, null, null, '0', '0', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33B72DCE0533A06A8C0E045', '专项ID', 'SPFID', 3, 32, null, '1', null, null, '0', 12, '0', '1', 1, null, null, null, null, '0', '0', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33C72DCE0533A06A8C0E045', '项目申报时间', 'CREATETIME', 3, 20, null, '1', null, null, '0', 13, '0', '1', 1, null, null, null, null, '0', '1', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33D72DCE0533A06A8C0E045', '资金申请起始年', 'STARTYEAR', 3, 32, null, '1', null, null, '0', 14, '0', '1', 1, null, null, null, null, '0', '1', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33E72DCE0533A06A8C0E045', '资金申请结束年', 'ENDYEAR', 3, 32, null, '1', null, null, '0', 15, '0', '1', 1, null, null, null, null, '0', '1', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);

    INSERT INTO P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
    VALUES (v_row.YEAR, v_row.DISTRICTID, '41DE7424A32F72DCE0533A06A8C0E045', null, '41DE7424A33F72DCE0533A06A8C0E045', '项目申报人', 'CREATEUSERNAME', 3, 1000, null, '1', null, null, '0', 16, '0', '1', 1, null, null, null, null, '0', '1', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null, '0', '0', null);
  
  END LOOP;
  
END;
--项目查询OA
