DECLARE
    v_n NUMBER(6) := 0;
    v_tableid  VARCHAR2(32);
    v_busi_tableid  VARCHAR2(32);
BEGIN
    -------------------------物理表增加字段---------------------------
    --KPI_T_FXMJXZBB增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_FXMJXZBB' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        execute immediate Q'{alter table P#KPI_T_FXMJXZBB  add ISDELETE CHAR(1)  DEFAULT 0}';
    END IF;

    -------------------------备份表物理表增加字段---------------------------
    --KPI_T_FXMJXZBB_BAK增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_FXMJXZBB_BAK' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        SELECT count(1) into v_n FROM USER_TABLES WHERE upper(TABLE_NAME)='P#KPI_T_FXMJXZBB_BAK';
        IF v_n = 1 THEN
            execute immediate Q'{alter table P#KPI_T_FXMJXZBB_BAK  add ISDELETE CHAR(1)  DEFAULT 0}';
        END IF;
    END IF;

    -------------------------获取tableId-------------------------
    SELECT tableid INTO v_tableid FROM dict_t_model where dbtablename = 'KPI_T_FXMJXZBB';
    SELECT tableid INTO v_busi_tableid FROM dict_t_model where dbtablename = 'SPF_T_PXMJXZBB';
    -------------------------factor表登记新增字段-------------------------
    for V_ROW in (select * from pub_t_partition_divid t where t.year <> '*') LOOP
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_tableid,'','525173AB749E488D94D0E531E5B7717B','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,'','','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_tableid AND DBCOLUMNNAME = 'ISDELETE');
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_busi_tableid,'','5D3B914EEBC94AF1830683015897BA06','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,v_tableid,'525173AB749E488D94D0E531E5B7717B','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_busi_tableid AND DBCOLUMNNAME = 'ISDELETE');
    END LOOP;
    sys_p_recreate_views(v_tableid);
    sys_p_recreate_views(v_busi_tableid);
    -------------------------物理表增加字段---------------------------
    --KPI_T_FZXZJJXZB增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_FZXZJJXZB' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        execute immediate Q'{alter table P#KPI_T_FZXZJJXZB  add ISDELETE CHAR(1)  DEFAULT 0}';
    END IF;

    -------------------------备份表物理表增加字段---------------------------
    --KPI_T_FZXZJJXZB_BAK增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_FZXZJJXZB_BAK' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        SELECT count(1) into v_n FROM USER_TABLES WHERE upper(TABLE_NAME)='P#KPI_T_FZXZJJXZB_BAK';
        IF v_n = 1 THEN
            execute immediate Q'{alter table P#KPI_T_FZXZJJXZB_BAK  add ISDELETE CHAR(1)  DEFAULT 0}';
        END IF;
    END IF;

    -------------------------获取tableId-------------------------
    SELECT tableid INTO v_tableid FROM dict_t_model where dbtablename = 'KPI_T_FZXZJJXZB';
    SELECT tableid INTO v_busi_tableid FROM dict_t_model where dbtablename = 'SPF_T_ZXJXZBB';
    -------------------------factor表登记新增字段-------------------------
    for V_ROW in (select * from pub_t_partition_divid t where t.year <> '*') LOOP
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_tableid,'','7C1AEC86B06F4363BAC161C6F7064B15','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,'','','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_tableid AND DBCOLUMNNAME = 'ISDELETE');
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_busi_tableid,'','CC91342183154D2FA5AAD1CFD343F3A7','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,v_tableid,'7C1AEC86B06F4363BAC161C6F7064B15','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_busi_tableid AND DBCOLUMNNAME = 'ISDELETE');
    END LOOP;
    sys_p_recreate_views(v_tableid);
    sys_p_recreate_views(v_busi_tableid);
END;
--WJP_1130_项目库_绩效指标表新增ISDELETE字段
