
DECLARE
  V_COUNT INT;
BEGIN
SELECT COUNT(*)
  into V_COUNT
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'P#DICT_T_SETREC'
   AND COLUMN_NAME = 'TYPEFLAG';
    IF V_COUNT = 0 
    THEN 
     EXECUTE IMMEDIATE Q'{ALTER TABLE P#DICT_T_SETREC ADD TYPEFLAG char(1)}'; 
EXECUTE IMMEDIATE Q'/CREATE OR REPLACE VIEW DICT_T_SETREC AS
SELECT DBVERSION,OBJECTID,PROCESSID,RECID,REMARK,SHOWCOLS,STATUS,TABLEID,TITLEWIDTH,TYPEFLAG
FROM P#DICT_T_SETREC
WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'/';
  END IF;
END;


--¸øDICT_T_SETREC±í¼Ótypeflag×Ö¶Î
