
DECLARE
  n_count integer;
BEGIN
  SELECT COUNT(*) INTO n_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#KPI_T_SETSPFKPI' AND COLUMN_NAME = 'ISIMPORT';
  IF n_count = 0 THEN
     EXECUTE IMMEDIATE 'alter table P#KPI_T_SETSPFKPI add isimport char(1) default 0';
  END IF;
  Select COUNT(*) INTO n_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#KPI_T_SETDEPKPI' AND COLUMN_NAME = 'ISIMPORT';
  IF n_count = 0 THEN
     EXECUTE IMMEDIATE 'alter table P#KPI_T_SETDEPKPI add isimport char(1) default 0';
  END IF;
  Select COUNT(*) INTO n_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#KPI_T_SETFNCKPI' AND COLUMN_NAME = 'ISIMPORT';
  IF n_count = 0 THEN
     EXECUTE IMMEDIATE 'alter table P#KPI_T_SETFNCKPI add isimport char(1) default 0';
  END IF;
  

 EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW KPI_T_SETSPFKPI AS
SELECT 
        STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID,
        SUPERGUID, KPINAME, INDITYPE, GETDATAFUNC, LEVELNO, 
        ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION, STANDARD, 
        ISINSERT, ISUPDATE, ISDELETE,  KPIPROP, DBVERSION, 
        FRMKPIID,ISIMPORT FROM P#KPI_T_SETSPFKPI 
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') 
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
execute immediate Q'{CREATE OR REPLACE VIEW KPI_T_SETDEPKPI AS
SELECT 
        STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID,
        SUPERGUID, KPINAME, INDITYPE, GETDATAFUNC, LEVELNO, 
        ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION, STANDARD, 
        ISINSERT, ISUPDATE, ISDELETE,  KPIPROP, DBVERSION, 
        FRMKPIID,ISIMPORT FROM P#KPI_T_SETDEPKPI 
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') 
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';  
execute immediate Q'{CREATE OR REPLACE VIEW KPI_T_SETFNCKPI AS
SELECT 
        STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID,
        SUPERGUID, KPINAME, INDITYPE, GETDATAFUNC, LEVELNO, 
        ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION, STANDARD, 
        ISINSERT, ISUPDATE, ISDELETE,  KPIPROP, DBVERSION, 
        FRMKPIID,isimport FROM P#KPI_T_SETFNCKPI 
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') 
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';          
END;   --GF_20170103_个性指标导入脚本
----GF_20170103_个性指标导入脚本
