DECLARE 
V_COUNT NUMBER(1);--查看表是否存在
BEGIN 
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES T WHERE  T.TABLE_NAME = 'P#SPF_T_BFLOW_LOG';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE Q'{
	  CREATE TABLE P#SPF_T_BFLOW_LOG
		(
		  DATAKEY      VARCHAR2(32) DEFAULT SYS_GUID() NOT NULL,
		  SPFID        VARCHAR2(32),
		  OBJECTID     VARCHAR2(32),
		  BATCHID      VARCHAR2(32),
		  CFLOWBATCHID VARCHAR2(32),
		  DBVERSION    TIMESTAMP(6),
		  STEP         VARCHAR2(32),
		  STATUS       CHAR(1) DEFAULT 1 NOT NULL,
		  YEAR         CHAR(4) NOT NULL,
		  PROVINCE     VARCHAR2(9) NOT NULL,
		  DISTRICTID   VARCHAR2(32),
		  ISBACK       CHAR(1),
		  OBJSTATUS    CHAR(1)
		)
	  }';
	  --刷P#KPI_T_FCZJXZBB表触发器
      EXECUTE IMMEDIATE Q'{alter table P#SPF_T_BFLOW_LOG  add constraint P#SPF_T_BFLOW_LOG_KEY primary key (PROVINCE, YEAR, STATUS, DATAKEY)}';
	  SYS_P_PARTITION_TABLE('P#SPF_T_BFLOW_LOG') ;
      EXECUTE IMMEDIATE Q'{create index IDX_SPF_T_BFLOW_LOG_KEY1 on P#SPF_T_BFLOW_LOG (DATAKEY)}';
      EXECUTE IMMEDIATE Q'{create index IDX_SPF_T_BFLOW_LOG_KEY2 on P#SPF_T_BFLOW_LOG (BATCHID, OBJSTATUS)}';
  	  EXECUTE IMMEDIATE Q'{
CREATE OR REPLACE VIEW SPF_T_BFLOW_LOG AS
SELECT DATAKEY,
       SPFID,
       OBJECTID,
       BATCHID,
       DBVERSION,
       CFLOWBATCHID,
       STATUS,
       STEP,
       ISBACK,
       OBJSTATUS,
       DISTRICTID
  FROM P#SPF_T_BFLOW_LOG
 WHERE STATUS = '1'

 }';
  END IF;
END;

--创建横向子表SPF_T_BFLOW_LOG
