CREATE OR REPLACE VIEW SPF_V_PBAKLISTMAIN AS
SELECT  A.DATAKEY,
(SELECT S.NAME FROM CODE_T_FIRAGENCY S WHERE S.GUID = F.FIRAGENCYID) FIRAGENCYNAME,
(SELECT AG.NAME FROM CODE_T_AGENCY_SPF AG WHERE AG.GUID=A.AGENCYID) AS REPORTAGENCY,
   A.SPFID,
   F.SPFNAME SPFNAME,
         A.AGENCYID,
         F.FIRAGENCYID,
         AGENCY.NAME AGENCYNAME,
         A.PROJTYPEID,
         A.PROJECTID,
         A.PROJCODE,
         A.PROJNAME  PROJNAME,
         A.PROJNAME||'{'||A.PROJECTID||'}' PROJGROUP_NAME,
       (SELECT  ACCT.NAME FROM CODE_V_ACCTCODE_OUT_SPF  ACCT WHERE ACCT.GUID  = a.EXPFUNCID) AS EXPFUNCCLASS,
        A.CREATEUSER,
        A.CREATETIME,
        NVL(A.UPSTATUS,'0') UPSTATUS,
        A.UPTIME,
        A.IMPORTANCE,
        A.DISTRICTID,
        A.ISBGT,
        NVL(A.CHECKSTATUS,'0') CHECKSTATUS,
        A.ISINSTEAD,
        A.ISTEMP,
        A.TEMPDEPTID,
        A.TEMPFIRAGENCYID,
        A.TEMPCHECKSTATUS,
        A.TEMPUPSTATUS,
        A.TEMPUPTIME,
        F.FUNDLEVEL,
        NVL((SELECT SUM(NVL(B.YX, 0))
             FROM SPF_T_PINVESTPLAN B
            WHERE B.PROJECTID = A.PROJECTID),
           0) YX,

        NVL((SELECT SUM(NVL(B.QTZJ, 0))
             FROM SPF_T_PINVESTPLAN B
            WHERE B.PROJECTID = A.PROJECTID),
           0) QTZJ,
        NVL((SELECT SUM(NVL(B.COUNTYAGNUM, 0))
             FROM SPF_T_PINVESTPLAN B
            WHERE B.PROJECTID = A.PROJECTID),
           0) COUNTYAGNUM,
        NVL((SELECT SUM(NVL(B.COUNTYNUM, 0))
             FROM SPF_T_PINVESTPLAN B
            WHERE B.PROJECTID = A.PROJECTID),
           0) COUNTYNUM,
        NVL((SELECT SUM(NVL(B.CITYAGNUM, 0))
             FROM SPF_T_PINVESTPLAN B
            WHERE B.PROJECTID = A.PROJECTID),
           0) CITYAGNUM,
        NVL((SELECT SUM(NVL(B.CITYNUM, 0))
             FROM SPF_T_PINVESTPLAN B
            WHERE B.PROJECTID = A.PROJECTID),
           0) CITYNUM,
        NVL((SELECT SUM(NVL(B.PROVAGNUM, 0))
             FROM SPF_T_PINVESTPLAN B
            WHERE B.PROJECTID = A.PROJECTID),
           0) PROVAGNUM,
        NVL((SELECT SUM(NVL(B.PROVNUM, 0))
             FROM SPF_T_PINVESTPLAN B
            WHERE B.PROJECTID = A.PROJECTID),
           0) PROVNUM,
        F.EXPFUNCID,
         A.DBVERSION,
        A.STATUS
    FROM SPF_T_PBASEINFO A ,CODE_T_FIRAGENCY AGENCY, SPF_T_FBASEINFO F
    WHERE F.FIRAGENCYID = AGENCY.GUID AND A.SPFID = F.SPFID
--SPF_V_PBAKLISTMAIN
