BEGIN 
 for v_tab in (SELECT TABLEID,sys_guid() GUID FROM DICT_T_MODEL WHERE RELATAB ='1FFB71E8965441A1AB5617677A447AA4' ) loop 
    for v_row in (select * from pub_t_partition_divid t where t.year <> '*') loop 
  DELETE FROM P#DICT_T_FACTOR  WHERE TABLEID = v_tab.Tableid AND PROVINCE = v_row.DISTRICTID AND YEAR = v_row.YEAR AND DBCOLUMNNAME ='ISCS';
  insert into P#DICT_T_FACTOR (YEAR, PROVINCE, NAME, TABLEID, COLUMNID, FRMCOLID, FRMTABID, ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (v_row.YEAR, v_row.DISTRICTID, '是否测算', v_tab.Tableid, v_tab.GUID, '6F4D8F7654C54DF79E1E7CDCB117C957','1FFB71E8965441A1AB5617677A447AA4', null, null, null, null, null, null, null, 1, 3, 'ISCS', '''0''', null, '0000000000000000000000000000000', null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '0', 1, '1', 78, null, null, 0, '0', null, '1', '0', null, '0', null);
    END LOOP;
    sys_p_recreate_views(v_tab.TABLEID);
  END LOOP;
  
   for v_model in (SELECT TABLEID FROM DICT_T_MODEL  WHERE DEALTYPE IN ('2104', '2105') ) loop 
   UPDATE P#DICT_T_MODEL
   SET TABSWHERE = ' ISCS =''1'''
 WHERE tableid = v_model.TABLEID;
 sys_p_recreate_views(v_model.TABLEID);
 END LOOP;
 DELETE FROM FASP_T_PUBMENU WHERE GUID ='264CFA21E0888D1FE050A8C0210558D4';
 UPDATE FASP_T_PUBMENU SET NAME ='部门用户对专项类别' WHERE GUID='12001005';
 UPDATE FASP_T_PUBMENU SET NAME ='财政用户对专项类别' WHERE GUID='12001006';
 UPDATE FASP_T_PUBMENU SET NAME ='角色对专项类别' WHERE GUID='12001008';
END;
--给业务对象添加是否测算字段
