declare
v_count number(1);--查看表是否存在
begin 
  select count(*) INTO v_count from user_tables t where  t.table_name = 'P#SPF_T_STAGESTATUS';
  if v_count = 0 THEN
   execute immediate Q'{
     create table P#SPF_T_STAGESTATUS
     (
  province      VARCHAR2(9) not null,
  year          CHAR(4) not null,
  status        CHAR(1) default '1' not null,
  dbversion     TIMESTAMP(6) default SYSDATE,
  datakey       VARCHAR2(32) default SYS_GUID() not null,
  processid     VARCHAR2(32),
  dataid        VARCHAR2(32),
  docid         VARCHAR2(32),
  operationname VARCHAR2(400),
  isfinal       VARCHAR2(32)
            )
  }';
    execute immediate Q'{alter table P#SPF_T_STAGESTATUS add constraint PK_P#SPF_T_STAGESTATUS primary key (PROVINCE, YEAR, STATUS, DATAKEY)}';

  --刷P#KPI_T_FCZJXZBB表触发器
  SYS_P_PARTITION_TABLE('P#SPF_T_STAGESTATUS') ;
  end if;
  
        --处理dealtype和缺省列
  select count(1) into v_count FROM dict_t_dealtype WHERE dealid='33' AND appid ='SPF';
  if v_count=0 then
     insert into dict_t_dealtype (APPID, DEALID, DEALNAME, ORDERID, NEEDCONFIG)  values ('SPF','33', '项目库阶段记录表', 1003, '0');
  end if;
  select count(1) into v_count FROM dict_t_defaultcol WHERE DEALID ='33' and name= '行标志';
  if v_count=0 then
    insert into dict_t_defaultcol (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS)
    values ('33', 1, '行标志', 'DATAKEY', 3, 32, '0', null, '1', '1',sys_guid(), '1');
  end if;

      --删除model 表中   财政绩效指标表  数据
    delete from p#dict_t_model t where t.TABLEID='B774DB396978456C88948727DD757A39' ;
    
    --删除factor 表中   财政绩效指标表 数据
    delete from p#dict_t_factor t where t.TABLEID='B774DB396978456C88948727DD757A39';
    
  --向P#表中循环插入数据
  for v_row in (select * from pub_t_partition_divid t where t.year <> '*') loop 
    
    begin

    --向model表中插入   财政绩效指标表 数据
  
insert into P#dict_t_model (YEAR, PROVINCE, TABLEID, NAME, ORDERID, DBTABLENAME, TABLETYPE, ISSHOW, APPID,  REMARK, SUITID, DEALTYPE, ISRESERVED, INPUTLVL, ISADD, SHORTTITLE, EXTPROP, BGTLVL, SECUSQL, ISSUMTAB, ISMAN, MAINUPTAB, RELATAB, TABSWHERE, ISPARTITION, STATUS, ISBAK,  INITSQL, INITSQLTIME, ISTASK, ISALLDISTRICT, DESCFILE, ISALLYEAR, INITSQLBTNNAME, ISEXCELIMP)
values (v_row.YEAR, v_row.DISTRICTID, 'B774DB396978456C88948727DD757A39', '项目库阶段状态表', 1, 'SPF_T_STAGESTATUS', '1', '1', 'SPF', null, 'FB12E708FE56425F82EF3D89FDE0D0EF', '33', '0', '3', '0', null, '0000000000000000000000000000000', null, null, '0', '0', null, null, null, '1', '1', '0',  NULL, '1', '0', '1', null, '1', null, '0');


insert into P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID, 'B774DB396978456C88948727DD757A39', null, '585E920F83F3445187B0B27A3C7F6217', '专项/项目ID', 'DATAID', 3, 32, 0, '0', null, null, '1',  3, '0', '1', 1, null, null, '0', null, '1', '1', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null,  '0', '1', null);

insert into P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID, 'B774DB396978456C88948727DD757A39', null, '5BF750C24D354739BA7A1946FBF9393E', '公文ID', 'DOCID', 3, 32, 0, '1', null, null, '1',  4, '0', '1', 1, null, null, '0', null, '0', '1', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null,  '0', '1', null);

insert into P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID, 'B774DB396978456C88948727DD757A39', null, '8C2BDBBA3BD44B7F8A0DBB3508D9791F', '阶段', 'PROCESSID', 3, 32, 0, '1', null, null, '1',  2, '0', '1', 1, null, null, '0', null, '0', '1', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', NULL, '0', '1', null);

insert into P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID, 'B774DB396978456C88948727DD757A39', null, 'A86CDEC5C6834D5EBF1A07A369B880AD', '操作说明', 'OPERATIONNAME', 3, 400, 0, '1', null, null, '1', 5, '0', '1', 1, null, null, '0', null, '0', '1', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null,  '0', '1', null);

insert into P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID, 'B774DB396978456C88948727DD757A39', null, 'BB3C66D50F7B4D458516BE9B68AE061C', '是否确认', 'ISFINAL', 3, 32, 0, '1', null, null, '1',  6, '0', '1', 1, null, null, '0', null, '0', '1', '0', '0', '0', null, null, '0', null, '0000000000000000000000000000000', null, null, null, '0', null, '0', null, null, null, '1', null,  '0', '1', null);

insert into P#DICT_T_FACTOR (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE,  ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID,  PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID, 'B774DB396978456C88948727DD757A39', '080001', 'CB56759606B948FD9EC9A95E5BA84041', '唯一标识', 'DATAKEY', 3, 32, null, '1', 'SYS_GUID()', null, '1',  1, '0', '1', 1, '唯一标识', null, null, null, '0', '1', '0', '0', '0', null, null, '0', null, null, '唯一标识', null, null, '0', null, '0', null, null, null, '1', null,  '0', null, null);
    end; 
  end loop;
  sys_p_recreate_views('B774DB396978456C88948727DD757A39');
  
end;
--新增项目库阶段记录表
