BEGIN
  UPDATE P#DICT_T_FACTOR  F  SET datatype = '6',showformat = '4',CSID='09B774215D424706B303ED8D30DB1125'  WHERE EXISTS(SELECT 1 FROM DICT_T_MODEL M WHERE M.TABLEID=F.TABLEID AND M.DBTABLENAME='EXP_T_PBUDGETTEMP' AND F.DBCOLUMNNAME='PROJECTID' );
END;
--修改预算中间表项目ID引用列
