BEGIN
--修改找不到父级的列
UPDATE DICT_T_FACTOR SET SUPERID = '0',LEVELNO = 1
WHERE (TABLEID,COLUMNID) IN (
SELECT TABLEID,COLUMNID
  FROM DICT_T_FACTOR X
 WHERE NOT EXISTS (SELECT 1
          FROM DICT_T_FACTOR Y
         WHERE Y.TABLEID = X.TABLEID
           AND Y.COLUMNID = X.SUPERID
           ) AND X.SUPERID <> '0') ;
           --删除爷爷爹孙子
  LOOP 
DELETE FROM DICT_T_FACTOR WHERE (TABLEID,COLUMNID) IN (SELECT TABLEID,COLUMNID
  FROM DICT_T_FACTOR X
 WHERE NOT EXISTS (SELECT 1
          FROM DICT_T_FACTOR Y
         WHERE Y.TABLEID = X.TABLEID
           AND Y.SUPERID = X.COLUMNID
           ) AND X.ISLEAF = '0');
EXIT WHEN SQL%ROWCOUNT < 1;
END LOOP;
END;
--DF_修正factor父节点问题
