BEGIN
UPDATE P#SPF_T_FBASEINFO SET CSMODE =(SELECT GUID FROM CODE_T_CSMX WHERE  CODE = (SELECT TABLEID FROM DICT_T_MODEL WHERE DEALTYPE ='2104') AND rownum=1) WHERE CSMODE IS NULL AND STATUS ='1';
END;
--spf添加默认测算模型
