declare 
v_count number(1);--查看表是否存在
begin 
  select count(*) INTO v_count from user_tables t where  t.table_name = 'P#SPF_T_FBASESTATUS';
  if v_count = 0 THEN
   execute immediate Q'{
     CREATE TABLE P#SPF_T_FBASESTATUS
    (
      PROVINCE    VARCHAR2(9) NOT NULL,
      YEAR        CHAR(4) NOT NULL,
      STATUS      CHAR(1) DEFAULT '1' NOT NULL,
      DBVERSION   TIMESTAMP(6) DEFAULT SYSDATE,
      DATAKEY     VARCHAR2(32) DEFAULT SYS_GUID() NOT NULL,
      NEEDUPDATE  VARCHAR2(4000),
      ORDERID     NUMBER(9),
      FINYEAR     VARCHAR2(4),
      SPFID       VARCHAR2(32),
      SETUPSTATUS NUMBER(1) DEFAULT 0
    )
    }';
    execute immediate Q'{alter table P#SPF_T_FBASESTATUS add constraint PK_P#SPF_T_FBASESTATUS primary key (PROVINCE, YEAR, STATUS, DATAKEY)}';
    --刷P#SPF_T_FBASESTATUS表触发器
    SYS_P_PARTITION_TABLE('P#SPF_T_FBASESTATUS') ;
    execute immediate Q'{create index IDX_P#SPF_T_FBASESTATUS2 on P#SPF_T_FBASESTATUS (SETUPSTATUS)}';
    execute immediate Q'{create unique index IDX_P#SPF_T_FBASESTATUS1 on P#SPF_T_FBASESTATUS (YEAR, STATUS, SPFID)}';
      --删除model 表中   财政绩效指标表  数据
    delete from p#dict_t_model t where t.TABLEID='4C8F62C7CD581AACE0533A06A8C0993B' ;
    
    --删除factor 表中   财政绩效指标表 数据
    delete from p#dict_t_factor t where t.TABLEID='4C8F62C7CD581AACE0533A06A8C0993B';
    
  --向P#表中循环插入数据
  for v_row in (select * from pub_t_partition_divid t where t.year <> '*') loop 
    

insert into P#DICT_T_MODEL (YEAR, PROVINCE, TABLEID, APPID, DBTABLENAME, NAME, DEALTYPE, EXTPROP, INPUTLVL, ISADD, ISMAN, ISPARTITION, ISRESERVED, ISSHOW, ISTASK, ISSUMTAB, MAINUPTAB, ORDERID, RELATAB, REMARK, SECUSQL, BGTLVL, INITSQL, INITSQLTIME, SHORTTITLE, STATUS, SUITID, TABLETYPE, TABSWHERE, ISBAK, ISALLDISTRICT, ISALLYEAR, INITSQLBTNNAME, ISEXCELIMP, ISREADONLY, DESCFILE)
values (v_row.YEAR, v_row.DISTRICTID, '4C8F62C7CD581AACE0533A06A8C0993B', 'SPF', 'SPF_T_FBASESTATUS', '专项资金状态记录表', 'B0', '0000000000000000000000000000000', '3', null, null, '1', null, '1', '0', '0', null, 1, null, null, null, null, '<CLOB>', '1', null, '1', 'FB12E708FE56425F82EF3D89FDE0D0EF', '1', null, '0', '0', '0', null, '0', '0', null);
insert into P#dict_t_factor (YEAR, PROVINCE, ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID, '行标志', null, null, null, null, '行标志', '4C8F62C7CD591AACE0533A06A8C0993B', null, 32, 3, 'DATAKEY', 'sys_guid()', '080001', null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '1', '0', '1', 1, '行标志', '1', 1, null, null, 0, null, null, '1', '0', '4C8F62C7CD581AACE0533A06A8C0993B', null, '0', null);

insert into P#dict_t_factor (YEAR, PROVINCE, ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID, '刷新标志', null, null, null, null, '刷新标志', '4C8F62C7CD5A1AACE0533A06A8C0993B', null, 4000, 3, 'NEEDUPDATE', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '1', '0', '1', 1, '刷新标志', '1', 2, null, null, 0, null, null, '1', '0', '4C8F62C7CD581AACE0533A06A8C0993B', null, '0', null);

insert into P#dict_t_factor (YEAR, PROVINCE, ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID, '排序序号', null, null, null, null, '排序序号', '4C8F62C7CD5B1AACE0533A06A8C0993B', null, 9, 1, 'ORDERID', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '1', '0', '1', 1, '排序序号', '1', 3, null, null, 0, null, null, '1', '0', '4C8F62C7CD581AACE0533A06A8C0993B', null, '0', null);

insert into P#dict_t_factor (YEAR, PROVINCE, ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID, '财年', null, null, null, null, '财年', '4C8F62C7CD5C1AACE0533A06A8C0993B', null, 4, 3, 'FINYEAR', null, '10206', null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '1', '0', '1', 1, '财年', '1', 4, null, null, 0, null, null, '1', '0', '4C8F62C7CD581AACE0533A06A8C0993B', null, '0', null);

insert into P#dict_t_factor (YEAR, PROVINCE, ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID, null, null, null, null, null, null, '4C90F61143D12AFEE0533A06A8C04309', null, 32, 3, 'SPFID', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '1', '1', '0', '0', '0', '1', '0', '1', 1, '专项ID', '0', 5, null, null, 0, '0', null, '1', '0', '4C8F62C7CD581AACE0533A06A8C0993B', null, '0', null);

insert into P#dict_t_factor (YEAR, PROVINCE, ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID, null, null, null, null, null, '0.未发布1.已发布2.已确认', '4C90F61143D22AFEE0533A06A8C04309', null, 1, 1, 'SETUPSTATUS', '0', null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '专项设立状态', '1', 6, null, null, 0, '0', null, '1', '0', '4C8F62C7CD581AACE0533A06A8C0993B', null, '0', null);
  end loop;
  sys_p_recreate_views('4C8F62C7CD581AACE0533A06A8C0993B');
 end if;
end;

--专项状态表P#SPF_T_FBASESTATUS
