declare
  v_n number(6) :=0;
begin 
  
  SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_PEVALINDI' and upper(column_name)='DEPTEVALUATION'; 
   --P#KPI_T_PEVALINDI添加DEPTEVALUATION字段
  if v_n=0 then
     execute immediate Q'{alter table P#KPI_T_PEVALINDI add DEPTEVALUATION varchar(4000)}';
     execute immediate Q'{CREATE OR REPLACE VIEW KPI_T_PEVALINDI AS 
     SELECT DATAKEY,PROJECTID,ORDERID,THIRDKPI,SCORE,ISINSERT,TEMPLATEID,CELLSECU,ISQZX,ISDJ,KPIPROP,ISUPDATE,FDCODE,ORIGCODE,ISTEMPLATE,SUPERID,LEVELNO,EXPLANATION,STANDARD,SELFEVALUATION,DWPF,BMPF,BMPJ,ZJPF,CZPF,PJJG,DEPTEVALUATION, STATUS, DBVERSION 
     FROM P#KPI_T_PEVALINDI  WHERE YEAR=global_multyear_cz.Secu_f_GLOBAL_PARM('YEAR')  AND  PROVINCE=global_multyear_cz.Secu_f_GLOBAL_PARM('DIVID')  AND STATUS='1'}';
     INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
     VALUES ('部门评价', NULL, NULL, NULL, NULL, NULL, '33A5A6E35413BD3BE050A8C0F0002FEC', NULL, 4000, 3, 'DEPTEVALUATION',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '部门评价', '1', 26, NULL, NULL, 6, '0', NULL, '1', '0', 'F82E82729FBF219EE040A8C020032EE2', NULL,  '0', NULL);
  end if;
    --修改财政绩效主视图distinctid改成districtid
  execute immediate Q'{CREATE OR REPLACE VIEW KPI_V_FNCEXPTARGET AS
      SELECT   '' needupdate,
                 '' finyear,
                 '' orderid,
                 c.guid datakey,
                 c.guid districtid,
                 c.code,
                 c.province_sh,
                 c.city,
                 c.county
        FROM     code_t_district_spf c
        ORDER BY c.code}';
  UPDATE DICT_T_FACTOR SET dbcolumnname = 'DISTRICTID' WHERE tableid = '18B66577095FA078E050A8C021051E98' AND NAME ='地区名称';
end;
--绩效_修改P#KPI_T_PEVALINDI字段_王建平
