DECLARE
    v_n NUMBER(6) := 0;
    v_tableid  VARCHAR2(32);
    v_busi_tableid  VARCHAR2(32);
BEGIN
    -------------------------物理表增加字段---------------------------
    --KPI_T_FXMJXZBB增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_FXMJXZBB' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        execute immediate Q'{alter table P#KPI_T_FXMJXZBB  add ISDELETE CHAR(1)  DEFAULT 0}';
    END IF;

    -------------------------备份表物理表增加字段---------------------------
    --KPI_T_FXMJXZBB_BAK增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_FXMJXZBB_BAK' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        SELECT count(1) into v_n FROM USER_TABLES WHERE upper(TABLE_NAME)='P#KPI_T_FXMJXZBB_BAK';
        IF v_n = 1 THEN
            execute immediate Q'{alter table P#KPI_T_FXMJXZBB_BAK  add ISDELETE CHAR(1)  DEFAULT 0}';
        END IF;
    END IF;

    -------------------------获取tableId-------------------------
    SELECT tableid INTO v_tableid FROM dict_t_model where dbtablename = 'KPI_T_FXMJXZBB';
    SELECT tableid INTO v_busi_tableid FROM dict_t_model where dbtablename = 'KPI_V_PROJINDI';
    -------------------------factor表登记新增字段-------------------------
    for V_ROW in (select * from pub_t_partition_divid t where t.year <> '*') LOOP
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_tableid,'','525173AB749E488D94D0E531E5B7717B','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,'','','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_tableid AND DBCOLUMNNAME = 'ISDELETE');
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_busi_tableid,'','ECF286729A31440D93DDB7D80457F407','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,v_tableid,'525173AB749E488D94D0E531E5B7717B','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_busi_tableid AND DBCOLUMNNAME = 'ISDELETE');
    END LOOP;
    sys_p_recreate_views(v_tableid);
    sys_p_recreate_views(v_busi_tableid);
    -------------------------物理表增加字段---------------------------
    --KPI_T_FZXZJJXZB增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_FZXZJJXZB' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        execute immediate Q'{alter table P#KPI_T_FZXZJJXZB  add ISDELETE CHAR(1)  DEFAULT 0}';
    END IF;

    -------------------------备份表物理表增加字段---------------------------
    --KPI_T_FZXZJJXZB_BAK增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_FZXZJJXZB_BAK' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        SELECT count(1) into v_n FROM USER_TABLES WHERE upper(TABLE_NAME)='P#KPI_T_FZXZJJXZB_BAK';
        IF v_n = 1 THEN
            execute immediate Q'{alter table P#KPI_T_FZXZJJXZB_BAK  add ISDELETE CHAR(1)  DEFAULT 0}';
        END IF;
    END IF;

    -------------------------获取tableId-------------------------
    SELECT tableid INTO v_tableid FROM dict_t_model where dbtablename = 'KPI_T_FZXZJJXZB';
    SELECT tableid INTO v_busi_tableid FROM dict_t_model where dbtablename = 'KPI_V_SPFINDI';
    -------------------------factor表登记新增字段-------------------------
    for V_ROW in (select * from pub_t_partition_divid t where t.year <> '*') LOOP
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_tableid,'','7C1AEC86B06F4363BAC161C6F7064B15','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,'','','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_tableid AND DBCOLUMNNAME = 'ISDELETE');
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_busi_tableid,'','61133B19F9E04B869AAC6BECB48894CC','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,v_tableid,'7C1AEC86B06F4363BAC161C6F7064B15','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_busi_tableid AND DBCOLUMNNAME = 'ISDELETE');
    END LOOP;
    sys_p_recreate_views(v_tableid);
    sys_p_recreate_views(v_busi_tableid);
    -------------------------物理表增加字段---------------------------
    --KPI_T_FBMJXZBB增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_FBMJXZBB' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        execute immediate Q'{alter table P#KPI_T_FBMJXZBB  add ISDELETE CHAR(1)  DEFAULT 0}';
    END IF;

    -------------------------备份表物理表增加字段---------------------------
    --KPI_T_FBMJXZBB_BAK增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_FBMJXZBB_BAK' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        SELECT count(1) into v_n FROM USER_TABLES WHERE upper(TABLE_NAME)='P#KPI_T_FBMJXZBB_BAK';
        IF v_n = 1 THEN
            execute immediate Q'{alter table P#KPI_T_FBMJXZBB_BAK  add ISDELETE CHAR(1)  DEFAULT 0}';
        END IF;
    END IF;

	/*
    -------------------------获取tableId-------------------------
    SELECT tableid INTO v_tableid FROM dict_t_model where dbtablename = 'KPI_T_FBMJXZBB';
    SELECT tableid INTO v_busi_tableid FROM dict_t_model where dbtablename = 'KPI_V_DEPTINDI';
    -------------------------factor表登记新增字段-------------------------
    for V_ROW in (select * from pub_t_partition_divid t where t.year <> '*') LOOP
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_tableid,'','D02D9C1720A54397B0B5C9A4BD7622B6','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,'','','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_tableid AND DBCOLUMNNAME = 'ISDELETE');
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_busi_tableid,'','35033190EC444131B6DD6D16329260EC','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,v_tableid,'D02D9C1720A54397B0B5C9A4BD7622B6','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_busi_tableid AND DBCOLUMNNAME = 'ISDELETE');
    END LOOP;
    sys_p_recreate_views(v_tableid);
    sys_p_recreate_views(v_busi_tableid);
    -------------------------物理表增加字段---------------------------
    --KPI_T_FCZJXZBB增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_FCZJXZBB' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        execute immediate Q'{alter table P#KPI_T_FCZJXZBB  add ISDELETE CHAR(1)  DEFAULT 0}';
    END IF;

    -------------------------备份表物理表增加字段---------------------------
    --KPI_T_FCZJXZBB_BAK增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_FCZJXZBB_BAK' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        SELECT count(1) into v_n FROM USER_TABLES WHERE upper(TABLE_NAME)='P#KPI_T_FCZJXZBB_BAK';
        IF v_n = 1 THEN
            execute immediate Q'{alter table P#KPI_T_FCZJXZBB_BAK  add ISDELETE CHAR(1)  DEFAULT 0}';
        END IF;
    END IF;

    -------------------------获取tableId-------------------------
    SELECT tableid INTO v_tableid FROM dict_t_model where dbtablename = 'KPI_T_FCZJXZBB';
    SELECT tableid INTO v_busi_tableid FROM dict_t_model where dbtablename = 'KPI_V_FINAINDI';
    -------------------------factor表登记新增字段-------------------------
    for V_ROW in (select * from pub_t_partition_divid t where t.year <> '*') LOOP
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_tableid,'','2BA041C0841A4924ADF8CA7BCEDB7EC0','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,'','','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_tableid AND DBCOLUMNNAME = 'ISDELETE');
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_busi_tableid,'','FD66B49B930C4FE98D931CD36AC9ED3F','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,v_tableid,'2BA041C0841A4924ADF8CA7BCEDB7EC0','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_busi_tableid AND DBCOLUMNNAME = 'ISDELETE');
    END LOOP;
    sys_p_recreate_views(v_tableid);
    sys_p_recreate_views(v_busi_tableid);
    -------------------------物理表增加字段---------------------------
    --KPI_T_PEVALINDI增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_PEVALINDI' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        execute immediate Q'{alter table P#KPI_T_PEVALINDI  add ISDELETE CHAR(1)  DEFAULT 0}';
    END IF;

    -------------------------备份表物理表增加字段---------------------------
    --KPI_T_PEVALINDI_BAK增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_PEVALINDI_BAK' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        SELECT count(1) into v_n FROM USER_TABLES WHERE upper(TABLE_NAME)='P#KPI_T_PEVALINDI_BAK';
        IF v_n = 1 THEN
            execute immediate Q'{alter table P#KPI_T_PEVALINDI_BAK  add ISDELETE CHAR(1)  DEFAULT 0}';
        END IF;
    END IF;

    -------------------------获取tableId-------------------------
    SELECT tableid INTO v_tableid FROM dict_t_model where dbtablename = 'KPI_T_PEVALINDI';
    SELECT tableid INTO v_busi_tableid FROM dict_t_model where dbtablename = 'KPI_V_PROJEVAL';
    -------------------------factor表登记新增字段-------------------------
    for V_ROW in (select * from pub_t_partition_divid t where t.year <> '*') LOOP
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_tableid,'','7D98296024F54D33BA1F62EFBD29E14D','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,'','','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_tableid AND DBCOLUMNNAME = 'ISDELETE');
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_busi_tableid,'','9293AC10E6C548CFB5054043AD34B83A','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,v_tableid,'7D98296024F54D33BA1F62EFBD29E14D','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_busi_tableid AND DBCOLUMNNAME = 'ISDELETE');
    END LOOP;
    sys_p_recreate_views(v_tableid);
    sys_p_recreate_views(v_busi_tableid);
    -------------------------物理表增加字段---------------------------
    --KPI_T_FEVALINDI增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_FEVALINDI' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        execute immediate Q'{alter table P#KPI_T_FEVALINDI  add ISDELETE CHAR(1)  DEFAULT 0}';
    END IF;

    -------------------------备份表物理表增加字段---------------------------
    --KPI_T_FEVALINDI_BAK增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_FEVALINDI_BAK' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        SELECT count(1) into v_n FROM USER_TABLES WHERE upper(TABLE_NAME)='P#KPI_T_FEVALINDI_BAK';
        IF v_n = 1 THEN
            execute immediate Q'{alter table P#KPI_T_FEVALINDI_BAK  add ISDELETE CHAR(1)  DEFAULT 0}';
        END IF;
    END IF;

    -------------------------获取tableId-------------------------
    SELECT tableid INTO v_tableid FROM dict_t_model where dbtablename = 'KPI_T_FEVALINDI';
    SELECT tableid INTO v_busi_tableid FROM dict_t_model where dbtablename = 'KPI_V_SPFEVAL';
    -------------------------factor表登记新增字段-------------------------
    for V_ROW in (select * from pub_t_partition_divid t where t.year <> '*') LOOP
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_tableid,'','3759AA33D8C14FD988E23648D741DB97','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,'','','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_tableid AND DBCOLUMNNAME = 'ISDELETE');
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_busi_tableid,'','633E83AB343C4BF6B7991A31CDEF3E2C','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,v_tableid,'3759AA33D8C14FD988E23648D741DB97','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_busi_tableid AND DBCOLUMNNAME = 'ISDELETE');
    END LOOP;
    sys_p_recreate_views(v_tableid);
    sys_p_recreate_views(v_busi_tableid);
    -------------------------物理表增加字段---------------------------
    --KPI_T_BMPEVALUATION增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_BMPEVALUATION' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        execute immediate Q'{alter table P#KPI_T_BMPEVALUATION  add ISDELETE CHAR(1)  DEFAULT 0}';
    END IF;

    -------------------------备份表物理表增加字段---------------------------
    --KPI_T_BMPEVALUATION_BAK增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_BMPEVALUATION_BAK' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        SELECT count(1) into v_n FROM USER_TABLES WHERE upper(TABLE_NAME)='P#KPI_T_BMPEVALUATION_BAK';
        IF v_n = 1 THEN
            execute immediate Q'{alter table P#KPI_T_BMPEVALUATION_BAK  add ISDELETE CHAR(1)  DEFAULT 0}';
        END IF;
    END IF;

    -------------------------获取tableId-------------------------
    SELECT tableid INTO v_tableid FROM dict_t_model where dbtablename = 'KPI_T_BMPEVALUATION';
    SELECT tableid INTO v_busi_tableid FROM dict_t_model where dbtablename = 'KPI_V_DEPTEVAL';
    -------------------------factor表登记新增字段-------------------------
    for V_ROW in (select * from pub_t_partition_divid t where t.year <> '*') LOOP
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_tableid,'','4889FF8855224BBE93CD2A652ABAF9D1','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,'','','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_tableid AND DBCOLUMNNAME = 'ISDELETE');
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_busi_tableid,'','B6DC6E265E014627820E578BBA7FDD22','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,v_tableid,'4889FF8855224BBE93CD2A652ABAF9D1','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_busi_tableid AND DBCOLUMNNAME = 'ISDELETE');
    END LOOP;
    sys_p_recreate_views(v_tableid);
    sys_p_recreate_views(v_busi_tableid);
    -------------------------物理表增加字段---------------------------
    --KPI_T_CZPEVALUATION增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_CZPEVALUATION' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        execute immediate Q'{alter table P#KPI_T_CZPEVALUATION  add ISDELETE CHAR(1)  DEFAULT 0}';
    END IF;

    -------------------------备份表物理表增加字段---------------------------
    --KPI_T_CZPEVALUATION_BAK增加 ISDELETE 字段
    SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_CZPEVALUATION_BAK' and upper(column_name)= 'ISDELETE';
    IF v_n = 0 THEN
        SELECT count(1) into v_n FROM USER_TABLES WHERE upper(TABLE_NAME)='P#KPI_T_CZPEVALUATION_BAK';
        IF v_n = 1 THEN
            execute immediate Q'{alter table P#KPI_T_CZPEVALUATION_BAK  add ISDELETE CHAR(1)  DEFAULT 0}';
        END IF;
    END IF;

    -------------------------获取tableId-------------------------
    SELECT tableid INTO v_tableid FROM dict_t_model where dbtablename = 'KPI_T_CZPEVALUATION';
    SELECT tableid INTO v_busi_tableid FROM dict_t_model where dbtablename = 'KPI_V_FINAEVEL';
    -------------------------factor表登记新增字段-------------------------
    for V_ROW in (select * from pub_t_partition_divid t where t.year <> '*') LOOP
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_tableid,'','C2D634B1FF50490FB97B1725FA71955B','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,'','','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_tableid AND DBCOLUMNNAME = 'ISDELETE');
            INSERT INTO P#DICT_T_FACTOR(PROVINCE,YEAR,TABLEID,DEID,COLUMNID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,NULLABLE,DEFAULTVALUE,CSID,ISUPDATE,ORDERID,FRMTABID,FRMCOLID,SUPERID,ISLEAF,LEVELNO,ALIAS,COLFORMAT,SHOWFORMAT,SHOWWIDTH,ISKEY,ISVISIBLE,ISRESERVE,ISSUM,ISREGEX,REGEXPR,REGEXPRINFO,ISBANDCOL,BANDREFDWCOL,EXTPROP,COLTIPS,ISVIRTUAL,VIRCONTEXT,ISHREF,HREFLOC,HREFPARMID,BGTLVL,STATUS,BANDCOLUMNID,PARENTNODECANCHECK,OPENWINDOWTYPE,XLSXCOLUMNID)
            SELECT V_ROW.DISTRICTID,V_ROW.YEAR,v_busi_tableid,'','96B073B3C03B4B728AB92A3E223FF774','是否可删除','ISDELETE',3,1,0,'1','0','','1',26,v_tableid,'C2D634B1FF50490FB97B1725FA71955B','0','1',1,'','','0',100,'0','0','0','0','0','','','0','','0000000000000000000000000000000','','0','','0','','','','1','','0','1',''
            FROM DUAL
            WHERE NOT EXISTS(SELECT 1 FROM P#DICT_T_FACTOR WHERE PROVINCE = V_ROW.DISTRICTID AND YEAR = V_ROW.YEAR AND STATUS = '1' AND TABLEID = v_busi_tableid AND DBCOLUMNNAME = 'ISDELETE');
    END LOOP;
    sys_p_recreate_views(v_tableid);
    sys_p_recreate_views(v_busi_tableid);
    */
END;
--WJP_1129_项目库_绩效指标评价表表新增ISDELETE字段
