CREATE OR REPLACE VIEW SPF_V_PBAKLOG AS
SELECT
( SELECT C.NAME FROM FASP_T_CAUSER C WHERE C.GUID=A.BAKUSERID ) AS BAKUSERID ,to_char(a.DBVERSION,'YYYY-MM-DD HH24:MI')as dbversion,a.BAKVERSION,a.SPFID,a.PROJECTID,A.DATAKEY
   FROM Spf_t_Pbaseinfo_Bak A
--项目备份页面加入备份人
