DECLARE
  v_n number(6) :=0;
BEGIN
  SELECT count(1) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#KPI_T_STAGESTATUS' and upper(column_name)='ISADJUST'; 
   --P#KPI_T_STAGESTATUS添加  ISADJUST  字段
  if v_n=0 then
     execute immediate Q'{alter table P#KPI_T_STAGESTATUS add ISADJUST char(1)}';
     execute immediate Q'{
		 CREATE OR REPLACE VIEW KPI_T_STAGESTATUS AS
     SELECT PROCESSID ,DATAID ,DATAKEY ,OPERATIONNAME ,DOCID,ISFINAL,ISADJUST,DBVERSION, STATUS  FROM P#KPI_T_STAGESTATUS
		 WHERE STATUS='1'  AND PROVINCE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID')}';
		 END IF;
END;
--绩效_160803绩效审核中间表增加ISADJUST字段_WJP
