DELETE FROM P#DICT_T_FACTORCODE
   WHERE TABLEID IN
         (SELECT TABLEID
            FROM DICT_T_MODELCODE
           WHERE DBTABLENAME = 'CODE_T_PROJECTANDSPF')
     AND DBCOLUMNNAME NOT IN
         (SELECT COLUMN_NAME
            FROM USER_TAB_COLUMNS
           WHERE TABLE_NAME = 'CODE_T_PROJECTANDSPF')
--Çå³ýCODE_T_PROJECTANDSPF¶àÓà×Ö¶Î_DF_
