--3位部门预算代码 + 3位二级预算单位代码 + 3位三级预算单位代码(或000) + 3位四级预算单位代码(或000)+2位项目编制年份码 + 4位顺序码
--等同于：预算单位代码(不足12位补0) + 2位项目编制年份码 + 4位顺序码
DECLARE
  AGENCYCODE VARCHAR2(32);
  YEARCODE VARCHAR2(32);
  SERIALCODE VARCHAR2(32);
  ACLENGTH  number(3) :=0;
BEGIN
  FOR C_PROJ IN (SELECT X.PROJECTID,X.PROJCODE, X.PROJTYPEID, X.CREATEUSER FROM SPF_T_PBASEINFO X WHERE X.PROJCODE IS NULL) LOOP
    --预算单位代码、长度
    SELECT c.CODE, LENGTH(c.CODE) INTO AGENCYCODE, ACLENGTH FROM CODE_T_AGENCY c
      WHERE c.GUID = (SELECT UPAGENCYID FROM SECU_T_USER WHERE GUID = C_PROJ.CREATEUSER);

    -- 不足12位补0
    WHILE ACLENGTH < 12 LOOP
      AGENCYCODE := AGENCYCODE + '000';
      ACLENGTH := ACLENGTH + 3;
    END LOOP;

    --年度代码
    SELECT SUBSTR(GLOBAL_MULTYEAR_CZ.Secu_f_Global_Parm('YEAR'), 3, 2) INTO YEARCODE FROM DUAL;

    --顺序码
    SELECT NVL(LPAD(MAX(SUBSTR(a.PROJCODE, -4) + 1), 4, '0'), LPAD('1', 4, '0')) SERIAL
    INTO SERIALCODE
    FROM SPF_T_PBASEINFO a
    WHERE a.PROJTYPEID = C_PROJ.PROJTYPEID;
    UPDATE SPF_T_PBASEINFO SET PROJCODE = AGENCYCODE||YEARCODE||SERIALCODE WHERE PROJECTID = C_PROJ.PROJECTID;
  END LOOP;
END;
--周兆坤_批量修改专项项目编码（等同二级项目新规则）
