BEGIN
EXECUTE IMMEDIATE 'alter table P#SECU_T_COLTOTABLES add(ISSHOW CHAR(1) default 1,ISREAD CHAR(1) default 0)';
EXECUTE IMMEDIATE 'DROP VIEW SECU_T_COLTOTABLES';
EXECUTE IMMEDIATE Q'{
CREATE OR REPLACE VIEW SECU_T_COLTOTABLES AS
SELECT DATAKEY,NEEDUPDATE,ORDERID,FINYEAR,GUID,COLUMNID,TABLEID,RELATALBLEID,COLVALUENAME, COLVALUEID, STATUS, DBVERSION, ISSHOW, ISREAD
FROM P#SECU_T_COLTOTABLES
WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
END;--冯明华添加是否可写列及视图
