CREATE OR REPLACE PROCEDURE P_CREATE_OA_SYNONYM(P_DBLINK VARCHAR2) IS
  V_CNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_CNT FROM USER_DB_LINKS X WHERE X.DB_LINK = UPPER(P_DBLINK);
  IF V_CNT > 0 THEN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_DOCRELATEEXT  FOR HQOA_T_DOCRELATEEXT@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_BUSITYPE  FOR HQOA_T_BUSITYPE@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_DOCBGTRELATION  FOR HQOA_T_DOCBGTRELATION@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_BUSINESSTYPE  FOR HQOA_T_BUSINESSTYPE@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_BUSI  FOR HQOA_T_BUSI@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_DOCISSUED  FOR HQOA_T_DOCISSUED@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_DOCTEMP  FOR HQOA_T_DOCTEMP@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM OA_P_IMPSENDDOC  FOR OA_P_IMPSENDDOC@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_DOCRELATE  FOR HQOA_T_DOCRELATE@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_RECEIVEFILE  FOR HQOA_T_RECEIVEFILE@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_SENDFILE  FOR HQOA_T_SENDFILE@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_DOCEXTINFO  FOR HQOA_T_DOCEXTINFO@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM OA_P_IMPRECEIVEDOC  FOR OA_P_IMPRECEIVEDOC@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM OA_P_IMPSENDDOC_ORG  FOR OA_P_IMPSENDDOC_ORG@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM OA_P_DELETE_DOCINDI  FOR OA_P_DELETE_DOCINDI@'||P_DBLINK;
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_V_RELATEDOC  FOR HQOA_V_RELATEDOC@'||P_DBLINK;
  ELSE
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_DOCRELATEEXT  FOR '||P_DBLINK||'.HQOA_T_DOCRELATEEXT';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_BUSITYPE  FOR '||P_DBLINK||'.HQOA_T_BUSITYPE';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_DOCBGTRELATION  FOR '||P_DBLINK||'.HQOA_T_DOCBGTRELATION';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_BUSINESSTYPE  FOR '||P_DBLINK||'.HQOA_T_BUSINESSTYPE';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_BUSI  FOR '||P_DBLINK||'.HQOA_T_BUSI';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_DOCISSUED  FOR '||P_DBLINK||'.HQOA_T_DOCISSUED';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_DOCTEMP  FOR '||P_DBLINK||'.HQOA_T_DOCTEMP';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM OA_P_IMPSENDDOC  FOR '||P_DBLINK||'.OA_P_IMPSENDDOC';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_DOCRELATE  FOR '||P_DBLINK||'.HQOA_T_DOCRELATE';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_RECEIVEFILE  FOR '||P_DBLINK||'.HQOA_T_RECEIVEFILE';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_SENDFILE  FOR '||P_DBLINK||'.HQOA_T_SENDFILE';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_T_DOCEXTINFO  FOR '||P_DBLINK||'.HQOA_T_DOCEXTINFO';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM OA_P_IMPRECEIVEDOC  FOR '||P_DBLINK||'.OA_P_IMPRECEIVEDOC';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM OA_P_IMPSENDDOC_ORG  FOR '||P_DBLINK||'.OA_P_IMPSENDDOC_ORG';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM OA_P_DELETE_DOCINDI  FOR '||P_DBLINK||'.OA_P_DELETE_DOCINDI';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM HQOA_V_RELATEDOC  FOR '||P_DBLINK||'.HQOA_V_RELATEDOC';
  END IF;
  RETURN;
END P_CREATE_OA_SYNONYM;
--SPF_P_CREATE_OA_SYNONYM
