CREATE OR REPLACE FUNCTION F_SPF_GETAGENCYDLPOWER(V_SPFID     VARCHAR2,
                                                  V_PROJECTID VARCHAR2)
  RETURN TYPE_SPF_AGENCYDLPOWERTABLE IS
  V_AGENCYDLPOWER1   TYPE_SPF_AGENCYDLPOWERTABLE;
  V_AGENCYDLPOWER    TYPE_SPF_AGENCYDLPOWERTABLE;
  V_USERTYPE         VARCHAR2(32);
  V_DIVISION         VARCHAR2(32);
  V_AGENCYID         VARCHAR2(32);
  V_USERDISTRICTID   VARCHAR2(32);
  V_USERAGENGCYLVLID VARCHAR2(100);
  V_SPFDISTRICTID    VARCHAR2(32);
BEGIN
  SELECT USERTYPE, DIVISION, UPAGENCYID, ADMDIV
    INTO V_USERTYPE, V_DIVISION, V_AGENCYID, V_USERDISTRICTID
    FROM FASP_T_CAUSER
   WHERE GUID = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('USER');
  SELECT DISTRICTID
    INTO V_SPFDISTRICTID
    FROM SPF_T_FBASEINFO
   WHERE SPFID = V_SPFID;

  --恒把自己申报的单位拼上
  SELECT AGENCYID
    BULK COLLECT
    INTO V_AGENCYDLPOWER1
    FROM SPF_T_PBASEINFO
   WHERE PROJECTID = V_PROJECTID;

  --如果是本级专项
  IF V_USERDISTRICTID = V_SPFDISTRICTID THEN
    --财政用户
    IF V_USERTYPE = '1' THEN
      --申报单位限制过滤
      SELECT X.GUID
        BULK COLLECT
        INTO V_AGENCYDLPOWER
        FROM CODE_T_AGENCY_SPFDL X, CODE_T_AGENCY_SPF Y
       WHERE X.LVLID LIKE Y.LVLID || '%'
         AND Y.DISTRICTID = V_USERDISTRICTID
         AND Y.GUID IN (SELECT AGENCYID
                          FROM SPF_T_FDECLAREAGENCY AGEN
                         WHERE AGEN.SPFID = V_SPFID);
      RETURN V_AGENCYDLPOWER1 MULTISET UNION V_AGENCYDLPOWER;
    END IF;
    --部门用户
    IF V_USERTYPE = '2' THEN
      SELECT LVLID
        INTO V_USERAGENGCYLVLID
        FROM CODE_T_AGENCY_SPF
       WHERE GUID = V_AGENCYID;
      --申报单位限制过滤,并且只能是本部门下的
      SELECT X.GUID
        BULK COLLECT
        INTO V_AGENCYDLPOWER
        FROM (SELECT GUID, LVLID
                FROM CODE_T_AGENCY_SPFDL
               WHERE LVLID LIKE V_USERAGENGCYLVLID || '%') X,
             CODE_T_AGENCY_SPF Y
       WHERE X.LVLID LIKE Y.LVLID || '%'
         AND Y.LVLID like
                       (SELECT lvlid
                          FROM code_t_agency_spf
                         where guid = V_AGENCYID) || '%'
         AND Y.GUID IN (SELECT AGENCYID
                          FROM SPF_T_FDECLAREAGENCY AGEN
                         WHERE AGEN.SPFID = V_SPFID);
      RETURN V_AGENCYDLPOWER1 MULTISET UNION V_AGENCYDLPOWER;
    END IF;
    --非本级专项
  ELSE
    --财政用户
    IF V_USERTYPE = '1' THEN
      --申报单位限制过滤
      SELECT X.GUID
        BULK COLLECT
        INTO V_AGENCYDLPOWER
        FROM CODE_T_AGENCY_SPFDL X, CODE_T_AGENCY_SPF Y
       WHERE X.LVLID LIKE Y.LVLID || '%'
         AND Y.DISTRICTID = V_USERDISTRICTID
         AND Y.GUID IN (SELECT CUSTODYDECLRANGE
                          FROM SPF_T_CUSTODYMIDDLE CUST
                         WHERE CUST.SPFID = V_SPFID);
      RETURN V_AGENCYDLPOWER1 MULTISET UNION V_AGENCYDLPOWER;
    END IF;
    --部门用户
    IF V_USERTYPE = '2' THEN
      SELECT LVLID
        INTO V_USERAGENGCYLVLID
        FROM CODE_T_AGENCY_SPF
       WHERE GUID = V_AGENCYID;
      --申报单位限制过滤,并且只能是本部门下的
      SELECT X.GUID
        BULK COLLECT
        INTO V_AGENCYDLPOWER
        FROM (SELECT GUID, LVLID
                FROM CODE_T_AGENCY_SPFDL
               WHERE LVLID LIKE V_USERAGENGCYLVLID || '%') X,
             CODE_T_AGENCY_SPF Y
       WHERE X.LVLID LIKE Y.LVLID || '%'
         AND Y.LVLID like
                       (SELECT lvlid
                          FROM code_t_agency_spf
                         where guid = V_AGENCYID) || '%'
         AND Y.GUID IN (SELECT CUSTODYDECLRANGE
                          FROM SPF_T_CUSTODYMIDDLE CUST
                         WHERE CUST.SPFID = V_SPFID);
      RETURN V_AGENCYDLPOWER1 MULTISET UNION V_AGENCYDLPOWER;
    END IF;
    RETURN V_AGENCYDLPOWER1;
  END IF;
  RETURN V_AGENCYDLPOWER1;
END;
--F_SPF_GETAGENCYDLPOWER
