DECLARE
begin
EXECUTE IMMEDIATE Q'/CREATE OR REPLACE VIEW SPF_T_SPFPYJHIST AS
SELECT HIST.BATCHID,
       (SELECT TITLE FROM BD_T_BATCH WHERE BATCHID = HIST.BATCHID) TITLE,
       HIST.BUSITYPEID,
       HIST.CREATEUSER,
       HIST.DATAKEY,
       HIST.OBJECTID,
       HIST.DISTRICTID,
       HIST.REMARK,
       HIST.SOURCEAGENCYID,
       HIST.SOURCEBATCHID,
       HIST.STEP,
       HIST.TARGETAGENCYID,
       HIST.WFDIRECTION,
       HIST.WFSTATUS,
       SPFYJ.SPFID,
       SPFYJ.AGENCYID,
       SPFYJ.PROJTYPEID,
       SPFYJ.SETUPSTATUS,
       (CASE
         WHEN (SPFYJ.SETUPSTATUS = 0) THEN
          '未设立'
         WHEN (SPFYJ.SETUPSTATUS = 1) THEN
          '已确认,未发布'
         ELSE
          '已设立'
       END) SETUPSTATUSNAME,
       1 NEEDUPDATE,
       1 ORDERID,
       (SELECT BUSITYPENAME
          FROM BD_T_BUSITYPE
         WHERE BUSITYPEID = HIST.BUSITYPEID) BUSITYPENAME,
       TO_CHAR(SYSDATE, 'YYYY') FINYEAR
  FROM SPF_T_CFLOW_HIST HIST, SPF_V_SPFFMAINYJ SPFYJ
 WHERE SPFYJ.SPFID = HIST.OBJECTID/';
 
end;-----SPF_V_SPFPMAINEJ

--SPF_T_SPFPYJHIST
