DECLARE
begin
EXECUTE IMMEDIATE Q'/CREATE OR REPLACE VIEW SPF_T_SPFPYJHIST AS
SELECT HIST.BATCHID,
       (SELECT TITLE FROM BD_T_BATCH WHERE BATCHID = HIST.BATCHID) TITLE,
       HIST.BUSITYPEID,
       HIST.CREATEUSER,
       HIST.DATAKEY,
       HIST.OBJECTID,
       HIST.DISTRICTID,
       HIST.REMARK,
       HIST.SOURCEAGENCYID,
       HIST.SOURCEBATCHID,
       HIST.STEP,
       HIST.TARGETAGENCYID,
       HIST.WFDIRECTION,
       HIST.WFSTATUS,
       SPFYJ.SPFID,
       SPFYJ.AGENCYID,
       SPFYJ.PROJTYPEID,
       SPFYJ.SETUPSTATUS,
       (CASE
         WHEN (SPFYJ.SETUPSTATUS = 0) THEN
          '未设立'
         WHEN (SPFYJ.SETUPSTATUS = 1) THEN
          '已确认,未发布'
         ELSE
          '已设立'
       END) SETUPSTATUSNAME,
       SPFYJ.SPFNAME,
       1 NEEDUPDATE,
       1 ORDERID,
       (SELECT BUSITYPENAME
          FROM BD_T_BUSITYPE
         WHERE BUSITYPEID = HIST.BUSITYPEID) BUSITYPENAME,
       TO_CHAR(SYSDATE, 'YYYY') FINYEAR
  FROM SPF_T_CFLOW_HIST HIST, SPF_V_SPFFMAINYJ SPFYJ
 WHERE SPFYJ.SPFID = HIST.OBJECTID/';

DELETE FROM P#dict_t_Factor WHERE tableid='4CCF7F63AC9F5A78E0533A06A8C05145' AND columnid in ('4CCF7F63ACAB5A78E0533A06A8C05145','4CCF7F63ACAC5A78E0533A06A8C05145','4CCF7F63ACAD5A78E0533A06A8C05145','525C2E77C2D81B3CE0533906A8C05ACB');

FOR V_ROW IN(SELECT * FROM PUB_T_PARTITION_DIVID T WHERE T.YEAR <> '*') LOOP   
BEGIN

insert into P#DICT_T_FACTOR (YEAR, PROVINCE, ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.year,V_ROW.Districtid, null, null, null, null, null, null, '4CCF7F63ACAB5A78E0533A06A8C05145', '506ADE82C24433E7E0533906A8C0E389', '32', '6', 'WFDIRECTION', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', '1', '流程方向', '1', '12', null, null, null, '4', null, '1', '0', '4CCF7F63AC9F5A78E0533A06A8C05145', null, '0', null);

insert into P#DICT_T_FACTOR (YEAR, PROVINCE, ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.year,V_ROW.Districtid, null, null, null, null, null, null, '4CCF7F63ACAC5A78E0533A06A8C05145', null, '1', '3', 'WFSTATUS', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '1', '流程状态', '1', '13', null, null, null, null, null, '1', '0', '4CCF7F63AC9F5A78E0533A06A8C05145', null, '0', null);

insert into P#DICT_T_FACTOR (YEAR, PROVINCE, ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.year,V_ROW.Districtid, null, null, null, null, null, null, '4CCF7F63ACAD5A78E0533A06A8C05145', null, '32', '3', 'SPFID', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '1', '专项编号', '1', '14', null, null, null, '0', null, '1', '0', '4CCF7F63AC9F5A78E0533A06A8C05145', null, '0', null);

insert into P#DICT_T_FACTOR (YEAR, PROVINCE, ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.year,V_ROW.Districtid, null, null, null, null, null, null, '525C2E77C2D81B3CE0533906A8C05ACB', null, '200', '3', 'SPFNAME', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', '1', '专项名称', '1', '24', null, null, '0', '0', null, '1', '0', '4CCF7F63AC9F5A78E0533A06A8C05145', null, '0', null);

 end;
 end loop;
end;-----SPF_T_SPFPYJHIST  
--SPF_T_SPFPYJHIST
