CREATE OR REPLACE VIEW SPF_T_OARELATION AS 
SELECT DBVERSION,
       DOCID,
       GUID,
       ORGID,
       REMARK,
       STATUS,
       TASKID,
       TASKTYPE,
       USERID
  FROM P#SPF_T_OARELATION
 WHERE YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR')
   AND STATUS = '1'
--SPF_T_OARELATION
