DECLARE
 v_n1 number(8) := 0;
 BEGIN
  select count(1)
    into v_n1
    from user_tables
   where upper(table_name) = 'P#SPF_T_YWQLSB';
  if v_n1 = 0 then
    execute immediate Q'{create table SPF_T_YWQLSB(DATAKEY VARCHAR2(32) default SYS_GUID() not null,
     ORDERID  number(9),NEEDUPDATE VARCHAR(4000),FINYEAR VARCHAR(4),AGENCYID VARCHAR(32),BUSIDATAKEY VARCHAR(32),OWNNERID VARCHAR(32),BATCHID VARCHAR(32),YWBID VARCHAR(32),OPERATETYPE VARCHAR(32),BUSITYPEID VARCHAR(32),SOURCEBATCHID VARCHAR(32))}';
    execute immediate 'alter table SPF_T_YWQLSB add constraint SPF_T_YWQLSB  primary key (DATAKEY)';
     SYS_P_PARTITION_TABLE('SPF_T_YWQLSB');
  end if;

       /*插入dealtype*/
  delete from dict_t_dealtype where dealid='67_JS';
    Insert into dict_t_dealtype (APPID,DEALID,DEALNAME,ORDERID,NEEDCONFIG,ISUNIQUE) values ('SPF','67_JS','业务区临时表',13,'0','0');
    delete from P#dict_t_model WHERE tableid ='4AE7F264D0773498E0533A06A8C0428E';
    delete from P#dict_t_factor where tableid ='4AE7F264D0773498E0533A06A8C0428E';
  DELETE FROM dict_t_defaultcol WHERE dealid ='67_JS';
  insert into dict_t_defaultcol (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS, DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  values ('67_JS', 1, '行标识', 'DATAKEY', 3, 32, null, null, '1', '1', sys_guid(), '1',  null, '1', '080001', '0', '0');
   EXECUTE IMMEDIATE Q'/CREATE OR REPLACE VIEW SPF_T_YWQLSB AS
SELECT DBVERSION,
       STATUS,
       BUSITYPEID,
       NEEDUPDATE,
       YWBID,
       SOURCEBATCHID,
       AGENCYID,
       BUSIDATAKEY,
       OPERATETYPE,
       FINYEAR,
       DATAKEY,
       ORDERID,
       OWNNERID,
       BATCHID
  FROM P#SPF_T_YWQLSB p#spf_t_ywqlsb
 WHERE STATUS = '1'/';
     EXECUTE IMMEDIATE Q'/CREATE OR REPLACE VIEW SPF_T_YWQLSB AS
SELECT DBVERSION,
       STATUS,
       BUSITYPEID,
       NEEDUPDATE,
       YWBID,
       SOURCEBATCHID,
       AGENCYID,
       BUSIDATAKEY,
       OPERATETYPE,
       FINYEAR,
       DATAKEY,
       ORDERID,
       OWNNERID,
       BATCHID
  FROM P#SPF_T_YWQLSB p#spf_t_ywqlsb
 WHERE STATUS = '1'/';
 for v_row in(select * from pub_t_partition_divid t where t.year <> '*') loop
  begin
insert into P#dict_t_model (YEAR, PROVINCE, TABLEID, NAME, ORDERID, DBTABLENAME, TABLETYPE, ISSHOW, APPID, REMARK, SUITID, DEALTYPE, ISRESERVED, INPUTLVL, ISADD, SHORTTITLE, EXTPROP, BGTLVL, SECUSQL, ISSUMTAB, ISMAN, MAINUPTAB, RELATAB, TABSWHERE, ISPARTITION, STATUS, ISBAK, INITSQL, INITSQLTIME, ISTASK, ISALLDISTRICT, DESCFILE, ISALLYEAR, INITSQLBTNNAME, ISEXCELIMP, ISREADONLY, ISSAVEFORMULA)
values (v_row.year, v_row.districtid, '4AE7F264D0773498E0533A06A8C0428E', '业务区临时表', 1, 'SPF_T_YWQLSB', '1', '1', 'SPF','', 'FB12E708FE56425F82EF3D89FDE0D0EF', '67_JS', '0', '3', '0', '', '0000000000000000000000000000000', '', '', '0', '0', '', '', '', '1', '1', '0', '', '1', '0', '1', '', '1', '', '0', '0', '0');


insert into P#dict_t_factor (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE, ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID, PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.year, v_row.districtid, '4AE7F264D0773498E0533A06A8C0428E', '080001', '4AE7F264D0783498E0533A06A8C0428E', '行标志', 'DATAKEY', 3, 32, 0, '1', 'sys_guid()', '', '1', 1, '0', '1', 1, '行标志', '', '', null, '0', '1', '1', '0', '0', '', '', '0', '', '', '行标志', '', '', '0', '', '0', '', '', '', '1', '', '0', '', '');

insert into P#dict_t_factor (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE, ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID, PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.year, v_row.districtid, '4AE7F264D0773498E0533A06A8C0428E', '', '4AE7F264D0793498E0533A06A8C0428E', '排序序号', 'ORDERID', 1, 9, 0, '1', '', '', '1', 2, '0', '1', 1, '排序序号', '', '', null, '0', '1', '1', '0', '0', '', '', '0', '', '', '排序序号', '', '', '0', '', '0', '', '', '', '1', '', '0', '', '');

insert into P#dict_t_factor (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE, ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID, PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.year, v_row.districtid, '4AE7F264D0773498E0533A06A8C0428E', '', '4AE7F264D07A3498E0533A06A8C0428E', '刷新标志', 'NEEDUPDATE', 3, 4000, 0, '1', '', '', '1', 3, '0', '1', 1, '刷新标志', '', '', null, '0', '1', '1', '0', '0', '', '', '0', '', '', '刷新标志', '', '', '0', '', '0', '', '', '', '1', '', '0', '', '');

insert into P#dict_t_factor (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE, ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID, PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.year, v_row.districtid, '4AE7F264D0773498E0533A06A8C0428E', '10206', '4AE7F264D07B3498E0533A06A8C0428E', '财年', 'FINYEAR', 3, 4, 0, '1', '', '', '1', 4, '0', '1', 1, '财年', '', '', null, '0', '1', '1', '0', '0', '', '', '0', '', '', '财年', '', '', '0', '', '0', '', '', '', '1', '', '0', '', '');

insert into P#dict_t_factor (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE, ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID, PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.year, v_row.districtid, '4AE7F264D0773498E0533A06A8C0428E', '10401', '4AE7F264D07C3498E0533A06A8C0428E', '预算单位', 'AGENCYID', 3, 32, 0, '1', '', '', '1', 5, '0', '1', 1, '预算单位', '', '', null, '0', '1', '1', '0', '0', '', '', '0', '', '', '预算单位', '', '', '0', '', '0', '', '', '', '1', '', '0', '', '');

insert into P#dict_t_factor (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE, ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID, PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.year, v_row.districtid, '4AE7F264D0773498E0533A06A8C0428E', '', '4AE844B7156D365BE0533A06A8C0DF9F', '业务数据行标示', 'BUSIDATAKEY', 3, 32, 0, '1', '', '', '1', 6, '0', '1', 1, '', '', '0', null, '0', '1', '0', '0', '0', '', '', '0', '', '0000000000000000000000000000000', '', '', '', '0', '', '0', '', '', '', '1', '', '0', '1', '');

insert into P#dict_t_factor (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE, ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID, PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.year, v_row.districtid, '4AE7F264D0773498E0533A06A8C0428E', '', '4AE844B7156E365BE0533A06A8C0DF9F', '所属人员', 'OWNNERID', 3, 32, 0, '1', '', '', '1', 7, '0', '1', 1, '', '', '0', null, '0', '1', '0', '0', '0', '', '', '0', '', '0000000000000000000000000000000', '', '', '', '0', '', '0', '', '', '', '1', '', '0', '1', '');

insert into P#dict_t_factor (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE, ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID, PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.year, v_row.districtid, '4AE7F264D0773498E0533A06A8C0428E', '', '4AE844B7156F365BE0533A06A8C0DF9F', '批次id', 'BATCHID', 3, 32, 0, '1', '', '', '1', 8, '0', '1', 1, '', '', '0', null, '0', '1', '0', '0', '0', '', '', '0', '', '0000000000000000000000000000000', '', '', '', '0', '', '0', '', '', '', '1', '', '0', '1', '');

insert into P#dict_t_factor (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE, ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID, PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.year, v_row.districtid, '4AE7F264D0773498E0533A06A8C0428E', '', '4B16C9D8978734A7E0533A06A8C0E13C', '业务表id', 'YWBID', 3, 32, 0, '1', '', '', '1', 9, '0', '1', 1, '', '', '0', null, '0', '1', '0', '0', '0', '', '', '0', '', '0000000000000000000000000000000', '', '', '', '0', '', '0', '', '', '', '1', '', '0', '1', '');

insert into P#dict_t_factor (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE, ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID, PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.year, v_row.districtid, '4AE7F264D0773498E0533A06A8C0428E', '', '4B5139E6929D2520E0533A06A8C017E2', '操作类型', 'OPERATETYPE', 3, 32, 0, '1', '', '', '1', 10, '0', '1', 1, '', '', '0', null, '0', '1', '0', '0', '0', '', '', '0', '', '0000000000000000000000000000000', '', '', '', '0', '', '0', '', '', '', '1', '', '0', '1', '');

insert into P#dict_t_factor (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE, ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID, PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.year, v_row.districtid, '4AE7F264D0773498E0533A06A8C0428E', '', '4B5E9B3340950BD6E0533A06A8C0F108', '业务类型id', 'BUSITYPEID', 3, 32, 0, '1', '', '', '1', 11, '0', '1', 1, '', '', '0', null, '0', '1', '0', '0', '0', '', '', '0', '', '0000000000000000000000000000000', '', '', '', '0', '', '0', '', '', '', '1', '', '0', '1', '');

insert into P#dict_t_factor (YEAR, PROVINCE, TABLEID, DEID, COLUMNID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, NULLABLE, DEFAULTVALUE, CSID, ISUPDATE, ORDERID, SUPERID, ISLEAF, LEVELNO, ALIAS, COLFORMAT, SHOWFORMAT, SHOWWIDTH, ISKEY, ISVISIBLE, ISRESERVE, ISSUM, ISREGEX, REGEXPR, REGEXPRINFO, ISBANDCOL, BANDREFDWCOL, EXTPROP, COLTIPS, FRMTABID, FRMCOLID, ISVIRTUAL, VIRCONTEXT, ISHREF, HREFLOC, HREFPARMID, BGTLVL, STATUS, BANDCOLUMNID, PARENTNODECANCHECK, OPENWINDOWTYPE, XLSXCOLUMNID)
values (v_row.year, v_row.districtid, '4AE7F264D0773498E0533A06A8C0428E', '', '4BC86F8A126E6CDBE0533A06A8C04C5B', '源批次id', 'SOURCEBATCHID', 3, 32, 0, '1', '', '', '1', 12, '0', '1', 1, '', '', '0', null, '0', '1', '0', '0', '0', '', '', '0', '', '0000000000000000000000000000000', '', '', '', '0', '', '0', '', '', '', '1', '', '0', '1', '');



    end;
 end loop;
 sys_p_recreate_views('4AE7F264D0773498E0533A06A8C0428E');
end;
--67_JS
