

DECLARE
  a integer;
  b integer;
  V_BAKCOL integer;
BEGIN
  SELECT COUNT(*) INTO a FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#SPF_T_PINVESTPLAN' AND COLUMN_NAME ='ISADJUST';
  IF a = 0 THEN  
    EXECUTE IMMEDIATE Q'{alter table P#SPF_T_PINVESTPLAN add ISADJUST CHAR(1) DEFAULT '0'}';
  END IF;
  SELECT COUNT(*) INTO a FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#SPF_T_PINVESTPLAN' AND COLUMN_NAME ='ADJUSTCOMMENT';
  IF a = 0 THEN  
    EXECUTE IMMEDIATE Q'{alter table P#SPF_T_PINVESTPLAN add ADJUSTCOMMENT VARCHAR2(500)}';
  END IF;
  delete from dict_t_factor t where t.TABLEID = (select tableid from dict_t_model where dbtablename = 'SPF_T_PINVESTPLAN') and DBCOLUMNNAME in ('ISADJUST','ADJUSTCOMMENT');
  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
values (null, null, null, null, null, null, '282D7328957130DEE050A8C0210533AF', null, 32, 3, 'ISADJUST', '''0''', null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '0', '0', '0', 1, '是否调整', '1', 124, null, null, 0, '0', null, '1', '0', '14C0C3214F27189EE050A8C0210507CA', null,  '0', null);
insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
values (null, null, null, null, null, null, '282D7328957230DEE050A8C0210533AF', null, 500, 3, 'ADJUSTCOMMENT', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '调整原因', '1', 125, null, null, 0, '0', null, '1', '0', '14C0C3214F27189EE050A8C0210507CA', null,  '0', null);

  SELECT COUNT(*) INTO V_BAKCOL  FROM User_Tables WHERE TABLE_NAME = UPPER('P#SPF_T_PINVESTPLAN_BAK');
  SELECT COUNT(*) INTO a FROM COLS WHERE TABLE_NAME = UPPER('P#SPF_T_PINVESTPLAN_BAK') AND COLUMN_NAME = UPPER('ISADJUST');
  SELECT COUNT(*) INTO b FROM COLS WHERE TABLE_NAME = UPPER('P#SPF_T_PINVESTPLAN_BAK') AND COLUMN_NAME = UPPER('ADJUSTCOMMENT');
   IF V_BAKCOL=1 AND a = 0 THEN
         EXECUTE IMMEDIATE Q'{alter table P#SPF_T_PINVESTPLAN_BAK add ISADJUST CHAR(1) DEFAULT '0'}';
         END IF;
   IF V_BAKCOL=1 AND b = 0 THEN
         EXECUTE IMMEDIATE Q'{alter table P#SPF_T_PINVESTPLAN_BAK add ADJUSTCOMMENT VARCHAR2(500)}';
         END IF;  
   sys_p_recreate_views('14C0C3214F27189EE050A8C0210507CA');
END;
--项目资金计划表添加字段
