CREATE OR REPLACE VIEW CODE_T_PROJECTANDSPFZY AS
SELECT 
 "GUID",
 "NAME",
 "SPFNAME",
 "AGENCYNAME",
 "AGENCYID",
 "PROJTYPEID",
 "CODE",
 "SUPERGUID",
 "ISLEAF",
 "LEVELNO",
 "TASKTYPE",
 "ID",
 "SHOWID",
 "ENDFLAG",
 "LVLID",
 "SUPERID",
 "FUNDLEVEL"
  FROM CODE_T_PROJECTANDSPF
 WHERE FUNDLEVEL = '1'
--DF_code_t_projectandspfzy
