CREATE OR REPLACE VIEW SPF_V_PMAIN AS
SELECT
A.DATAKEY,
A.AGENCYID,
         F.FIRAGENCYID,
         AGENCY.NAME AGENCYNAME,
         A.SPFID,
         A.PROJTYPEID,
         F.SPFNAME,
         A.PROJECTID,
         A.PROJCODE,
         A.PROJNAME  PROJNAME,
         A.PROJNAME||'{'||A.PROJECTID||'}' PROJGROUP_NAME,
       (SELECT  ACCT.NAME FROM CODE_V_ACCTCODE_OUT_SPF  ACCT WHERE ACCT.GUID  = a.EXPFUNCID) AS EXPFUNCCLASS,
        A.CREATEUSER,
        A.CREATETIME,
        NVL(A.UPSTATUS,'0') UPSTATUS,
        A.UPTIME,
        A.IMPORTANCE,
        A.DISTRICTID,
        A.ISBGT,
        A.ISINDEX,
        NVL(A.CHECKSTATUS,'0') CHECKSTATUS,
        A.ISINSTEAD,
        F.FUNDLEVEL,
        NVL((SELECT SUM(NVL(B.COUNTYAGNUM, 0))
             FROM SPF_T_PINVESTPLAN B
            WHERE B.PROJECTID = A.PROJECTID),
           0) COUNTYAGNUM,
        NVL((SELECT SUM(NVL(B.COUNTYNUM, 0))
             FROM SPF_T_PINVESTPLAN B
            WHERE B.PROJECTID = A.PROJECTID),
           0) COUNTYNUM,
        NVL((SELECT SUM(NVL(B.CITYAGNUM, 0))
             FROM SPF_T_PINVESTPLAN B
            WHERE B.PROJECTID = A.PROJECTID),
           0) CITYAGNUM,
        NVL((SELECT SUM(NVL(B.CITYNUM, 0))
             FROM SPF_T_PINVESTPLAN B
            WHERE B.PROJECTID = A.PROJECTID),
           0) CITYNUM,
        NVL((SELECT SUM(NVL(B.PROVAGNUM, 0))
             FROM SPF_T_PINVESTPLAN B
            WHERE B.PROJECTID = A.PROJECTID),
           0) PROVAGNUM,
        NVL((SELECT SUM(NVL(B.PROVNUM, 0))
             FROM SPF_T_PINVESTPLAN B
            WHERE B.PROJECTID = A.PROJECTID),
           0) PROVNUM,
        F.EXPFUNCID,
        a.ISTEMP,
        f.DISTRICTID Spf_districtid,
        a.TEMPCHECKSTATUS,
        a.TEMPUPSTATUS,
        A.DBVERSION,
        A.STATUS
    FROM SPF_T_PBASEINFO A ,CODE_T_FIRAGENCY AGENCY, SPF_T_FBASEINFO F
    WHERE F.FIRAGENCYID = AGENCY.GUID AND A.SPFID = F.SPFID
--SPF_V_PMAIN
