declare
begin
EXECUTE IMMEDIATE Q'/  
CREATE OR REPLACE VIEW CODE_T_AGENCY_SPFDL AS
SELECT A.GUID,
       A.CODE,
       A.NAME,
       A.SUPERGUID,
       A.ISLEAF,
       A.LEVELNO,
       A.DIVTYPE,
       A.ISDISTRICT,
       A.DISTRICTID,
       A.DISTRICTCODE,
       A.DISTRICTNAME,
       A.DISTRICTLVL,
       A.AGENCYTYPE,
       A.ID,
       A.ENDFLAG,
       A.LVLID,
       A.SUPERID,
       A.FININTORG
  FROM CODE_T_AGENCY_SPF A/';
  update p#dict_t_modelcode
   set dynamicwhere = '((CASE when (1 =(SELECT COUNT(1) FROM FASP_T_CAUSER US, SPF_T_FBASEINFO FI where FI.DISTRICTID = US.Admdiv AND US.GUID = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM(''USER'') AND FI.SPFID = ''$SPFID$'')) AND exists (SELECT GUID FROM Code_t_Agency_Spfdl dl where CODE_T_AGENCY_SPFDL.GUID = dl.GUID START WITH EXISTS (SELECT 1 FROM SPF_T_FDECLAREAGENCY AGEN WHERE AGEN.SPFID = ''$SPFID$'' AND DL.GUID = AGEN.AGENCYID) CONNECT BY PRIOR DL.GUID = DL.SUPERGUID) then 1 when (0 = (SELECT COUNT(1) FROM FASP_T_CAUSER US, SPF_T_FBASEINFO FI where FI.DISTRICTID = US.Admdiv AND US.GUID = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM(''USER'') AND FI.SPFID = ''$SPFID$'') AND exisTS (SELECT 1 FROM SPF_T_CUSTODYMIDDLE CUST where CUST.CUSTODYDECLRANGE = CODE_T_AGENCY_SPFDL.GUID AND SPFID = ''$SPFID$'')) then 1 else 0 end) = 1 AND EXISTS (select 1 from FASP_T_CAUSER U WHERE U.GUID = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM(''USER'') AND (CASE WHEN USERTYPE = 1 AND CODE_T_AGENCY_SPFDL.DISTRICTID = U.ADMDIV THEN 1 WHEN USERTYPE = 2 AND CODE_T_AGENCY_SPFDL.SUPERGUID = U.UPAGENCYID THEN 1 ELSE 0 END) = 1)) OR CODE_T_AGENCY_SPFDL.GUID = (SELECT AGENCYID FROM SPF_T_PBASEINFO WHERE PROJECTID = ''$PROJECTID$'')'
 where tableid = '223267AA7D472B22E050A8C021057ED5';
end;
--代录代码表脚本
