CREATE OR REPLACE PROCEDURE P_PROJ_COMBINED_VIEW(P_APPID VARCHAR2,P_SRC_TABLEID VARCHAR2,P_CREATED_OBJ_NAME VARCHAR2,P_CREATED_OBJ_CN_NAME VARCHAR2,P_DEALTYPE VARCHAR2,P_ISRECREATE CHAR DEFAULT '0') IS
  V_SQL VARCHAR2(32760);
  V_TABLEID VARCHAR2(32);
  V_COLUMNID VARCHAR2(32);
  V_CNT NUMBER;
  V_TMP VARCHAR2(30000);
  V_ORDERID NUMBER;
  V_SRC_TABLE VARCHAR2(30);
  V_NAME VARCHAR2(30);
  V_CNNAME VARCHAR2(30);
  TYPE R_ID_NAME IS RECORD
  (
    COLUMNID VARCHAR2(32),
    DBCOLUMNNAME VARCHAR2(30)
  );
  TYPE R_LIST IS TABLE OF R_ID_NAME;
  V_COLLIST R_LIST;
  V_INDEX BINARY_INTEGER;
  V_FUND BOOLEAN;
BEGIN
  SELECT COUNT(*) INTO V_CNT FROM DICT_T_MODEL WHERE TABLEID = P_SRC_TABLEID;
  IF V_CNT < 1 THEN
    RETURN;
  END IF;
  
  IF P_ISRECREATE = '0' THEN
    V_TABLEID := RAWTOHEX(SYS_GUID());
    V_NAME := P_CREATED_OBJ_NAME;
    V_CNNAME := P_CREATED_OBJ_CN_NAME;
    INSERT INTO DICT_T_MODEL(APPID, BGTLVL, DBTABLENAME, DEALTYPE, EXTPROP, INPUTLVL, ISADD, ISMAN, ISPARTITION, ISRESERVED, ISSHOW, ISTASK, ISSUMTAB, MAINUPTAB, NAME, ORDERID, RELATAB, REMARK, SECUSQL, INITSQLTIME, SHORTTITLE, SUITID, TABLEID, TABLETYPE,ISBAK,ISALLDISTRICT)
    SELECT P_APPID APPID, BGTLVL,V_NAME DBTABLENAME, P_DEALTYPE DEALTYPE, RPAD('0',100,'0') EXTPROP, INPUTLVL, ISADD, ISMAN, ISPARTITION,'0' ISRESERVED,'1' ISSHOW,'0' ISTASK, ISSUMTAB, MAINUPTAB, V_CNNAME NAME, ORDERID, RELATAB, REMARK, SECUSQL,'1' INITSQLTIME, SHORTTITLE, SUITID, V_TABLEID TABLEID, '2' TABLETYPE,'0' ISBAK,ISALLDISTRICT
    FROM DICT_T_MODEL
    WHERE TABLEID = P_SRC_TABLEID;
    
    SELECT TABLEID INTO V_TMP FROM DICT_T_MODEL WHERE DBTABLENAME = 'SPF_T_PBASEINFO';
    INSERT INTO DICT_T_FACTOR(ALIAS,BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, ISBANDCOL, OPENWINDOWTYPE,ISKEY,ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE,LEVELNO, NAME,NULLABLE, ORDERID, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS,SUPERID,TABLEID)
    SELECT ALIAS,BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, '0' ISBANDCOL, OPENWINDOWTYPE,'0' ISKEY,'1' ISLEAF,'0' ISREGEX,'1' ISRESERVE,'0' ISSUM,'0' ISUPDATE,'0' ISVIRTUAL,'1' ISVISIBLE,1 LEVELNO, NAME,'0' NULLABLE,0 ORDERID, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS,'0' SUPERID,V_TABLEID TABLEID
    FROM DICT_T_FACTOR 
    WHERE TABLEID = V_TMP
    AND DBCOLUMNNAME IN ('PROJNAME','PROJCODE','PROJTYPEID','SPFID');
    --处理ORDERID
    SELECT MAX(ORDERID ) INTO V_ORDERID FROM DICT_T_FACTOR WHERE TABLEID = V_TABLEID;
    UPDATE DICT_T_FACTOR SET ORDERID = 1 WHERE TABLEID = V_TABLEID AND DBCOLUMNNAME = 'PROJNAME' AND ISLEAF = '1';
    UPDATE DICT_T_FACTOR SET ORDERID = 2 WHERE TABLEID = V_TABLEID AND DBCOLUMNNAME = 'PROJCODE' AND ISLEAF = '1';
    UPDATE DICT_T_FACTOR SET ORDERID = 3 WHERE TABLEID = V_TABLEID AND DBCOLUMNNAME = 'PROJTYPEID' AND ISLEAF = '1';
    UPDATE DICT_T_FACTOR SET ORDERID = 4 WHERE TABLEID = V_TABLEID AND DBCOLUMNNAME = 'SPFID' AND ISLEAF = '1';
    
    INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
    VALUES ('查看明细', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 255, 3, 'CKMX',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '查看明细', '1', 4, NULL, NULL, 0, '0', NULL, '1', '0', V_TABLEID, NULL,  '0', NULL);

    INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
    VALUES ('相关公文', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 255, 3, 'XGGW',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '相关公文', '1', 5, NULL, NULL, 0, '0', NULL, '1', '0', V_TABLEID, NULL,  '0', NULL);
      
    INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
    VALUES ('项目分组名称', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 255, 3, 'PROJ_GROUP_NAME',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '项目分组名称', '1', 6, NULL, NULL, 0, '0', NULL, '1', '0', V_TABLEID, NULL,  '0', NULL);


    INSERT INTO DICT_T_FACTOR(ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,PARENTNODECANCHECK, XLSXCOLUMNID)
    SELECT ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID + 6 ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID,V_TABLEID TABLEID, VIRCONTEXT,PARENTNODECANCHECK, XLSXCOLUMNID
    FROM DICT_T_FACTOR
    WHERE TABLEID = P_SRC_TABLEID 
    AND (ISLEAF = '0' OR ISLEAF = '1' AND DBCOLUMNNAME NOT IN ('PROJNAME','PROJCODE','PROJTYPEID','SPFID','CKMX','XGGW','PROJ_GROUP_NAME'));
      
    --处理COLUMNID/SUPERID/BANDCOLUMNID
    FOR C_COL IN (SELECT TABLEID,COLUMNID,SUPERID FROM DICT_T_FACTOR WHERE TABLEID = V_TABLEID ) LOOP
      V_COLUMNID := RAWTOHEX(SYS_GUID());
      UPDATE DICT_T_FACTOR SET COLUMNID = V_COLUMNID WHERE TABLEID = V_TABLEID AND COLUMNID = C_COL.COLUMNID;
      UPDATE DICT_T_FACTOR SET SUPERID = V_COLUMNID WHERE TABLEID = V_TABLEID AND SUPERID =  C_COL.COLUMNID;
      UPDATE DICT_T_FACTOR SET BANDCOLUMNID = V_COLUMNID WHERE TABLEID = V_TABLEID AND BANDCOLUMNID =  C_COL.COLUMNID;
    END LOOP;
  
  ELSE
    SELECT TABLEID,NAME,DBTABLENAME INTO V_TABLEID,V_CNNAME,V_NAME FROM DICT_T_MODEL WHERE APPID = P_APPID AND DBTABLENAME = P_CREATED_OBJ_NAME;
    --DELETE FROM DICT_T_FACTOR WHERE TABLEID = V_TABLEID;
    
    --先保存已经存在的末级列ID
    SELECT COLUMNID,DBCOLUMNNAME BULK COLLECT INTO V_COLLIST FROM DICT_T_FACTOR WHERE TABLEID = V_TABLEID AND ISLEAF = '1';
    --删除
    DELETE FROM DICT_T_FACTOR WHERE TABLEID = V_TABLEID AND ISLEAF = '1' AND DBCOLUMNNAME NOT IN ('PROJNAME','PROJCODE','PROJTYPEID','SPFID','CKMX','XGGW','PROJ_GROUP_NAME') ;
    
    INSERT INTO DICT_T_FACTOR(ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,PARENTNODECANCHECK, XLSXCOLUMNID)
    SELECT ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID + 6 ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID,V_TABLEID TABLEID, VIRCONTEXT,PARENTNODECANCHECK, XLSXCOLUMNID
    FROM DICT_T_FACTOR
    WHERE TABLEID = P_SRC_TABLEID 
    AND (ISLEAF = '0' OR ISLEAF = '1' AND DBCOLUMNNAME NOT IN ('PROJNAME','PROJCODE','PROJTYPEID','SPFID','CKMX','XGGW','PROJ_GROUP_NAME'));
      
    --处理COLUMNID/SUPERID/BANDCOLUMNID
    FOR C_COL IN (SELECT TABLEID,COLUMNID,SUPERID,DBCOLUMNNAME,ISLEAF FROM DICT_T_FACTOR 
      WHERE TABLEID = V_TABLEID AND (ISLEAF = '0' OR ISLEAF = '1' AND DBCOLUMNNAME NOT IN ('PROJNAME','PROJCODE','PROJTYPEID','SPFID','CKMX','XGGW','PROJ_GROUP_NAME'))) LOOP
      V_COLUMNID := RAWTOHEX(SYS_GUID());
      V_FUND := FALSE;
      IF C_COL.ISLEAF = '1' THEN
        V_INDEX := V_COLLIST.FIRST;
        --处理缓存的列
        WHILE V_INDEX <= V_COLLIST.LAST LOOP
          IF V_COLLIST(V_INDEX).DBCOLUMNNAME = C_COL.DBCOLUMNNAME THEN
            V_FUND := TRUE;
            EXIT;
          END IF;
          V_INDEX := V_COLLIST.NEXT(V_INDEX);
        END LOOP;
      END IF;
      IF V_FUND THEN
        UPDATE DICT_T_FACTOR SET COLUMNID = V_COLLIST(V_INDEX).COLUMNID WHERE TABLEID = V_TABLEID AND COLUMNID = C_COL.COLUMNID;
        UPDATE DICT_T_FACTOR SET BANDCOLUMNID = V_COLLIST(V_INDEX).COLUMNID WHERE TABLEID = V_TABLEID AND BANDCOLUMNID =  C_COL.COLUMNID;
      ELSE
        UPDATE DICT_T_FACTOR SET COLUMNID = V_COLUMNID WHERE TABLEID = V_TABLEID AND COLUMNID = C_COL.COLUMNID;
        UPDATE DICT_T_FACTOR SET SUPERID = V_COLUMNID WHERE TABLEID = V_TABLEID AND SUPERID =  C_COL.COLUMNID;
        UPDATE DICT_T_FACTOR SET BANDCOLUMNID = V_COLUMNID WHERE TABLEID = V_TABLEID AND BANDCOLUMNID =  C_COL.COLUMNID;
      END IF;
    END LOOP;
    
  END IF;
  
  SELECT DBTABLENAME INTO V_SRC_TABLE FROM DICT_T_MODEL WHERE TABLEID = P_SRC_TABLEID;
  SELECT CONNSTRA('X.'||DBCOLUMNNAME||',') INTO V_TMP FROM DICT_T_FACTOR 
  WHERE TABLEID = V_TABLEID AND ISLEAF = '1' AND DBCOLUMNNAME NOT IN ('PROJNAME','PROJCODE','PROJTYPEID','SPFID','CKMX','XGGW','PROJ_GROUP_NAME');
  
  V_SQL := 'CREATE OR REPLACE VIEW '||V_NAME||' AS
SELECT '||V_TMP||'Y.PROJNAME,Y.PROJCODE,Y.PROJTYPEID ,Y.SPFID,CAST('''' AS VARCHAR2(255)) CKMX,CAST('''' AS VARCHAR2(255)) XGGW,CAST('''' AS VARCHAR2(255)) PROJ_GROUP_NAME
FROM '||V_SRC_TABLE||' X,SPF_T_PBASEINFO Y
WHERE X.PROJECTID = Y.PROJECTID
UNION ALL
SELECT '||V_TMP||'Y.SPFNAME,Y.SPFCODE,Y.PROJTYPEID ,Y.SPFID,CAST('''' AS VARCHAR2(255)) CKMX,CAST('''' AS VARCHAR2(255)) XGGW,CAST('''' AS VARCHAR2(255)) PROJ_GROUP_NAME
FROM '||V_SRC_TABLE||' X,SPF_T_FBASEINFO Y
WHERE X.PROJECTID = Y.SPFID';
  BEGIN
    EXECUTE IMMEDIATE V_SQL;
  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
  END;
END P_PROJ_COMBINED_VIEW;
--P_PROJ_COMBINED_VIEW加入SPFID
