CREATE OR REPLACE PROCEDURE P_KEEP_SPF_ACCOUNTS(P_WHERE VARCHAR2) IS
    V_TABLEID VARCHAR2(32);
    V_TABLE VARCHAR2(30);
    V_SQL VARCHAR2(32760);
    V_TMP VARCHAR2(4000);
    V_COLLIST VARCHAR2(4000);
    V_TEMPLIST VARCHAR2(4000);
    V_PROVINCE VARCHAR2(32);
    V_YEAR VARCHAR2(32);
    V_DBVERSION TIMESTAMP(6);
    V_LASTMODIFIED TIMESTAMP(6);
  BEGIN
    V_DBVERSION := SYSDATE;
    V_PROVINCE := GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID');
    V_YEAR := GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR');
    SELECT NVL((SELECT T.LAST_OPERATION_TIME  FROM  BGT_T_KEEPCOUNT_TIME T 
    WHERE T.PROVINCE = V_PROVINCE AND T.YEAR = V_YEAR  AND T.OPERATION_TYPE = 'P_KEEP_SPF_ACCOUNTS'),
    TO_TIMESTAMP('20120101','YYYYMMDD')) 
    INTO V_LASTMODIFIED FROM DUAL;
    
    SELECT TABLEID,DBTABLENAME INTO V_TABLEID,V_TABLE FROM DICT_T_MODEL WHERE DEALTYPE = '2101';
    V_TMP := ' ';
    V_TEMPLIST := '';
    FOR C_DATA IN (SELECT X.FUNDSOURCEID,CONNSTRA(Y.TOBASECOL||'*'||Y.VALUERATIO||'+') COL_EXP,
    CONNSTRA(','||Y.TOBASECOL||',') COL_LIST,
    'TMP$COL'||TRIM(TO_CHAR(ROW_NUMBER() OVER( ORDER BY X.FUNDSOURCEID))) EXP_ALIAS
    FROM BGT_V_PUBFUNDSOURCE X, EXP_S_PROJINVEST Y, DICT_T_FACTOR Z
    WHERE X.FUNDSOURCEID = Y.FUNDSOURCEID
     AND Y.TOBASECOL = Z.DBCOLUMNNAME
     AND Z.TABLEID = V_TABLEID
     AND Z.ISLEAF = '1'
    GROUP BY X.FUNDSOURCEID) LOOP
       V_TMP :=V_TMP||C_DATA.EXP_ALIAS||' AS '''||C_DATA.FUNDSOURCEID||''',';
       V_TEMPLIST := V_TEMPLIST||'('||TRIM(TRAILING '+' FROM C_DATA.COL_EXP)||') '||C_DATA.EXP_ALIAS||',';
    END LOOP;
    V_TEMPLIST := TRIM(TRAILING ',' FROM V_TEMPLIST);
    V_TMP := SUBSTR(V_TMP,1,LENGTH(V_TMP) - 1);
    SELECT CONNSTRA(COLUMN_NAME||',') INTO V_COLLIST FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'BGT_T_YSJZSJB' AND COLUMN_NAME NOT IN ('GUID','AMT','SFJZ','ISWRITEOFF');
    V_COLLIST := SUBSTR(V_COLLIST,1,LENGTH(V_COLLIST) - 1);
    V_TABLE:= '(SELECT STATUS,FINYEAR,DATAKEY,AGENCYID,PROJECTID,EXPECOID,DBVERSION,EXPFUNCID,SPFID,'||V_TEMPLIST||'
  FROM P#'||V_TABLE||' 
  WHERE SPFID IN (SELECT SPFID FROM SPF_T_FBASEINFO 
  WHERE DISTRICTID = (SELECT GUID FROM CODE_T_DISTRICT_SPF WHERE CODE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM(''DIVID'')))
  )' ;
    
    --先处理项目支出明细表中已经被删除数据
    
    --未记账未冲抵 SFJZ = '0' AND  ISWRITEOFF ='0'直接删除
    V_SQL := Q'{DELETE FROM BGT_T_YSJZSJB T1 WHERE SFJZ = '0' AND ISWRITEOFF ='0' AND DATAKEY IN (SELECT DATAKEY FROM }'||V_TABLE||Q'{ T2 WHERE STATUS <> '1' AND DBVERSION >= :1)}';
    BEGIN
      EXECUTE IMMEDIATE V_SQL USING V_LASTMODIFIED;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
    END;
    
    --未记账未冲抵 SFJZ = '0' AND  ISWRITEOFF ='1'不处理
    --未记账未冲抵 SFJZ = '1' AND  ISWRITEOFF ='1'不处理
    
    --未记账未冲抵 SFJZ = '1' AND  ISWRITEOFF ='0'生成一笔负的,状态为未记账SFJZ = '0',ISWRITEOFF ='1'
    V_SQL := 'INSERT INTO BGT_T_YSJZSJB('||V_COLLIST||',AMT,SFJZ,ISWRITEOFF)
    SELECT '||V_COLLIST||Q'{,0-AMT AMT,'0' SFJZ,'1' ISWRITEOFF
    FROM BGT_T_YSJZSJB WHERE SFJZ = '1' AND ISWRITEOFF ='0'
    AND DATAKEY IN (SELECT DATAKEY FROM }'||V_TABLE||Q'{ T2 WHERE STATUS <> '1' AND DBVERSION >= :1)}';
    BEGIN
      EXECUTE IMMEDIATE V_SQL USING V_LASTMODIFIED;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
    END;
    
    --SJZYZFXM为空的数据
    
    --处理已存在的数据
    
    --没有记账 SFJZ = '0' AND  ISWRITEOFF ='0' 的直接更新金额和其他核算要素，其他的不处理
    V_SQL := 'UPDATE BGT_T_YSJZSJB TA
    SET (TA.AMT,TA.EXPFUNCGUID,TA.FINYEAR,TA.PROGUID,TA.AGENCYGUID,TA.EXPECOGUID,TA.SAFUNDSGUID,TA.WH,TA.FININTORGGUID) 
    = (SELECT TB.AMT,TB.EXPFUNCID,TB.FINYEAR,TB.PROGUID,TB.AGENCYGUID,TB.EXPECOGUID,TB.SAFUNDSGUID,TB.WH,TB.FININTORGGUID FROM '||Q'{(
    SELECT Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID,Y.EXPFUNCID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,Y.DBVERSION
    ,(SELECT ZHUANH FROM BGT_T_YSLYWHB WHERE SUPERID = Y.DATAKEY AND YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) SAFUNDSGUID
,(SELECT LYWH FROM BGT_T_YSLYWHB WHERE SUPERID = Y.DATAKEY AND YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) WH
,NVL((SELECT DEPTID FROM SPF_V_FBASEINFO_A WHERE SPFID = Y.SPFID),
           (SELECT FININTORG FROM CODE_T_AGENCY_SPF WHERE GUID = Y.AGENCYID)) FININTORGGUID
    FROM (
    SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID, EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION,EXPFUNCID  FROM (
    SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID,EXPECOID,DBVERSION,EXPFUNCID,SPFID,}'||V_TEMPLIST||' FROM '||V_TABLE|| ' T1
    WHERE T1.STATUS = ''1'' AND T1.SJZYZFXM IS NULL AND T1.DBVERSION >= :1 AND PROJECTID = ''*'' AND SPFID IN (SELECT TASKID FROM SPF_T_OARELATION WHERE DOCID = '''||P_WHERE||''' AND TASKTYPE = ''0'') AND  NOT EXISTS(SELECT 1 FROM BGT_T_YSLYWHB WHERE SUPERID = T1.DATAKEY)
    ) TT
    UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||Q'{))) Y) TB
    WHERE (TA.DATAKEY = TB.DATAKEY AND TA.FUNDSOURCEGUID = TB.FUNDSOURCEGUID))
  WHERE TA.SFJZ = '0' AND TA.ISWRITEOFF = '0' AND EXISTS(SELECT 1 FROM }'||Q'{(SELECT Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID,'01687gDiFwDjc' AGENCYEXPGUID, '' EXPFUNCGUID,'01687E2hS1Edv' FUNDTYPEGUID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,Y.DBVERSION
   FROM (
   SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID, EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION  FROM (
   SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID,EXPECOID,DBVERSION,EXPFUNCID,SPFID,}'||V_TEMPLIST||' FROM '||V_TABLE|| ' T1
   WHERE T1.STATUS = ''1'' AND T1.SJZYZFXM IS NULL AND T1.DBVERSION >= :2 AND (EXPECOID IS NOT NULL AND EXPFUNCID IS NOT NULL) AND PROJECTID = ''*'' AND SPFID IN (SELECT TASKID FROM SPF_T_OARELATION WHERE DOCID = '''||P_WHERE||''' AND TASKTYPE = ''0'') AND  NOT EXISTS(SELECT 1 FROM BGT_T_YSLYWHB WHERE SUPERID = T1.DATAKEY)
   ) TT
   UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||'))) Y) TB
   WHERE (TA.DATAKEY = TB.DATAKEY AND TA.FUNDSOURCEGUID = TB.FUNDSOURCEGUID 
   AND TA.FINYEAR||''$''||TA.AGENCYGUID||''$''||TA.PROGUID||''$''||TA.EXPFUNCGUID||''$''||TA.EXPECOGUID||''#''||TO_CHAR(TA.AMT)
   <>  TB.FINYEAR||''$''||TB.AGENCYGUID||''$''||TB.PROGUID||''$''||TB.EXPFUNCID||''$''||TB.EXPECOGUID||''#''||TO_CHAR(TB.AMT)
   ))';
   BEGIN
      EXECUTE IMMEDIATE V_SQL USING V_LASTMODIFIED,V_LASTMODIFIED;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
    END;
    
    --未记账已冲抵 SFJZ = '0' AND ISWRITEOFF ='1' 不处理
    --已记账已冲抵 SFJZ = '1' AND ISWRITEOFF ='1' 不处理
    --记账SFJZ= '1' 且 是否冲抵ISWRITEOFF ='0',金额不等的数据复制一行金额为负数的行，两行数据 是否冲抵 ISWRITEOFF都变为'1'，再插入一行
    V_SQL := Q'{BEGIN
  FOR C_DATA IN (
  SELECT FINYEAR,PROGUID,AGENCYGUID,EXPECOGUID,EXPFUNCGUID,FUNDSOURCEGUID,AMT,SFJZ,ISWRITEOFF,DATAKEY FROM BGT_T_YSJZSJB TA WHERE TA.SFJZ = '1'  AND TA.ISWRITEOFF ='0'
  AND EXISTS (SELECT 1 FROM (SELECT Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID,'01687gDiFwDjc' AGENCYEXPGUID, EXPFUNCID EXPFUNCGUID,'01687E2hS1Edv' FUNDTYPEGUID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,Y.DBVERSION
     FROM (
     SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID, EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION,EXPFUNCID  FROM (
     SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID,EXPECOID,DBVERSION,EXPFUNCID,SPFID,}'||V_TEMPLIST||' FROM '||V_TABLE|| ' T1
     WHERE T1.STATUS = ''1'' AND T1.SJZYZFXM IS NULL AND T1.DBVERSION >= :1 AND (EXPECOID IS NOT NULL AND EXPFUNCID IS NOT NULL) AND PROJECTID = ''*'' AND SPFID IN (SELECT TASKID FROM SPF_T_OARELATION WHERE DOCID = '''||P_WHERE||''' AND TASKTYPE = ''0'') AND NOT EXISTS(SELECT 1 FROM BGT_T_YSLYWHB WHERE SUPERID = T1.DATAKEY)
     ) TT
     UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||'))) Y) TB
     WHERE (TA.DATAKEY = TB.DATAKEY AND TA.FUNDSOURCEGUID = TB.FUNDSOURCEGUID 
     AND TA.FINYEAR||''$''||TA.AGENCYGUID||''$''||TA.PROGUID||''$''||TA.EXPFUNCGUID||''$''||TA.EXPECOGUID||''#''||TO_CHAR(TA.AMT)
     <>  TB.FINYEAR||''$''||TB.AGENCYGUID||''$''||TB.PROGUID||''$''||TB.EXPFUNCGUID||''$''||TB.EXPECOGUID||''#''||TO_CHAR(TB.AMT)
   ))) LOOP

     INSERT INTO BGT_T_YSJZSJB('||V_COLLIST||',AMT,SFJZ,ISWRITEOFF)
     SELECT '||V_COLLIST||Q'{,0-AMT AMT,'0' SFJZ,'1' ISWRITEOFF
     FROM BGT_T_YSJZSJB
     WHERE DATAKEY = C_DATA.DATAKEY AND FUNDSOURCEGUID = C_DATA.FUNDSOURCEGUID AND SFJZ = '1' AND ISWRITEOFF = '0';

     UPDATE BGT_T_YSJZSJB SET ISWRITEOFF = '1'
     WHERE DATAKEY = C_DATA.DATAKEY AND FUNDSOURCEGUID = C_DATA.FUNDSOURCEGUID AND SFJZ = '1' AND ISWRITEOFF = '0'
     AND FINYEAR||''$''||AGENCYGUID||''$''||PROGUID||''$''||EXPFUNCGUID||''$''||EXPECOGUID||''#''||TO_CHAR(AMT)
     =C_DATA.FINYEAR||''$''||C_DATA.AGENCYGUID||''$''||C_DATA.PROGUID||''$''||C_DATA.EXPFUNCGUID||''$''||C_DATA.EXPECOGUID||''#''||TO_CHAR(C_DATA.AMT);

     INSERT INTO BGT_T_YSJZSJB(FINYEAR,AGENCYGUID,PROGUID,AGENCYEXPGUID,EXPFUNCGUID,FUNDTYPEGUID,EXPECOGUID,FUNDSOURCEGUID,AMT,DATAKEY,BGTTYPEGUID,SAFUNDSGUID,WH,FININTORGGUID)
  SELECT Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID,'01687gDiFwDjc' AGENCYEXPGUID, EXPFUNCGUID,'01687E2hS1Edv' FUNDTYPEGUID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,'01687wARQ1YgH' BGTTYPEGUID
  ,(SELECT ZHUANH FROM BGT_T_YSLYWHB WHERE SUPERID = Y.DATAKEY AND YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) SAFUNDSGUID
  ,(SELECT LYWH FROM BGT_T_YSLYWHB WHERE SUPERID = Y.DATAKEY AND YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) WH
  ,NVL((SELECT DEPTID FROM SPF_V_FBASEINFO_A WHERE SPFID = Y.SPFID),
           (SELECT FININTORG FROM CODE_T_AGENCY_SPF WHERE GUID = Y.AGENCYID)) FININTORGGUID
  FROM (
  SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID, EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION,EXPFUNCID EXPFUNCGUID,SPFID  FROM (
  SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID,EXPECOID,DBVERSION,EXPFUNCID,SPFID,}'||V_TEMPLIST||' FROM '||V_TABLE|| ' TA
  WHERE TA.STATUS = ''1'' AND TA.SJZYZFXM IS NULL AND TA.DATAKEY = C_DATA.DATAKEY AND TA.DBVERSION >= :2 AND (EXPECOID IS NOT NULL AND EXPFUNCID IS NOT NULL) AND PROJECTID = ''*'' AND SPFID IN (SELECT TASKID FROM SPF_T_OARELATION WHERE DOCID = '''||P_WHERE||''' AND TASKTYPE = ''0'') ) TT
   UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||'))) Y
   WHERE Y.FUNDSOURCEGUID = C_DATA.FUNDSOURCEGUID
   AND Y.FINYEAR||''$''||Y.AGENCYGUID||''$''||Y.PROGUID||''$''||Y.EXPFUNCGUID||''$''||Y.EXPECOGUID||''#''||TO_CHAR(Y.AMT)
   <>  C_DATA.FINYEAR||''$''||C_DATA.AGENCYGUID||''$''||C_DATA.PROGUID||''$''||C_DATA.EXPFUNCGUID||''$''||C_DATA.EXPECOGUID||''#''||TO_CHAR(C_DATA.AMT);
  END LOOP;
END;';
    BEGIN
      EXECUTE IMMEDIATE V_SQL USING V_LASTMODIFIED,V_LASTMODIFIED;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
    END;
    
    --不存在的数据插入
    V_SQL := Q'{INSERT INTO BGT_T_YSJZSJB(FINYEAR,AGENCYGUID,PROGUID,AGENCYEXPGUID,EXPFUNCGUID,FUNDTYPEGUID,EXPECOGUID,FUNDSOURCEGUID,AMT,DATAKEY,BGTTYPEGUID,SAFUNDSGUID,WH,FININTORGGUID)
SELECT Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID,'01687gDiFwDjc' AGENCYEXPGUID, EXPFUNCGUID,'01687E2hS1Edv' FUNDTYPEGUID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,'01687wARQ1YgH' BGTTYPEGUID
,(SELECT ZHUANH FROM BGT_T_YSLYWHB WHERE SUPERID = Y.DATAKEY AND YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) SAFUNDSGUID
,(SELECT LYWH FROM BGT_T_YSLYWHB WHERE SUPERID = Y.DATAKEY AND YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) WH
,NVL((SELECT DEPTID FROM SPF_V_FBASEINFO_A WHERE SPFID = Y.SPFID),
           (SELECT FININTORG FROM CODE_T_AGENCY_SPF WHERE GUID = Y.AGENCYID)) FININTORGGUID
FROM (
SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID, EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION,EXPFUNCID EXPFUNCGUID,SPFID  FROM (
SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID,EXPECOID,DBVERSION,EXPFUNCID,SPFID,}'||V_TEMPLIST||' FROM '||V_TABLE|| ' TA
WHERE TA.STATUS = ''1'' AND TA.SJZYZFXM IS NULL AND TA.DBVERSION >= :1 AND (EXPECOID IS NOT NULL AND EXPFUNCID IS NOT NULL) AND PROJECTID = ''*'' AND SPFID IN (SELECT TASKID FROM SPF_T_OARELATION WHERE DOCID = '''||P_WHERE||''' AND TASKTYPE = ''0'') ) TT
 UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||Q'{))) Y
 WHERE AMT <> 0 AND NOT EXISTS(SELECT 1 FROM BGT_T_YSJZSJB
 WHERE DATAKEY = Y.DATAKEY AND FUNDSOURCEGUID = Y.FUNDSOURCEGUID
 }';
    BEGIN
      EXECUTE IMMEDIATE V_SQL USING V_LASTMODIFIED;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
    END;
    
    --SJZYZFXM非空的数据
    --存在的数据更新
    V_SQL := 'UPDATE BGT_T_YSJZSJB TA
    SET (TA.SJZYZFXM,TA.AMT,TA.EXPFUNCGUID,TA.FINYEAR,TA.PROGUID,TA.AGENCYGUID,TA.EXPECOGUID,TA.SAFUNDSGUID,TA.WH,TA.FININTORGGUID) 
    = (SELECT TB.SJZYZFXM,TB.AMT,TB.EXPFUNCID,TB.FINYEAR,TB.PROGUID,TB.AGENCYGUID,TB.EXPECOGUID,TB.SAFUNDSGUID,TB.WH,TB.FININTORGGUID FROM '||Q'{(
    SELECT Y.SJZYZFXM,Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID,Y.EXPFUNCID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,Y.DBVERSION
    ,(SELECT ZHUANH FROM BGT_T_YSLYWHB WHERE SUPERID = Y.DATAKEY AND YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) SAFUNDSGUID
,(SELECT LYWH FROM BGT_T_YSLYWHB WHERE SUPERID = Y.DATAKEY AND YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) WH
,NVL((SELECT DEPTID FROM SPF_V_FBASEINFO_A WHERE SPFID = Y.SPFID),
           (SELECT FININTORG FROM CODE_T_AGENCY_SPF WHERE GUID = Y.AGENCYID)) FININTORGGUID
    FROM (
    SELECT SJZYZFXM,FINYEAR,DATAKEY,AGENCYID,PROJECTID, EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION,EXPFUNCID  FROM (
    SELECT SJZYZFXM,FINYEAR,DATAKEY,AGENCYID,PROJECTID,EXPECOID,DBVERSION,EXPFUNCID,SPFID,}'||V_TEMPLIST||' FROM '||V_TABLE|| ' T1
    WHERE T1.STATUS = ''1'' AND T1.SJZYZFXM IS NOT NULL AND T1.DBVERSION >= :1 AND PROJECTID = ''*'' AND SPFID IN (SELECT TASKID FROM SPF_T_OARELATION WHERE DOCID = '''||P_WHERE||''' AND TASKTYPE = ''0'') AND  NOT EXISTS(SELECT 1 FROM BGT_T_YSLYWHB WHERE SUPERID = T1.DATAKEY)
    ) TT
    UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||Q'{))) Y) TB
    WHERE (TA.DATAKEY = TB.DATAKEY AND TA.FUNDSOURCEGUID = TB.FUNDSOURCEGUID))
  WHERE TA.SFJZ = '0' AND TA.ISWRITEOFF = '0' AND TA.SJZYZFXM IS NOT NULL AND EXISTS(SELECT 1 FROM }'||Q'{(SELECT Y.SJZYZFXM,Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID,'01687gDiFwDjc' AGENCYEXPGUID, '' EXPFUNCGUID,'01687E2hS1Edv' FUNDTYPEGUID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,Y.DBVERSION
   FROM (
   SELECT SJZYZFXM,FINYEAR,DATAKEY,AGENCYID,PROJECTID, EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION  FROM (
   SELECT SJZYZFXM,FINYEAR,DATAKEY,AGENCYID,PROJECTID,EXPECOID,DBVERSION,EXPFUNCID,SPFID,}'||V_TEMPLIST||' FROM '||V_TABLE|| ' T1
   WHERE T1.STATUS = ''1'' AND T1.SJZYZFXM IS NOT NULL AND T1.DBVERSION >= :2 AND (EXPECOID IS NOT NULL AND EXPFUNCID IS NOT NULL) AND PROJECTID = ''*'' AND SPFID IN (SELECT TASKID FROM SPF_T_OARELATION WHERE DOCID = '''||P_WHERE||''' AND TASKTYPE = ''0'') AND  NOT EXISTS(SELECT 1 FROM BGT_T_YSLYWHB WHERE SUPERID = T1.DATAKEY)
   ) TT
   UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||'))) Y) TB
   WHERE (TA.DATAKEY = TB.DATAKEY AND TA.FUNDSOURCEGUID = TB.FUNDSOURCEGUID 
   AND TA.SJZYZFXM||''$''||TA.FINYEAR||''$''||TA.AGENCYGUID||''$''||TA.PROGUID||''$''||TA.EXPFUNCGUID||''$''||TA.EXPECOGUID||''#''||TO_CHAR(TA.AMT)
   <>  TB.SJZYZFXM||''$''||TB.FINYEAR||''$''||TB.AGENCYGUID||''$''||TB.PROGUID||''$''||TB.EXPFUNCID||''$''||TB.EXPECOGUID||''#''||TO_CHAR(TB.AMT)
   ))';
   BEGIN
      EXECUTE IMMEDIATE V_SQL USING V_LASTMODIFIED,V_LASTMODIFIED;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
    END;
    
    --未记账已冲抵 SFJZ = '0' AND ISWRITEOFF ='1' 不处理
    --已记账已冲抵 SFJZ = '1' AND ISWRITEOFF ='1' 不处理
    --记账SFJZ= '1' 且 是否冲抵ISWRITEOFF ='0',金额不等的数据复制一行金额为负数的行，两行数据 是否冲抵 ISWRITEOFF都变为'1'，再插入一行
    V_SQL := Q'{BEGIN
  FOR C_DATA IN (
  SELECT SJZYZFXM,FINYEAR,PROGUID,AGENCYGUID,EXPECOGUID,EXPFUNCGUID,FUNDSOURCEGUID,AMT,SFJZ,ISWRITEOFF,DATAKEY FROM BGT_T_YSJZSJB TA WHERE TA.SFJZ = '1'  AND TA.ISWRITEOFF ='0'
  AND EXISTS (SELECT 1 FROM (SELECT Y.SJZYZFXM,Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID,'01687gDiFwDjc' AGENCYEXPGUID, EXPFUNCID EXPFUNCGUID,'01687E2hS1Edv' FUNDTYPEGUID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,Y.DBVERSION
     FROM (
     SELECT SJZYZFXM,FINYEAR,DATAKEY,AGENCYID,PROJECTID, EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION,EXPFUNCID  FROM (
     SELECT SJZYZFXM,FINYEAR,DATAKEY,AGENCYID,PROJECTID,EXPECOID,DBVERSION,EXPFUNCID,SPFID,}'||V_TEMPLIST||' FROM '||V_TABLE|| ' T1
     WHERE T1.STATUS = ''1'' AND T1.SJZYZFXM IS NOT NULL AND T1.DBVERSION >= :1 AND (EXPECOID IS NOT NULL AND EXPFUNCID IS NOT NULL) AND PROJECTID = ''*'' AND SPFID IN (SELECT TASKID FROM SPF_T_OARELATION WHERE DOCID = '''||P_WHERE||''' AND TASKTYPE = ''0'') AND NOT EXISTS(SELECT 1 FROM BGT_T_YSLYWHB WHERE SUPERID = T1.DATAKEY)
     ) TT
     UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||'))) Y) TB
     WHERE (TA.DATAKEY = TB.DATAKEY AND TA.FUNDSOURCEGUID = TB.FUNDSOURCEGUID 
     AND TA.SJZYZFXM||''$''||TA.FINYEAR||''$''||TA.AGENCYGUID||''$''||TA.PROGUID||''$''||TA.EXPFUNCGUID||''$''||TA.EXPECOGUID||''#''||TO_CHAR(TA.AMT)
     <>  TB.SJZYZFXM||''$''||TB.FINYEAR||''$''||TB.AGENCYGUID||''$''||TB.PROGUID||''$''||TB.EXPFUNCGUID||''$''||TB.EXPECOGUID||''#''||TO_CHAR(TB.AMT)
   ))) LOOP

     INSERT INTO BGT_T_YSJZSJB('||V_COLLIST||',AMT,SFJZ,ISWRITEOFF)
     SELECT '||V_COLLIST||Q'{,0-AMT AMT,'0' SFJZ,'1' ISWRITEOFF
     FROM BGT_T_YSJZSJB
     WHERE DATAKEY = C_DATA.DATAKEY AND FUNDSOURCEGUID = C_DATA.FUNDSOURCEGUID AND SFJZ = '1' AND ISWRITEOFF = '0';

     UPDATE BGT_T_YSJZSJB SET ISWRITEOFF = '1'
     WHERE DATAKEY = C_DATA.DATAKEY AND FUNDSOURCEGUID = C_DATA.FUNDSOURCEGUID AND SFJZ = '1' AND ISWRITEOFF = '0'
     AND SJZYZFXM||''$''||FINYEAR||''$''||AGENCYGUID||''$''||PROGUID||''$''||EXPFUNCGUID||''$''||EXPECOGUID||''#''||TO_CHAR(AMT)
     =C_DATA.SJZYZFXM||''$''||C_DATA.FINYEAR||''$''||C_DATA.AGENCYGUID||''$''||C_DATA.PROGUID||''$''||C_DATA.EXPFUNCGUID||''$''||C_DATA.EXPECOGUID||''#''||TO_CHAR(C_DATA.AMT);

     INSERT INTO BGT_T_YSJZSJB(SJZYZFXM,FINYEAR,AGENCYGUID,PROGUID,AGENCYEXPGUID,EXPFUNCGUID,FUNDTYPEGUID,EXPECOGUID,FUNDSOURCEGUID,AMT,DATAKEY,BGTTYPEGUID,SAFUNDSGUID,WH,FININTORGGUID)
  SELECT Y.SJZYZFXM,Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID,'01687gDiFwDjc' AGENCYEXPGUID, EXPFUNCGUID,'01687E2hS1Edv' FUNDTYPEGUID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,'01687wARQ1YgH' BGTTYPEGUID
  ,(SELECT ZHUANH FROM BGT_T_YSLYWHB WHERE SUPERID = Y.DATAKEY AND YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) SAFUNDSGUID
  ,(SELECT LYWH FROM BGT_T_YSLYWHB WHERE SUPERID = Y.DATAKEY AND YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) WH
  ,NVL((SELECT DEPTID FROM SPF_V_FBASEINFO_A WHERE SPFID = Y.SPFID),
           (SELECT FININTORG FROM CODE_T_AGENCY_SPF WHERE GUID = Y.AGENCYID)) FININTORGGUID
  FROM (
  SELECT SJZYZFXM,FINYEAR,DATAKEY,AGENCYID,PROJECTID, EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION,EXPFUNCID EXPFUNCGUID,SPFID  FROM (
  SELECT SJZYZFXM,FINYEAR,DATAKEY,AGENCYID,PROJECTID,EXPECOID,DBVERSION,EXPFUNCID,SPFID,}'||V_TEMPLIST||' FROM '||V_TABLE|| ' TA
  WHERE TA.STATUS = ''1'' AND TA.SJZYZFXM IS NOT NULL AND TA.DATAKEY = C_DATA.DATAKEY AND TA.DBVERSION >= :2 AND (EXPECOID IS NOT NULL AND EXPFUNCID IS NOT NULL) AND PROJECTID = ''*'' AND SPFID IN (SELECT TASKID FROM SPF_T_OARELATION WHERE DOCID = '''||P_WHERE||''' AND TASKTYPE = ''0'') ) TT
   UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||'))) Y
   WHERE Y.FUNDSOURCEGUID = C_DATA.FUNDSOURCEGUID
   AND Y.SJZYZFXM||''$''||Y.FINYEAR||''$''||Y.AGENCYGUID||''$''||Y.PROGUID||''$''||Y.EXPFUNCGUID||''$''||Y.EXPECOGUID||''#''||TO_CHAR(Y.AMT)
   <>  C_DATA.SJZYZFXM||''$''||C_DATA.FINYEAR||''$''||C_DATA.AGENCYGUID||''$''||C_DATA.PROGUID||''$''||C_DATA.EXPFUNCGUID||''$''||C_DATA.EXPECOGUID||''#''||TO_CHAR(C_DATA.AMT);
  END LOOP;
END;';
    BEGIN
      EXECUTE IMMEDIATE V_SQL USING V_LASTMODIFIED,V_LASTMODIFIED;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
    END;

   --不存在的数据插入
    V_SQL := Q'{INSERT INTO BGT_T_YSJZSJB(SJZYZFXM,FINYEAR,AGENCYGUID,PROGUID,AGENCYEXPGUID,EXPFUNCGUID,FUNDTYPEGUID,EXPECOGUID,FUNDSOURCEGUID,AMT,DATAKEY,BGTTYPEGUID,SAFUNDSGUID,WH,FININTORGGUID)
SELECT Y.SJZYZFXM,Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID,'01687gDiFwDjc' AGENCYEXPGUID, EXPFUNCGUID,'01687E2hS1Edv' FUNDTYPEGUID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,'01687wARQ1YgH' BGTTYPEGUID
,(SELECT ZHUANH FROM BGT_T_YSLYWHB WHERE SUPERID = Y.DATAKEY AND YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) SAFUNDSGUID
,(SELECT LYWH FROM BGT_T_YSLYWHB WHERE SUPERID = Y.DATAKEY AND YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) WH
,NVL((SELECT DEPTID FROM SPF_V_FBASEINFO_A WHERE SPFID = Y.SPFID),
           (SELECT FININTORG FROM CODE_T_AGENCY_SPF WHERE GUID = Y.AGENCYID)) FININTORGGUID
FROM (
SELECT SJZYZFXM,FINYEAR,DATAKEY,AGENCYID,PROJECTID, EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION,EXPFUNCID EXPFUNCGUID,SPFID  FROM (
SELECT SJZYZFXM,FINYEAR,DATAKEY,AGENCYID,PROJECTID,EXPECOID,DBVERSION,EXPFUNCID,SPFID,}'||V_TEMPLIST||' FROM '||V_TABLE|| ' TA
WHERE TA.STATUS = ''1'' AND TA.SJZYZFXM IS NOT NULL AND TA.DBVERSION >= :1 AND (EXPECOID IS NOT NULL AND EXPFUNCID IS NOT NULL) AND PROJECTID = ''*'' AND SPFID IN (SELECT TASKID FROM SPF_T_OARELATION WHERE DOCID = '''||P_WHERE||''' AND TASKTYPE = ''0'') ) TT
 UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||Q'{))) Y
 WHERE AMT <> 0 AND NOT EXISTS(SELECT 1 FROM BGT_T_YSJZSJB
 WHERE DATAKEY = Y.DATAKEY AND FUNDSOURCEGUID = Y.FUNDSOURCEGUID
 }';
    BEGIN
      EXECUTE IMMEDIATE V_SQL USING V_LASTMODIFIED;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
    END;
    
    DELETE FROM BGT_T_KEEPCOUNT_TIME T 
    WHERE T.PROVINCE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID')
    AND T.YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR')
    AND T.OPERATION_TYPE = 'P_KEEP_SPF_ACCOUNTS';
    
    INSERT INTO BGT_T_KEEPCOUNT_TIME(PROVINCE,YEAR,OPERATION_TYPE,LAST_OPERATION_TIME)
    VALUES(V_PROVINCE,V_YEAR,'P_KEEP_SPF_ACCOUNTS',V_DBVERSION);
    
    RETURN;
  END P_KEEP_SPF_ACCOUNTS;
--曹锟记账
