DECLARE
  n_count integer;
BEGIN
  SELECT COUNT(*) INTO n_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#KPI_T_SETPROJKPI' AND COLUMN_NAME = 'ISRELEASE';
  IF n_count = 0 THEN
     EXECUTE IMMEDIATE 'alter table P#KPI_T_SETPROJKPI add isrelease char(1) default 0';
     EXECUTE IMMEDIATE'comment on column P#KPI_T_SETPROJKPI.isrelease is ''发布状态（0未发布，1发布）''';
  END IF;
  
  SELECT COUNT(*) INTO n_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#KPI_T_SETSPFKPI' AND COLUMN_NAME = 'ISRELEASE';
  IF n_count = 0 THEN
     EXECUTE IMMEDIATE 'alter table P#KPI_T_SETSPFKPI add isrelease char(1) default 0';
     EXECUTE IMMEDIATE'comment on column P#KPI_T_SETSPFKPI.isrelease is ''发布状态（0未发布，1发布）''';
  END IF;
  
  SELECT COUNT(*) INTO n_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#KPI_T_SETDEPKPI' AND COLUMN_NAME = 'ISRELEASE';
  IF n_count = 0 THEN
     EXECUTE IMMEDIATE 'alter table P#KPI_T_SETDEPKPI add isrelease char(1) default 0';
     EXECUTE IMMEDIATE'comment on column P#KPI_T_SETDEPKPI.isrelease is ''发布状态（0未发布，1发布）''';
  END IF;
  
  SELECT COUNT(*) INTO n_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#KPI_T_SETFNCKPI' AND COLUMN_NAME = 'ISRELEASE';
  IF n_count = 0 THEN
     EXECUTE IMMEDIATE 'alter table P#KPI_T_SETFNCKPI add isrelease char(1) default 0';
     EXECUTE IMMEDIATE'comment on column P#KPI_T_SETFNCKPI.isrelease is ''发布状态（0未发布，1发布）''';
  END IF;
  
  EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW KPI_T_SETPROJKPI AS
      SELECT
        STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID,
        SUPERGUID, KPINAME, INDITYPE, GETDATAFUNC, LEVELNO,
        ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION, STANDARD,
        ISINSERT, ISUPDATE, ISDELETE, KPIPROP, DBVERSION,ISIMPORT,
        FRMKPIID,ISRELEASE FROM P#KPI_T_SETPROJKPI
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID')
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
      
  EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW KPI_T_SETSPFKPI AS
      SELECT 
        STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID,
        SUPERGUID, KPINAME, INDITYPE, GETDATAFUNC, LEVELNO, 
        ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION, STANDARD, 
        ISINSERT, ISUPDATE, ISDELETE,  KPIPROP, DBVERSION, 
        FRMKPIID,ISIMPORT,ISRELEASE FROM P#KPI_T_SETSPFKPI 
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') 
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
      
      EXECUTE IMMEDIATE Q'{ CREATE OR REPLACE VIEW KPI_T_SETDEPKPI AS
      SELECT 
        STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID,
        SUPERGUID, KPINAME, INDITYPE, GETDATAFUNC, LEVELNO, 
        ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION, STANDARD, 
        ISINSERT, ISUPDATE, ISDELETE,  KPIPROP, DBVERSION, 
        FRMKPIID,ISIMPORT,ISRELEASE FROM P#KPI_T_SETDEPKPI 
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') 
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
      
     EXECUTE IMMEDIATE Q'{ CREATE OR REPLACE VIEW KPI_T_SETFNCKPI AS
SELECT 
        STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID,
        SUPERGUID, KPINAME, INDITYPE, GETDATAFUNC, LEVELNO, 
        ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION, STANDARD, 
        ISINSERT, ISUPDATE, ISDELETE,  KPIPROP, DBVERSION, 
        FRMKPIID,isimport,ISRELEASE FROM P#KPI_T_SETFNCKPI 
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') 
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
      
      EXECUTE IMMEDIATE 'update P#KPI_T_SETPROJKPI set ISRELEASE = ''1'' ';
      EXECUTE IMMEDIATE 'update P#KPI_T_SETSPFKPI set ISRELEASE = ''1'' ';
      EXECUTE IMMEDIATE 'update P#KPI_T_SETDEPKPI set ISRELEASE = ''1'' ';
      EXECUTE IMMEDIATE 'update P#KPI_T_SETFNCKPI set ISRELEASE = ''1'' ';
END;   
--GF_20170330_绩效指标库新增发布字段
--GF_20170330_绩效指标库新增发布字段
