declare
v_type varchar2(64);
v_isExists CHAR(1);
BEGIN
--1、创建纳入预算临时表
-- Drop table
 SELECT COUNT(1) INTO v_isExists FROM user_tables WHERE TABLE_NAME ='P#SPF_T_INBUDGETTEMP';
  IF v_isExists > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE P#SPF_T_INBUDGETTEMP';
  END IF;
   SELECT COUNT(1) INTO v_isExists FROM User_Views WHERE VIEW_NAME ='SPF_T_INBUDGETTEMP';
   IF v_isExists > 0 THEN
    EXECUTE IMMEDIATE 'DROP VIEW SPF_T_INBUDGETTEMP';
  END IF;
execute immediate Q'{create table SPF_T_INBUDGETTEMP
(
  DATAKEY      VARCHAR2(32) default SYS_GUID() not null,
  INVEST_DATAKEY    VARCHAR2(32) not null,
  INBUDGET_DATAKEY  VARCHAR2(32) not null,
  ZCMX_DATAKEY  VARCHAR2(32) not null,
  ISSELECT  CHAR(1) default '0' not null,
  year      CHAR(4) not null,
  province  VARCHAR2(9) not null,
  dbversion TIMESTAMP(6) default SYSDATE,
  status    CHAR(1) default 1 not null
)}';

execute immediate 'alter table SPF_T_INBUDGETTEMP add constraint PK_SPF_T_INBUDGETTEMP primary key (PROVINCE, YEAR, STATUS, DATAKEY)';
SYS_P_PARTITION_TABLE('SPF_T_INBUDGETTEMP');


--2、增加政府功能和经济科目
SELECT  COUNT(*) INTO V_ISEXISTS FROM USER_TABLES w WHERE w.TABLE_NAME ='P#EXP_T_PBUDGETTEMP';
IF(V_ISEXISTS = 1) THEN
  SELECT COUNT(*) INTO V_ISEXISTS FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#EXP_T_PBUDGETTEMP' AND COLUMN_NAME ='GOVEXPECOID';
  IF(V_ISEXISTS = 0) THEN
     EXECUTE IMMEDIATE 'ALTER TABLE P#EXP_T_PBUDGETTEMP ADD GOVEXPECOID VARCHAR2(32)';
  END IF;
  SELECT COUNT(*) INTO V_ISEXISTS FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#EXP_T_PBUDGETTEMP' AND COLUMN_NAME ='GOVEXPFUNCID';
  IF(V_ISEXISTS = 0) THEN
  EXECUTE IMMEDIATE 'ALTER TABLE P#EXP_T_PBUDGETTEMP ADD GOVEXPFUNCID VARCHAR2(32)';
  END IF;
END IF;

SELECT  COUNT(*) INTO V_ISEXISTS FROM USER_TABLES w WHERE w.TABLE_NAME ='P#SPF_T_PINVESTPLAN';
IF(V_ISEXISTS = 1) THEN
  SELECT COUNT(*) INTO V_ISEXISTS FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#SPF_T_PINVESTPLAN' AND COLUMN_NAME ='GOVEXPECOID'; 
  IF(V_ISEXISTS = 0) THEN 
  EXECUTE IMMEDIATE 'ALTER TABLE P#SPF_T_PINVESTPLAN ADD GOVEXPECOID VARCHAR2(32)';
  END IF;
  SELECT COUNT(*) INTO V_ISEXISTS FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#SPF_T_PINVESTPLAN' AND COLUMN_NAME ='GOVEXPFUNCID';
  IF(V_ISEXISTS = 0) THEN
  EXECUTE IMMEDIATE 'ALTER TABLE P#SPF_T_PINVESTPLAN ADD GOVEXPFUNCID VARCHAR2(32)';
  END IF;
END IF;
SELECT  COUNT(*) INTO V_ISEXISTS FROM USER_TABLES w WHERE w.TABLE_NAME ='P#SPF_T_PINVESTPLAN_BAK';
IF(V_ISEXISTS = 1) THEN
  SELECT COUNT(*) INTO V_ISEXISTS FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#SPF_T_PINVESTPLAN_BAK' AND COLUMN_NAME ='GOVEXPECOID'; 
  IF(V_ISEXISTS = 0) THEN 
  EXECUTE IMMEDIATE 'ALTER TABLE P#SPF_T_PINVESTPLAN_BAK ADD GOVEXPECOID VARCHAR2(32)';
  END IF;
  SELECT COUNT(*) INTO V_ISEXISTS FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#SPF_T_PINVESTPLAN_BAK' AND COLUMN_NAME ='GOVEXPFUNCID';
  IF(V_ISEXISTS = 0) THEN
  EXECUTE IMMEDIATE 'ALTER TABLE P#SPF_T_PINVESTPLAN_BAK ADD GOVEXPFUNCID VARCHAR2(32)';
  END IF;
END IF;

SELECT  COUNT(*) INTO V_ISEXISTS FROM USER_TABLES w WHERE w.TABLE_NAME ='P#BGT_T_ZCXMMXB';
IF(V_ISEXISTS = 1) THEN
  SELECT COUNT(*) INTO V_ISEXISTS FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#BGT_T_ZCXMMXB' AND COLUMN_NAME ='GOVEXPECOID';
  IF(V_ISEXISTS = 0) THEN
  EXECUTE IMMEDIATE 'ALTER TABLE P#BGT_T_ZCXMMXB ADD GOVEXPECOID VARCHAR2(32)';
  END IF;

  SELECT COUNT(*) INTO V_ISEXISTS FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#BGT_T_ZCXMMXB' AND COLUMN_NAME ='ISCS';
  IF(V_ISEXISTS = 0) THEN
  EXECUTE IMMEDIATE 'ALTER TABLE P#BGT_T_ZCXMMXB ADD ISCS CHAR  (1) DEFAULT ''0'' ';
  END IF;

  SELECT COUNT(*) INTO V_ISEXISTS FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#BGT_T_ZCXMMXB' AND COLUMN_NAME ='GOVEXPFUNCID';
  IF(V_ISEXISTS = 0) THEN
  EXECUTE IMMEDIATE 'ALTER TABLE P#BGT_T_ZCXMMXB ADD GOVEXPFUNCID VARCHAR2(32)';
  END IF;
END IF;

SELECT  COUNT(*) INTO V_ISEXISTS FROM USER_TABLES w WHERE w.TABLE_NAME ='P#BGT_T_ZCXMMXB_BAK';
IF(V_ISEXISTS = 1) THEN
  SELECT COUNT(*) INTO V_ISEXISTS FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#BGT_T_ZCXMMXB_BAK' AND COLUMN_NAME ='GOVEXPECOID';
  IF(V_ISEXISTS = 0) THEN
  EXECUTE IMMEDIATE 'ALTER TABLE P#BGT_T_ZCXMMXB_BAK ADD GOVEXPECOID VARCHAR2(32)';
  END IF;
  SELECT COUNT(*) INTO V_ISEXISTS FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#BGT_T_ZCXMMXB_BAK' AND COLUMN_NAME ='GOVEXPFUNCID';
  IF(V_ISEXISTS = 0) THEN
  EXECUTE IMMEDIATE 'ALTER TABLE P#BGT_T_ZCXMMXB_BAK ADD GOVEXPFUNCID VARCHAR2(32)';
  END IF;

  SELECT COUNT(*) INTO V_ISEXISTS FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#BGT_T_ZCXMMXB_BAK' AND COLUMN_NAME ='ISCS';
  IF(V_ISEXISTS = 0) THEN
  EXECUTE IMMEDIATE 'ALTER TABLE P#BGT_T_ZCXMMXB_BAK ADD ISCS CHAR (1) DEFAULT ''0'' ';
  END IF;
END IF;


DELETE FROM P#DICT_T_FACTOR WHERE COLUMNID IN('D5B684BA06F64D1AB0D17B5A14953503','90CAD635559E4E55857561EBE678B864');
DELETE FROM P#DICT_T_FACTOR WHERE COLUMNID IN('D5B684BA06F64D1AB0D17B5A14953506','90CAD635559E4E55857561EBE678B865');
DELETE FROM P#DICT_T_FACTOR WHERE COLUMNID IN('D5B684BA06F64D1AB0D17B5A14953507','90CAD635559E4E55857561EBE678B867','6F4D8F7654C54DF79E1E7CDCB117C957');
for v_row in (select * from pub_t_partition_divid t where t.year <> '*') loop 
insert into P#DICT_T_FACTOR (YEAR, PROVINCE,ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID,null, null, null, null, null, null, 'D5B684BA06F64D1AB0D17B5A14953503', null, 32, 3, 'GOVEXPECOID', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '政府经济分类', '1', 76, null, null, 0, '0', null, '1', '0', '1076B3D87C3841D08DCC658EEB6A7BE0', null, '0', null);
insert into P#DICT_T_FACTOR (YEAR, PROVINCE,ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID,null, null, null, null, null, null, '90CAD635559E4E55857561EBE678B864', null, 32, 3, 'GOVEXPFUNCID', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '政府功能分类', '1', 77, null, null, 0, '0', null, '1', '0', '1076B3D87C3841D08DCC658EEB6A7BE0', null, '0', null);

insert into P#DICT_T_FACTOR (YEAR, PROVINCE,ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID,null, null, null, null, null, null, 'D5B684BA06F64D1AB0D17B5A14953506', null, 32, 3, 'GOVEXPECOID', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '政府经济分类', '1', 76, null, null, 0, '0', null, '1', '0', '14C0C3214F27189EE050A8C0210507CA', null, '0', null);
insert into P#DICT_T_FACTOR (YEAR, PROVINCE,ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID,null, null, null, null, null, null, '90CAD635559E4E55857561EBE678B865', null, 32, 3, 'GOVEXPFUNCID', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '政府功能分类', '1', 77, null, null, 0, '0', null, '1', '0', '14C0C3214F27189EE050A8C0210507CA', null, '0', null);

insert into P#DICT_T_FACTOR (YEAR, PROVINCE,ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID,null, null, null, null, null, null, 'D5B684BA06F64D1AB0D17B5A14953507', null, 32, 3, 'GOVEXPECOID', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '政府经济分类', '1', 76, null, null, 0, '0', null, '1', '0', '1FFB71E8965441A1AB5617677A447AA4', null, '0', null);
insert into P#DICT_T_FACTOR (YEAR, PROVINCE,ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID,null, null, null, null, null, null, '90CAD635559E4E55857561EBE678B867', null, 32, 3, 'GOVEXPFUNCID', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '政府功能分类', '1', 77, null, null, 0, '0', null, '1', '0', '1FFB71E8965441A1AB5617677A447AA4', null, '0', null);
insert into P#DICT_T_FACTOR (YEAR, PROVINCE,ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
values (v_row.YEAR, v_row.DISTRICTID,null, null, null, null, null, null, '6F4D8F7654C54DF79E1E7CDCB117C957', null, 1, 3, 'ISCS', '''0''', null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '0', 1, '是否测算', '1', 78, null, null, 0, '0', null, '1', '0', '1FFB71E8965441A1AB5617677A447AA4', null, '0', null);
END LOOP;
sys_p_recreate_views('14C0C3214F27189EE050A8C0210507CA');
sys_p_recreate_views('1076B3D87C3841D08DCC658EEB6A7BE0');
sys_p_recreate_views('1FFB71E8965441A1AB5617677A447AA4');

END;
--纳入预算改造

