DECLARE v_exist number(8) := 0;
BEGIN
--- 添加指标类型及复制来源绩效指标ID字段
  -- 给项目绩效指标表添加指标类型字段 BEGIN
  SELECT COUNT(1) INTO v_exist FROM user_tab_columns WHERE COLUMN_NAME ='INDITYPE' AND TABLE_NAME = 'P#KPI_T_SETPROJKPI';

  IF v_exist=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE P#KPI_T_SETPROJKPI ADD INDITYPE CHAR(1) DEFAULT 0';
    EXECUTE IMMEDIATE 'ALTER TABLE P#KPI_T_SETPROJKPI ADD FRMKPIID VARCHAR(32)';        -- 用于标识来源KPI，用于批量复制时查询口径关系用
    EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW KPI_T_SETPROJKPI AS
      SELECT STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID, SUPERGUID, KPINAME, 
      INDITYPE, LEVELNO, ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION, STANDARD, ISINSERT, 
      KPIPROP, DBVERSION, FRMKPIID FROM P#KPI_T_SETPROJKPI 
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') 
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
  END IF;
  -- 给项目绩效指标表添加指标类型字段 END

  -- 给专项绩效指标表添加指标类型字段 BEGIN
  SELECT COUNT(1) INTO v_exist FROM user_tab_columns WHERE COLUMN_NAME ='INDITYPE' AND TABLE_NAME = 'P#KPI_T_SETSPFKPI';

  IF v_exist=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE P#KPI_T_SETSPFKPI ADD INDITYPE CHAR(1) DEFAULT 0';
    EXECUTE IMMEDIATE 'ALTER TABLE P#KPI_T_SETSPFKPI ADD FRMKPIID VARCHAR(32)';        -- 用于标识来源KPI，用于批量复制时查询口径关系用
    EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW KPI_T_SETSPFKPI AS
      SELECT STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID, SUPERGUID, KPINAME, 
      INDITYPE, LEVELNO, ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION, STANDARD, ISINSERT, 
      KPIPROP, DBVERSION, FRMKPIID FROM P#KPI_T_SETSPFKPI 
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') 
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
  END IF;
  -- 给专项绩效指标表添加指标类型字段 END


  -- 给部门绩效指标表添加指标类型字段 BEGIN
  SELECT COUNT(1) INTO v_exist FROM user_tab_columns WHERE COLUMN_NAME ='INDITYPE' AND TABLE_NAME = 'P#KPI_T_SETDEPKPI';

  IF v_exist=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE P#KPI_T_SETDEPKPI ADD INDITYPE CHAR(1) DEFAULT 0';
    EXECUTE IMMEDIATE 'ALTER TABLE P#KPI_T_SETDEPKPI ADD FRMKPIID VARCHAR(32)';        -- 用于标识来源KPI，用于批量复制时查询口径关系用
    EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW KPI_T_SETDEPKPI AS
      SELECT STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID, SUPERGUID, KPINAME, 
      INDITYPE, LEVELNO, ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION, STANDARD, ISINSERT, 
      KPIPROP, DBVERSION, FRMKPIID FROM P#KPI_T_SETDEPKPI 
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') 
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
  END IF;
  -- 给部门绩效指标表添加指标类型字段 END

  -- 给财政绩效指标表添加指标类型字段 BEGIN
  SELECT COUNT(1) INTO v_exist FROM user_tab_columns WHERE COLUMN_NAME ='INDITYPE' AND TABLE_NAME = 'P#KPI_T_SETFNCKPI';

  IF v_exist=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE P#KPI_T_SETFNCKPI ADD INDITYPE CHAR(1) DEFAULT 0';
    EXECUTE IMMEDIATE 'ALTER TABLE P#KPI_T_SETFNCKPI ADD FRMKPIID VARCHAR(32)';        -- 用于标识来源KPI，用于批量复制时查询口径关系用
    EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW KPI_T_SETFNCKPI AS
      SELECT STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID, SUPERGUID, KPINAME, 
      INDITYPE, LEVELNO, ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION, STANDARD, ISINSERT, 
      KPIPROP, DBVERSION, FRMKPIID FROM P#KPI_T_SETFNCKPI 
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') 
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
  END IF;
  -- 给财政绩效指标表添加指标类型字段 END





--- 添加取数函数字段
  -- 给项目绩效指标表添加取数函数字段 BEGIN
  SELECT COUNT(1) INTO v_exist FROM user_tab_columns WHERE COLUMN_NAME ='GETDATAFUNC' AND TABLE_NAME = 'P#KPI_T_SETPROJKPI';

  IF v_exist=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE P#KPI_T_SETPROJKPI ADD GETDATAFUNC VARCHAR(200) ';
    EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW KPI_T_SETPROJKPI AS
      SELECT STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID, SUPERGUID, KPINAME, 
      INDITYPE, GETDATAFUNC, LEVELNO, ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION, 
      STANDARD, ISINSERT, KPIPROP, DBVERSION, FRMKPIID FROM P#KPI_T_SETPROJKPI 
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') 
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
  END IF;
  -- 给项目绩效指标表添加取数函数字段 END

  -- 给专项绩效指标表添加取数函数字段 BEGIN
  SELECT COUNT(1) INTO v_exist FROM user_tab_columns WHERE COLUMN_NAME ='GETDATAFUNC' AND TABLE_NAME = 'P#KPI_T_SETSPFKPI';

  IF v_exist=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE P#KPI_T_SETSPFKPI ADD GETDATAFUNC VARCHAR(200) ';    
    EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW KPI_T_SETSPFKPI AS
      SELECT STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID, SUPERGUID, KPINAME, 
      INDITYPE, GETDATAFUNC, LEVELNO, ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION,
      STANDARD, ISINSERT, KPIPROP, DBVERSION, FRMKPIID FROM P#KPI_T_SETSPFKPI 
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') 
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
  END IF;
  -- 给专项绩效指标表添加取数函数字段 END

  -- 给部门绩效指标表添加取数函数字段 BEGIN
  SELECT COUNT(1) INTO v_exist FROM user_tab_columns WHERE COLUMN_NAME ='GETDATAFUNC' AND TABLE_NAME = 'P#KPI_T_SETDEPKPI';

  IF v_exist=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE P#KPI_T_SETDEPKPI ADD GETDATAFUNC VARCHAR(200) ';
    EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW KPI_T_SETDEPKPI AS
      SELECT STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID, SUPERGUID, KPINAME, 
      INDITYPE, GETDATAFUNC, LEVELNO, ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION, 
      STANDARD, ISINSERT, KPIPROP, DBVERSION, FRMKPIID FROM P#KPI_T_SETDEPKPI 
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') 
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
  END IF;
  -- 给部门绩效指标表添加取数函数字段 END

  -- 给财政绩效指标表添加取数函数字段 BEGIN
  SELECT COUNT(1) INTO v_exist FROM user_tab_columns WHERE COLUMN_NAME ='GETDATAFUNC' AND TABLE_NAME = 'P#KPI_T_SETFNCKPI';

  IF v_exist=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE P#KPI_T_SETFNCKPI ADD GETDATAFUNC VARCHAR(200) ';
    EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW KPI_T_SETFNCKPI AS
      SELECT STATUS, DATAKEY, NEEDUPDATE, ORDERID, FINYEAR, GUID, SUPERGUID, KPINAME, 
      INDITYPE, GETDATAFUNC, LEVELNO, ISLEAF, SCORE, REQUIREDCHILD, EXPLANATION, 
      STANDARD, ISINSERT, KPIPROP, DBVERSION, FRMKPIID FROM P#KPI_T_SETFNCKPI 
      WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') 
      AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
  END IF;
  -- 给财政绩效指标表添加取数函数字段 END
END;

--绩效_ZZK_160921_给所有指标表添加指标类型及取数函数字段
