DECLARE
begin
EXECUTE IMMEDIATE Q'/CREATE OR REPLACE VIEW SPF_V_SPFPMAINEJ AS
SELECT PM.SPFNAME,
       PM.CREATETIME,
       PM.FIRAGENCYID,
       PM.PROJTYPEID,
       PM.PROJECTID,
       PM.SPFID,
       PM.PROJNAME,
       PM.PROJGROUP_NAME,
       PM.PROJCODE,
       PM.AGENCYNAME,
       PM.EXPFUNCID,
       PM.CREATEUSER,
       PM.CHECKSTATUS,
       PM.ISBGT,
       PM.AGENCYID,
       PM.IMPORTANCE,
       PM.ISINSTEAD,
       PM.DISTRICTID,
       PM.DATAKEY,
       PM.SPF_DISTRICTID,
       PM.ISINDEX
  FROM SPF_V_PMAIN PM
     WHERE 1 = 1 AND (PROJTYPEID IN (SELECT PROJTYPEID
      FROM SPF_T_PROJECTTYPE  WHERE PROJTYPE in ('2', '9')))/';

end;-----SPF_V_SPFPMAINEJ
--SPF_V_SPFPMAINEJ
