DECLARE
v_isExists CHAR(1);
BEGIN
  SELECT  COUNT(*) INTO V_ISEXISTS FROM USER_TABLES w WHERE w.TABLE_NAME ='P#SPF_T_FBASEINFO';
IF(V_ISEXISTS = 1) THEN
  SELECT COUNT(*) INTO V_ISEXISTS FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#SPF_T_FBASEINFO' AND COLUMN_NAME ='CSMODE'; 
  IF(V_ISEXISTS = 0) THEN 
    EXECUTE IMMEDIATE 'ALTER TABLE P#SPF_T_FBASEINFO ADD CSMODE VARCHAR2(32)';
    DELETE FROM P#DICT_T_FACTOR WHERE COLUMNID ='66E0EB35396349DBB57B199BE74C4715';
    for v_row in (select * from pub_t_partition_divid t where t.year <> '*') loop 
     insert into P#DICT_T_FACTOR (YEAR, PROVINCE,ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
     values (v_row.YEAR, v_row.DISTRICTID,null, null, null, null, null, null, '66E0EB35396349DBB57B199BE74C4715', 'E1A35FB4D52A459399162F32298D74FF', 32, 6, 'CSMODE', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '测算模型', '1', 45, null, null, 0, '4', null, '1', '0', '94C0F208AB0E407E9800093043FA7692', null, '0', null);
    END LOOP;
  END IF;
END IF;
  SELECT  COUNT(*) INTO V_ISEXISTS FROM USER_TABLES w WHERE w.TABLE_NAME ='P#SPF_T_FBASEINFO_BAK';
IF(V_ISEXISTS = 1) THEN
  SELECT COUNT(*) INTO V_ISEXISTS FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#SPF_T_FBASEINFO_BAK' AND COLUMN_NAME ='CSMODE'; 
  IF(V_ISEXISTS = 0) THEN 
  EXECUTE IMMEDIATE 'ALTER TABLE P#SPF_T_FBASEINFO_BAK ADD CSMODE VARCHAR2(32)';
  END IF;
END IF;
sys_p_recreate_views('94C0F208AB0E407E9800093043FA7692');
   FOR v_relaRow IN (SELECT tableid, sys_guid() GUID FROM dict_t_model WHERE relatab ='94C0F208AB0E407E9800093043FA7692') LOOP
       DELETE FROM P#DICT_T_FACTOR WHERE TABLEID =v_relaRow.Tableid AND DBCOLUMNNAME = 'CSMODE';
      for v_row in (select * from pub_t_partition_divid t where t.year <> '*') loop 
          insert into P#DICT_T_FACTOR (YEAR, PROVINCE, ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
          values (v_row.YEAR, v_row.DISTRICTID, null, null, null, null, null, null, v_relaRow.Guid, 'E1A35FB4D52A459399162F32298D74FF', 32, 6, 'CSMODE', null, null, '0000000000000000000000000000000', '66E0EB35396349DBB57B199BE74C4715', '94C0F208AB0E407E9800093043FA7692', null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '测算模型', '1', 45, null, null, 0, '4', null, '1', '0', v_relaRow.Tableid, null, '0', null);
       END LOOP;
      sys_p_recreate_views(v_relaRow.Tableid);
   END LOOP;
END;

--专项表新增测算模型列
