BEGIN
EXECUTE IMMEDIATE Q'{alter table P#SPF_T_FNOTICEGUIDE modify (ATTACHID varchar2(32))}';
UPDATE P#DICT_T_FACTOR T1 SET T1.DATATYPE = '3'
WHERE T1.TABLEID =
       (SELECT T2.TABLEID
          FROM DICT_T_MODEL T2
         WHERE T2.DBTABLENAME = 'SPF_T_FNOTICEGUIDE');
END;
--修改SPF_T_FNOTICEGUIDE物理表和factor中attachid字段类型
