DECLARE
V_COUNT INT;
BEGIN
SELECT COUNT(*)
  into V_COUNT
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'P#SPF_T_PADJUSTSTATUS'
   AND COLUMN_NAME = 'BGTADJUSTSTATUS';
    IF V_COUNT = 0 
    THEN 
     EXECUTE IMMEDIATE Q'{ALTER TABLE P#SPF_T_PADJUSTSTATUS ADD BGTADJUSTSTATUS char(1)}'; 
EXECUTE IMMEDIATE Q'/CREATE OR REPLACE VIEW SPF_T_PADJUSTSTATUS AS
SELECT DATAKEY,NEEDUPDATE,ORDERID,FINYEAR,PROJECTID,ADJUSTSTATUS,BGTADJUSTSTATUS,PROJNAME,STATUS,DBVERSION
  FROM P#SPF_T_PADJUSTSTATUS
 WHERE PROVINCE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID')
       AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'/';
  END IF;
EXECUTE IMMEDIATE Q'/CREATE OR REPLACE VIEW SPF_T_SHOWPROJINFO AS
SELECT A.DATAKEY,
       AGENCY.NAME FIRAGENCYNAME,
       A.SPFID,
       F.SPFNAME SPFNAME,
       A.AGENCYID,
       F.FIRAGENCYID,
       AGENCY.NAME AGENCYNAME,
       A.PROJNAME PROJNAME,
       A.PROJNAME || '{' || A.PROJECTID || '}' PROJGROUP_NAME,
       F.DISTRICTID,
       DISTRICTSPF.NAME DISTRICTIDNAME,
       A.PROJECTID,
       A.DBVERSION,
       DISTRICTSPF.CODE DISTRICTCODE,
       STATUS.ADJUSTSTATUS,
       PB.ISBGT,
       PB.ISINDEX,
       F.PROJTYPEID,
       STATUS.BGTADJUSTSTATUS,
       NVL(PB.CHECKSTATUS, '0') CHECKSTATUS
  FROM P#SPF_T_PBASEINFO A
  INNER JOIN P#SPF_T_PBASESTATUS PB
    ON A.PROJECTID = PB.PROJECTID
  INNER JOIN P#SPF_T_FBASEINFO F
    ON A.SPFID = F.SPFID
  INNER JOIN CODE_T_FIRAGENCY AGENCY
    ON F.FIRAGENCYID = AGENCY.GUID
  INNER JOIN CODE_T_DISTRICT_SPF DISTRICTSPF
    ON DISTRICTSPF.GUID = F.DISTRICTID
  INNER JOIN P#SPF_T_PADJUSTSTATUS STATUS
     ON A.PROJECTID = STATUS.PROJECTID
 WHERE A.STATUS = '1'
   AND PB.CHECKSTATUS = '1'
   AND PB.STATUS ='1'
   AND F.STATUS = '1'
   AND PB.Year = GLOBAL_MULTYear_CZ.Secu_f_Global_Parm('YEAR')/';

   EXECUTE IMMEDIATE Q'/CREATE OR REPLACE VIEW SPF_T_SHOWSPFINFO AS
SELECT T.SPFNAME,
        T.PROJTYPEID,
        T.deptID,
        DEPTIDSPF.NAME DEPTNAME,
        T.FIRAGENCYID,
        DEPTSPF.NAME FIRAGENCYNAME,
        T.DISTRICTID,
        T.BEGINYEAR FINYEAR,
         1 NEEDUPDATE,
         1 ORDERID,
         T.datakey,
         T.SPFID,
         T.ISRELEASE,
         T.Fundmanage,
         T.Spfcode,
         DISTRICTSPF.CODE DISTRICTCODE,
         DISTRICTSPF.NAME DISTRICTIDNAME,
         T.Dbversion
      FROM P#SPF_T_FBASEINFO T
       INNER JOIN P#SPF_T_FBASESTATUS FB
    ON T.SPFID = FB.SPFID and FB.STATUS ='1'  and FB.setupStatus = '2'
        left JOIN CODE_T_DISTRICT_SPF DISTRICTSPF
    ON DISTRICTSPF.GUID = T.DISTRICTID
     left JOIN Code_t_Firagency DEPTSPF
    ON DEPTSPF.GUID = T.FIRAGENCYID
        left JOIN CODE_T_DEPT_SPF DEPTIDSPF
    ON DEPTIDSPF.GUID = T.Deptid
      where  t.status='1'
      AND FB.Year = GLOBAL_MULTYear_CZ.Secu_f_Global_Parm('YEAR')/';

end;
--为专项资金申报准备的专项查询视图登记
