DECLARE
begin
EXECUTE IMMEDIATE Q'/CREATE OR REPLACE VIEW SPF_T_SPFSENDPYJACT AS
SELECT ACT.BATCHID,
       (SELECT TITLE FROM BD_T_BATCH WHERE BATCHID = ACT.BATCHID) TITLE,
       ACT.BUSITYPEID,
       ACT.CREATEUSER,
       ACT.DATAKEY,
       ACT.OBJECTID,
       ACT.DISTRICTID,
       ACT.REMARK,
       ACT.SOURCEAGENCYID,
       ACT.SOURCEBATCHID,
       ACT.STEP,
       ACT.TARGETAGENCYID,
       ACT.WFDIRECTION,
       ACT.WFSTATUS,
       SPFYI.SPFID,
       SPFYI.PROJTYPEID,
       SPFYI.AGENCYID,
       SPFYI.SETUPSTATUS,
       (CASE
         WHEN (SPFYI.SETUPSTATUS = 0) THEN
          '未设立'
         WHEN (SPFYI.SETUPSTATUS = 1) THEN
          '已确认,未发布'
         ELSE
          '已设立'
       END) SETUPSTATUSNAME,
       1 NEEDUPDATE,
       1 ORDERID,
       (SELECT BUSITYPENAME
          FROM BD_T_BUSITYPE
         WHERE BUSITYPEID = ACT.BUSITYPEID) BUSITYPENAME,
       TO_CHAR(SYSDATE, 'YYYY') FINYEAR
  FROM SPF_T_CFLOW_ACT ACT, SPF_V_SPFFMAINYJ SPFYI
 WHERE SPFYI.SPFID = ACT.OBJECTID/';
 
end;--SPF_T_SPFSENDPYJACT
--SPF_T_SPFSENDPYJACT
