BEGIN
update P#SPF_T_CONDISET   
       set     SENTENCES= 'SPFID IN (SELECT spfid FROM SPF_T_FBASEINFO WHERE PROJTYPEID IN (SELECT PROJTYPEID FROM SPF_T_PROJECTTYPE where PROJTYPE = ''3'') ) AND FUNDMANAGE in(''2'',''3'') AND DISTRICTID = (SELECT t.DISTRICTID FROM CODE_T_AGENCY_SPF t WHERE t.GUID=''$UPAGENCYID$'')'
       where GUID='6E0C2681AF0F4450A2C1BF0918C2A5D0';
  
end;
--修改主列表dyg
