CREATE OR REPLACE PROCEDURE P_KEEP_SPF_ACCOUNTS(P_WHERE VARCHAR2) IS
    V_TABLEID VARCHAR2(32);
    V_TABLE VARCHAR2(3000);
    V_SQL VARCHAR2(32760);
    V_TMP VARCHAR2(4000);
    V_COLLIST VARCHAR2(4000);
    V_TEMPLIST VARCHAR2(4000);
    V_PROVINCE VARCHAR2(32);
    V_YEAR VARCHAR2(32);
    V_WHERE VARCHAR2(4000);
    V_DBVERSION TIMESTAMP(6);
  BEGIN
    V_DBVERSION := SYSDATE;
    V_WHERE := ' 1 = 1 AND ' || P_WHERE;
    V_PROVINCE := GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID');
    V_YEAR := GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR');

    SELECT TABLEID,DBTABLENAME INTO V_TABLEID,V_TABLE FROM DICT_T_MODEL WHERE DEALTYPE = '2101';

    V_TMP := ' ';
    V_TEMPLIST := '';
    FOR C_DATA IN (SELECT X.FUNDSOURCEID,CONNSTRA(Y.TOBASECOL||'*'||Y.VALUERATIO||'+') COL_EXP,
    CONNSTRA(','||Y.TOBASECOL||',') COL_LIST,
    'TMP$COL'||TRIM(TO_CHAR(ROW_NUMBER() OVER( ORDER BY X.FUNDSOURCEID))) EXP_ALIAS
    FROM BGT_V_PUBFUNDSOURCE X, EXP_S_PROJINVEST Y, DICT_T_FACTOR Z
    WHERE X.FUNDSOURCEID = Y.FUNDSOURCEID
     AND Y.TOBASECOL = Z.DBCOLUMNNAME
     AND Z.TABLEID = V_TABLEID
     AND Z.ISLEAF = '1'
    GROUP BY X.FUNDSOURCEID) LOOP
       V_TMP :=V_TMP||C_DATA.EXP_ALIAS||' AS '''||C_DATA.FUNDSOURCEID||''',';
       V_TEMPLIST := V_TEMPLIST||'('||TRIM(TRAILING '+' FROM C_DATA.COL_EXP)||') '||C_DATA.EXP_ALIAS||',';
    END LOOP;
    V_TEMPLIST := TRIM(TRAILING ',' FROM V_TEMPLIST);
    V_TMP := SUBSTR(V_TMP,1,LENGTH(V_TMP) - 1);
    SELECT CONNSTRA(COLUMN_NAME||',') INTO V_COLLIST FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'BGT_T_YSJZSJB' AND COLUMN_NAME NOT IN ('GUID','AMT','SFJZ','ISWRITEOFF');
    V_COLLIST := SUBSTR(V_COLLIST,1,LENGTH(V_COLLIST) - 1);

    V_TABLE:= '(SELECT STATUS,FINYEAR,DATAKEY,AGENCYID,SPFID AS PROJECTID,EXPECOID,DBVERSION,EXPFUNCID,SPFID,'||V_TEMPLIST||'
  FROM P#'||V_TABLE||'
  WHERE YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM(''YEAR'')  AND ISADJUST = ''0'' AND PROJECTID = ''*'' AND SPFID IN (SELECT SPFID FROM SPF_T_FBASEINFO
  WHERE DISTRICTID = (SELECT GUID FROM CODE_T_DISTRICT_SPF WHERE CODE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM(''DIVID'')))
  )' ;

    --先处理项目支出明细表中已经被删除数据
    --SFJZ 0表示未记账 1表示记账成功 2表示记账失败
    --未记账非冲抵 SFJZ IN ('0', '2') AND  ISWRITEOFF ='0'直接删除
    V_SQL := Q'{DELETE FROM BGT_T_YSJZSJB T1 WHERE SFJZ IN ('0', '2') AND ISWRITEOFF ='0' AND EXISTS (SELECT 1 FROM }'||V_TABLE||Q'{ T2 WHERE T2.STATUS = '2' AND T2.DATAKEY = T1.DATAKEY)}';
    BEGIN
      --DBMS_OUTPUT.PUT_LINE(V_SQL);
      EXECUTE IMMEDIATE V_SQL;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
    END;

    --未记账冲抵 SFJZ IN ('0', '2') AND  ISWRITEOFF ='1'不处理
    --已记账冲抵 SFJZ = '1' AND  ISWRITEOFF ='1'不处理

    --已记账冲抵 SFJZ = '1' AND  ISWRITEOFF ='0'生成一笔负的,状态为未记账SFJZ = '0',ISWRITEOFF ='1'，原来那一行ISWRITEOFF 变为'1'

    V_SQL := 'INSERT INTO BGT_T_YSJZSJB('||V_COLLIST||',AMT,SFJZ,ISWRITEOFF)
    SELECT '||V_COLLIST||Q'{,0-AMT AMT,'0' SFJZ,'1' ISWRITEOFF
    FROM BGT_T_YSJZSJB T1 WHERE SFJZ = '1' AND ISWRITEOFF ='0'
    AND EXISTS (SELECT DATAKEY FROM }'||V_TABLE||Q'{ T2 WHERE T2.STATUS = '2' AND T2.DATAKEY = T1.DATAKEY)}';
    BEGIN
      --DBMS_OUTPUT.PUT_LINE(V_SQL);
      EXECUTE IMMEDIATE V_SQL;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
    END;

    V_SQL := Q'{UPDATE BGT_T_YSJZSJB T1
    SET ISWRITEOFF = '1'
    WHERE SFJZ = '1' AND ISWRITEOFF ='0'
    AND EXISTS (SELECT DATAKEY FROM }'||V_TABLE||Q'{ T2 WHERE T2.STATUS = '2' AND T2.DATAKEY = T1.DATAKEY)}';
    BEGIN
      --DBMS_OUTPUT.PUT_LINE(V_SQL);
      EXECUTE IMMEDIATE V_SQL;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
    END;

    --处理已存在的数据

    --对于已经存在的数据，没有记账 SFJZ = '0' AND  ISWRITEOFF ='0' 的直接更新金额和其他核算要素，其他的不处理
    V_SQL := 'UPDATE BGT_T_YSJZSJB TA
    SET (TA.FINYEAR,TA.AGENCYGUID,TA.PROGUID,TA.EXPFUNCGUID,TA.FUNDTYPEGUID,TA.EXPECOGUID,TA.AMT,TA.SAFUNDSGUID,TA.WH,TA.FININTORGGUID,TA.LOCEXPSTRGUID)
     = (SELECT TB.FINYEAR,TB.AGENCYGUID,TB.PROGUID,TB.EXPFUNCGUID,TB.FUNDTYPEGUID,TB.EXPECOGUID,TB.AMT,TB.SAFUNDSGUID,TB.WH,TB.FININTORGGUID,TB.LOCEXPSTRGUID FROM '||Q'{(
    SELECT Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID, EXPFUNCGUID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,Y.DBVERSION,
    (SELECT (SELECT FUNDTYPEID FROM BGT_T_FUNCTYPE2FUNDTYPE WHERE FUNCTYPEID = FASP_V_PUBEXPFUNC.FUNCTYPE) FROM FASP_V_PUBEXPFUNC WHERE GUID = Y.EXPFUNCGUID) FUNDTYPEGUID,
(SELECT ZHUANH FROM BGT_T_YSLYWHB WHERE SUPERID = Y.DATAKEY AND YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) SAFUNDSGUID,
(SELECT LYWH FROM BGT_T_YSLYWHB WHERE SUPERID = Y.DATAKEY AND YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) WH,
NVL((SELECT FININTORG FROM CODE_T_AGENCY_SPF WHERE GUID = Y.AGENCYID),(SELECT DEPTID FROM SPF_T_FBASEINFO WHERE SPFID = Y.SPFID)) FININTORGGUID,
(SELECT
CASE WHEN SUBSTR(CODE,1,3) >= '201' AND SUBSTR(CODE,1,3) <= '229' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '01')
 WHEN SUBSTR(CODE,1,5) = '23001' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '020101')
 WHEN SUBSTR(CODE,1,5) = '23002' AND SUBSTR(CODE,1,7) <> '2300251' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '020102')
 WHEN SUBSTR(CODE,1,5) = '23003'  THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '020103')
 WHEN SUBSTR(CODE,1,5) = '23011'  THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '0202')
 WHEN SUBSTR(CODE,1,7) = '2300251' OR SUBSTR(CODE,1,7) = '2300402' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '0203')
 WHEN SUBSTR(CODE,1,5) = '23008' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '0204' )
ELSE ''
END
 FROM FASP_V_PUBEXPFUNC WHERE GUID = Y.EXPFUNCGUID) LOCEXPSTRGUID
    FROM (
    SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID, EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION,EXPFUNCGUID,SPFID FROM
    (
    SELECT * FROM (
   SELECT T1.*,NVL(EXPFUNCID,(SELECT EXPFUNCID FROM SPF_T_FBASEINFO WHERE SPF_T_FBASEINFO.SPFID = T1.PROJECTID)) EXPFUNCGUID  FROM }'||V_TABLE|| ' T1
   WHERE T1.STATUS = ''1'' AND '||V_WHERE||' AND NOT EXISTS(SELECT 1 FROM BGT_T_YSLYWHB WHERE SUPERID = T1.DATAKEY)
    ) WHERE (EXPECOID IS NOT NULL AND EXPFUNCGUID IS NOT NULL)) TT
    UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||Q'{))) Y) TB
    WHERE (TA.DATAKEY = TB.DATAKEY AND TA.FUNDSOURCEGUID = TB.FUNDSOURCEGUID))
  WHERE TA.SFJZ = '0' AND TA.ISWRITEOFF = '0' AND EXISTS(SELECT 1 FROM }'||Q'{(SELECT Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID, EXPFUNCGUID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,Y.DBVERSION
   FROM (
   SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID, EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION,EXPFUNCGUID,SPFID FROM
   (
   SELECT * FROM (
   SELECT T1.*,NVL(EXPFUNCID,(SELECT EXPFUNCID FROM SPF_T_FBASEINFO WHERE SPF_T_FBASEINFO.SPFID = T1.PROJECTID)) EXPFUNCGUID  FROM }'||V_TABLE|| ' T1
   WHERE T1.STATUS = ''1'' AND '||V_WHERE||' AND NOT EXISTS(SELECT 1 FROM BGT_T_YSLYWHB WHERE SUPERID = T1.DATAKEY)
   ) WHERE (EXPECOID IS NOT NULL AND EXPFUNCGUID IS NOT NULL)
   ) TT
   UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||'))) Y) TB
   WHERE (TA.DATAKEY = TB.DATAKEY AND TA.FUNDSOURCEGUID = TB.FUNDSOURCEGUID
   AND TA.FINYEAR||''$''||TA.AGENCYGUID||''$''||TA.PROGUID||''$''||TA.EXPFUNCGUID||''$''||TA.EXPECOGUID||''#''||TO_CHAR(TA.AMT)
   <>  TB.FINYEAR||''$''||TB.AGENCYGUID||''$''||TB.PROGUID||''$''||TB.EXPFUNCGUID||''$''||TB.EXPECOGUID||''#''||TO_CHAR(TB.AMT)
   ))';

   BEGIN
     --DBMS_OUTPUT.PUT_LINE(V_SQL);
      EXECUTE IMMEDIATE V_SQL;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
    END;

    --未记账已冲抵 SFJZ = '0' AND ISWRITEOFF ='1' 不处理
    --已记账已冲抵 SFJZ = '1' AND ISWRITEOFF ='1' 不处理

    --记账SFJZ= '1' 且 是否冲抵ISWRITEOFF ='0',金额不等的数据复制一行金额为负数的行，两行数据 是否冲抵 ISWRITEOFF都变为'1'，再插入一行

    V_SQL := Q'{BEGIN
  FOR C_DATA IN (
  SELECT FINYEAR,PROGUID,AGENCYGUID,EXPECOGUID,FUNDSOURCEGUID,SFJZ,ISWRITEOFF,DATAKEY,EXPFUNCGUID,AMT FROM BGT_T_YSJZSJB TA WHERE TA.SFJZ = '1'  AND TA.ISWRITEOFF ='0'
  AND EXISTS (SELECT 1 FROM (SELECT Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID,'01687gDiFwDjc' AGENCYEXPGUID, Y.EXPFUNCGUID EXPFUNCGUID,'01687E2hS1Edv' FUNDTYPEGUID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,Y.DBVERSION
     FROM (
     SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID, EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION,EXPFUNCGUID FROM
     (
     SELECT *  FROM (
     SELECT T1.*,NVL(EXPFUNCID,(SELECT EXPFUNCID FROM SPF_T_FBASEINFO WHERE SPF_T_FBASEINFO.SPFID = T1.PROJECTID)) EXPFUNCGUID FROM }'||V_TABLE|| ' T1
     WHERE T1.STATUS = ''1'' AND '||V_WHERE||' AND NOT EXISTS(SELECT 1 FROM BGT_T_YSLYWHB WHERE BGT_T_YSLYWHB.SUPERID = T1.DATAKEY)
     ) WHERE (EXPECOID IS NOT NULL AND EXPFUNCGUID IS NOT NULL)
     ) TT
     UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||'))) Y) TB
     WHERE (TA.DATAKEY = TB.DATAKEY AND TA.FUNDSOURCEGUID = TB.FUNDSOURCEGUID
     AND TA.FINYEAR||''$''||TA.AGENCYGUID||''$''||TA.PROGUID||''$''||TA.EXPFUNCGUID||''$''||TA.EXPECOGUID||''#''||TO_CHAR(TA.AMT)
     <>  TB.FINYEAR||''$''||TB.AGENCYGUID||''$''||TB.PROGUID||''$''||TB.EXPFUNCGUID||''$''||TB.EXPECOGUID||''#''||TO_CHAR(TB.AMT)
   ) )) LOOP

     INSERT INTO BGT_T_YSJZSJB('||V_COLLIST||',AMT,SFJZ,ISWRITEOFF)
     SELECT '||V_COLLIST||Q'{,0-AMT AMT,'0' SFJZ,'1' ISWRITEOFF
     FROM BGT_T_YSJZSJB
     WHERE DATAKEY = C_DATA.DATAKEY AND FUNDSOURCEGUID = C_DATA.FUNDSOURCEGUID AND SFJZ = '1' AND ISWRITEOFF = '0';

     UPDATE BGT_T_YSJZSJB SET ISWRITEOFF = '1'
     WHERE DATAKEY = C_DATA.DATAKEY AND FUNDSOURCEGUID = C_DATA.FUNDSOURCEGUID AND SFJZ = '1' AND ISWRITEOFF = '0'
     AND FINYEAR||'$'||AGENCYGUID||'$'||PROGUID||'$'||EXPFUNCGUID||'$'||EXPECOGUID||'#'||TO_CHAR(AMT)
     =C_DATA.FINYEAR||'$'||C_DATA.AGENCYGUID||'$'||C_DATA.PROGUID||'$'||C_DATA.EXPFUNCGUID||'$'||C_DATA.EXPECOGUID||'#'||TO_CHAR(C_DATA.AMT);

     INSERT INTO BGT_T_YSJZSJB(FINYEAR,AGENCYGUID,PROGUID,AGENCYEXPGUID,EXPFUNCGUID,FUNDTYPEGUID,EXPECOGUID,FUNDSOURCEGUID,AMT,DATAKEY,BGTTYPEGUID,SAFUNDSGUID,WH,FININTORGGUID,LOCEXPSTRGUID)
  SELECT Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID,'01687gDiFwDjc' AGENCYEXPGUID, Y.EXPFUNCGUID,(SELECT (SELECT FUNDTYPEID FROM BGT_T_FUNCTYPE2FUNDTYPE WHERE BGT_T_FUNCTYPE2FUNDTYPE.FUNCTYPEID = FASP_V_PUBEXPFUNC.FUNCTYPE) FROM FASP_V_PUBEXPFUNC WHERE FASP_V_PUBEXPFUNC.GUID = Y.EXPFUNCGUID) FUNDTYPEGUID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,'01687wARQ1YgH' BGTTYPEGUID
  ,(SELECT ZHUANH FROM BGT_T_YSLYWHB WHERE BGT_T_YSLYWHB.SUPERID = Y.DATAKEY AND BGT_T_YSLYWHB.YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) SAFUNDSGUID
  ,(SELECT LYWH FROM BGT_T_YSLYWHB WHERE BGT_T_YSLYWHB.SUPERID = Y.DATAKEY AND BGT_T_YSLYWHB.YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) WH
  ,NVL((SELECT FININTORG FROM CODE_T_AGENCY_SPF WHERE CODE_T_AGENCY_SPF.GUID = Y.AGENCYID),
(SELECT DEPTID FROM SPF_T_FBASEINFO WHERE SPF_T_FBASEINFO.SPFID = Y.SPFID)) FININTORGGUID,
  (SELECT
CASE WHEN SUBSTR(CODE,1,3) >= '201' AND SUBSTR(CODE,1,3) <= '229' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '01')
 WHEN SUBSTR(CODE,1,5) = '23001' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '020101')
 WHEN SUBSTR(CODE,1,5) = '23002' AND SUBSTR(CODE,1,7) <> '2300251' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '020102')
 WHEN SUBSTR(CODE,1,5) = '23003'  THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '020103')
 WHEN SUBSTR(CODE,1,5) = '23011'  THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '0202')
 WHEN SUBSTR(CODE,1,7) = '2300251' OR SUBSTR(CODE,1,7) = '2300402' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '0203')
 WHEN SUBSTR(CODE,1,5) = '23008' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '0204' )
ELSE ''
END
 FROM FASP_V_PUBEXPFUNC WHERE FASP_V_PUBEXPFUNC.GUID = Y.EXPFUNCGUID) LOCEXPSTRGUID
  FROM (
  SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID, EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION,EXPFUNCGUID,SPFID FROM
  (
  SELECT *  FROM (
  SELECT T1.*,NVL(EXPFUNCID,(SELECT EXPFUNCID FROM SPF_T_FBASEINFO WHERE SPF_T_FBASEINFO.SPFID = T1.PROJECTID)) EXPFUNCGUID FROM }'||V_TABLE|| ' T1
  WHERE T1.STATUS = ''1'' AND T1.DATAKEY = C_DATA.DATAKEY AND T1.EXPECOID IS NOT NULL AND '||V_WHERE||'
  ) WHERE EXPFUNCGUID IS NOT NULL) TT
   UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||'))) Y
   WHERE Y.FUNDSOURCEGUID = C_DATA.FUNDSOURCEGUID
   AND Y.FINYEAR||''$''||Y.AGENCYID||''$''||Y.PROJECTID||''$''||Y.EXPFUNCGUID||''$''||Y.EXPECOGUID||''#''||TO_CHAR(Y.AMT)
   <>  C_DATA.FINYEAR||''$''||C_DATA.AGENCYGUID||''$''||C_DATA.PROGUID||''$''||C_DATA.EXPFUNCGUID||''$''||C_DATA.EXPECOGUID||''#''||TO_CHAR(C_DATA.AMT);

  END LOOP;
END;';
    BEGIN
      --DBMS_OUTPUT.PUT_LINE(V_SQL);
      EXECUTE IMMEDIATE V_SQL;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
    END;

    --不存在的数据插入
    V_SQL := Q'{INSERT INTO BGT_T_YSJZSJB(FINYEAR,AGENCYGUID,PROGUID,AGENCYEXPGUID,EXPFUNCGUID,FUNDTYPEGUID,EXPECOGUID,FUNDSOURCEGUID,AMT,DATAKEY,BGTTYPEGUID,SAFUNDSGUID,WH,FININTORGGUID,LOCEXPSTRGUID)
SELECT Y.FINYEAR,Y.AGENCYID AGENCYGUID,Y.PROJECTID PROGUID,'01687gDiFwDjc' AGENCYEXPGUID, Y.EXPFUNCGUID,(SELECT (SELECT FUNDTYPEID FROM BGT_T_FUNCTYPE2FUNDTYPE WHERE BGT_T_FUNCTYPE2FUNDTYPE.FUNCTYPEID = FASP_V_PUBEXPFUNC.FUNCTYPE) FROM FASP_V_PUBEXPFUNC WHERE FASP_V_PUBEXPFUNC.GUID = Y.EXPFUNCGUID) FUNDTYPEGUID,Y.EXPECOGUID,Y.FUNDSOURCEGUID,Y.AMT,Y.DATAKEY,'01687wARQ1YgH' BGTTYPEGUID
,(SELECT ZHUANH FROM BGT_T_YSLYWHB WHERE BGT_T_YSLYWHB.SUPERID = Y.DATAKEY AND BGT_T_YSLYWHB.YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) SAFUNDSGUID
,(SELECT LYWH FROM BGT_T_YSLYWHB WHERE BGT_T_YSLYWHB.SUPERID = Y.DATAKEY AND BGT_T_YSLYWHB.YSLY = Y.FUNDSOURCEGUID AND ROWNUM < 2) WH
,NVL((SELECT FININTORG FROM CODE_T_AGENCY_SPF WHERE GUID = Y.AGENCYID),
(SELECT DEPTID FROM SPF_T_FBASEINFO WHERE SPF_T_FBASEINFO.SPFID = Y.SPFID)) FININTORGGUID,
  (SELECT
CASE WHEN SUBSTR(CODE,1,3) >= '201' AND SUBSTR(CODE,1,3) <= '229' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '01')
 WHEN SUBSTR(CODE,1,5) = '23001' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '020101')
 WHEN SUBSTR(CODE,1,5) = '23002' AND SUBSTR(CODE,1,7) <> '2300251' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '020102')
 WHEN SUBSTR(CODE,1,5) = '23003'  THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '020103')
 WHEN SUBSTR(CODE,1,5) = '23011'  THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '0202')
 WHEN SUBSTR(CODE,1,7) = '2300251' OR SUBSTR(CODE,1,7) = '2300402' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '0203')
 WHEN SUBSTR(CODE,1,5) = '23008' THEN (SELECT GUID FROM FASP_V_PUBLOCEXPSTR WHERE CODE = '0204' )
ELSE ''
END
 FROM FASP_V_PUBEXPFUNC WHERE FASP_V_PUBEXPFUNC.GUID = Y.EXPFUNCGUID) LOCEXPSTRGUID
FROM (
SELECT FINYEAR,DATAKEY,AGENCYID,PROJECTID,EXPECOID EXPECOGUID, FUNDSOURCEGUID, AMT,DBVERSION,EXPFUNCGUID,SPFID  FROM (
SELECT * FROM (
SELECT T1.*,NVL(EXPFUNCID,(SELECT EXPFUNCID FROM SPF_T_FBASEINFO WHERE SPF_T_FBASEINFO.SPFID = T1.PROJECTID)) EXPFUNCGUID FROM }'||V_TABLE|| ' T1
WHERE  T1.STATUS = ''1'' AND '||V_WHERE||'
) WHERE (EXPECOID IS NOT NULL AND EXPFUNCGUID IS NOT NULL) ) TT
 UNPIVOT(AMT FOR FUNDSOURCEGUID IN('||V_TMP||Q'{))) Y
 WHERE  AMT <> 0 AND NOT EXISTS(SELECT 1 FROM BGT_T_YSJZSJB
 WHERE BGT_T_YSJZSJB.DATAKEY = Y.DATAKEY AND BGT_T_YSJZSJB.FUNDSOURCEGUID = Y.FUNDSOURCEGUID)
 }';
    BEGIN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      EXECUTE IMMEDIATE V_SQL;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(V_SQL);
      RAISE;
    END;
RETURN;
END P_KEEP_SPF_ACCOUNTS;
--P_KEEP_SPF_ACCOUNTS
