
DECLARE
   V_COL INT; 
BEGIN
   SELECT COUNT(*) INTO V_COL   FROM USER_TABLES WHERE TABLE_NAME ='P#SPF_T_YJXMCZHDJEB';
   IF V_COL=0 THEN
     
   --创建一级项目核定金额表
      EXECUTE IMMEDIATE Q'{
      create table P#SPF_T_YJXMCZHDJEB
      (
        province   VARCHAR2(9) not null,
        year       CHAR(4) not null,
        status     CHAR(1) default '1' not null,
        agencyid           VARCHAR2(32) not null,
        dbversion  TIMESTAMP(6) default SYSDATE,
        datakey    VARCHAR2(32) default sys_guid() not null,
        orderid    NUMBER(9),
        finyear    VARCHAR2(4),
        needupdate VARCHAR2(4000),
        spfid      VARCHAR2(32),
        auditvalue NUMBER(24,6) default 0
      )}';
      EXECUTE IMMEDIATE Q'{
      -- Create/Recreate primary, unique and foreign key constraints 
      alter table P#SPF_T_YJXMCZHDJEB
        add constraint PK_P#SPF_T_YJXMCZHDJEB primary key (PROVINCE, YEAR, STATUS, DATAKEY,AGENCYID)
      }';
  	 sys_p_partition_table('P#SPF_T_YJXMCZHDJEB');
      EXECUTE IMMEDIATE Q'{
      CREATE OR REPLACE TRIGGER TR_P#SPF_T_YJXMCZHDJEB
      BEFORE INSERT OR UPDATE ON  P#SPF_T_YJXMCZHDJEB FOR EACH ROW 
      BEGIN 
      IF INSERTING THEN 
      :NEW.PROVINCE:=NVL(:NEW.PROVINCE,GLOBAL_MULTYEAR_CZ.V_PMDIVID); 
      :NEW.YEAR:=NVL(:NEW.YEAR,GLOBAL_MULTYEAR_CZ.V_PMYEAR); 
      :NEW.DBVERSION := CASE WHEN TO_CHAR(:NEW.DBVERSION, 'yyyy-mm-dd') = '2012-01-01' THEN TO_DATE('2012-01-01', 'yyyy-mm-dd') ELSE SYSDATE END; 
      END IF; 
      IF (TO_CHAR(:NEW.DBVERSION,'yyyy-mm-dd') ='2012-01-01' AND ((UPDATING AND UPDATING('DBVERSION')) or INSERTING ) ) THEN 
      RETURN ;
      END IF; 
      IF UPDATING THEN 
      :NEW.DBVERSION:=SYSDATE;
      END IF; 
      END TR_P#SPF_T_YJXMCZHDJEB;
      }';

      EXECUTE IMMEDIATE Q'{
        CREATE OR REPLACE VIEW SPF_T_YJXMCZHDJEB AS
        SELECT DATAKEY,ORDERID ,AGENCYID,FINYEAR,NEEDUPDATE,SPFID,AUDITVALUE, STATUS, DBVERSION FROM P#SPF_T_YJXMCZHDJEB  WHERE YEAR=global_multyear_cz.Secu_f_GLOBAL_PARM('YEAR')  AND  PROVINCE=global_multyear_cz.Secu_f_GLOBAL_PARM('DIVID') AND STATUS='1'
      }';
      DELETE FROM dict_t_dealtype WHERE appID = 'SPF' AND dealID = '3*07';
        INSERT INTO dict_t_dealtype(appID, dealID, dealName, orderid, needconfig)
        VALUES
        ('SPF', '3*07', '专项核定金额表', 13, '0');
      DELETE FROM dict_t_defaultcol WHERE GUID IN ('22ADCBCBF40616B4E050A8C021050F2A','22ADCBCBF40716B4E050A8C021050F2A','22ADCBCBF40816B4E050A8C021050F2A','22ADCBCBF40916B4E050A8C021050F2A',
      '22ADCBCBF40A16B4E050A8C021050F2A','22ADCBCBF40B16B4E050A8C021050F2A','F8EF9711CE51A0B4E040A8C0200314B5');

        insert into dict_t_defaultcol (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS, DEFAULTVALUE, ISLOGICKEY, DEID)
        values ('3*07', 5, '单位编号', 'AGENCYID', 3, 32, 0, 'F70AF199747A1EFAE040A8C020653B39', '0', '1', 'F8EF9711CE51A0B4E040A8C0200314B5', '1', null, '0', null);

        insert into dict_t_defaultcol (dealid, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS, DEFAULTVALUE, ISLOGICKEY, DEID)
        values ('3*07', 2, '行标志', 'DATAKEY', 3, 32, 0, null, '1', '1', '22ADCBCBF40616B4E050A8C021050F2A', '1', 'sys_guid()', '0', '080001');

        insert into dict_t_defaultcol (dealid, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS, DEFAULTVALUE, ISLOGICKEY, DEID)
        values ('3*07', 3, '排序标志', 'ORDERID ', 1, 9, 0, null, '0', '1', '22ADCBCBF40716B4E050A8C021050F2A', '1', null, '0', null);

        insert into dict_t_defaultcol (dealid, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS, DEFAULTVALUE, ISLOGICKEY, DEID)
        values ('3*07', 4, '财年', 'FINYEAR', 3, 4, 0, null, '0', '1', '22ADCBCBF40816B4E050A8C021050F2A', '1', null, '0', '10206');

        insert into dict_t_defaultcol (dealid, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS, DEFAULTVALUE, ISLOGICKEY, DEID)
        values ('3*07', 3, '刷新标志', 'NEEDUPDATE', 3, 4000, 0, null, '0', '1', '22ADCBCBF40916B4E050A8C021050F2A', '1', null, '0', null);

        insert into dict_t_defaultcol (dealid, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS, DEFAULTVALUE, ISLOGICKEY, DEID)
        values ('3*07', 6, '专项ID', 'SPFID', 3, 32, 0, null, '0', '1', '22ADCBCBF40A16B4E050A8C021050F2A', '1', NULL, '0', '');

        insert into dict_t_defaultcol (dealid, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS, DEFAULTVALUE, ISLOGICKEY, DEID)
        values ('3*07', 7, '财政核定金额', 'AUDITVALUE', 2, 24, 6, null, '0', '1', '22ADCBCBF40B16B4E050A8C021050F2A', '1', '0', '0', '');
       
        DELETE FROM dict_t_model where tableid ='22BD906C0C4F0C71E050A8C0210522C7';
        DELETE FROM dict_t_factor where tableid ='22BD906C0C4F0C71E050A8C0210522C7';  

	 insert into dict_t_model (APPID, BGTLVL, DBTABLENAME, DEALTYPE, EXTPROP, INPUTLVL, ISADD, ISMAN, ISPARTITION, ISRESERVED, ISSHOW, ISTASK, ISSUMTAB, MAINUPTAB, NAME, ORDERID, RELATAB, REMARK, SECUSQL, INITSQLTIME, SHORTTITLE, STATUS, SUITID, TABLEID, TABLETYPE, TABSWHERE, ISBAK)
        values ('SPF', '1', 'SPF_T_YJXMCZHDJEB',  '3*07', '0000000000000000000000000000000', '3', '0', '0', '1', '0', '1', '0', '0', null, '一级项目核定金额', 16, 'CC76165E85FA4D36AB8069DEE5796AB1', null, null,  '1', null, '1', 'F41F98CA4C3B4912A78DF20E437F79F2', '22BD906C0C4F0C71E050A8C0210522C7', '1', null, '0');

     insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
      values ('行标志', null, null, null, null, '行标志', '22BD906C0C500C71E050A8C0210522C7', null, 32, 3, 'DATAKEY', 'sys_guid()', '080001', null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '1', '0', '1', 1, '行标志', '1', 1, null, null, 0, null, null, '1', '0', '22BD906C0C4F0C71E050A8C0210522C7', null, '0', null);

      insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
      values ('排序标志', null, null, null, null, '排序标志', '22BD906C0C510C71E050A8C0210522C7', null, 9, 1, 'ORDERID', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '1', '0', '1', 1, '排序标志', '1', 2, null, null, 0, null, null, '1', '0', '22BD906C0C4F0C71E050A8C0210522C7', null, '0', null);

      insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
      values ('财年', null, null, null, null, '财年', '22BD906C0C520C71E050A8C0210522C7', null, 4, 3, 'FINYEAR', null, '10206', null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '1', '0', '1', 1, '财年', '1', 3, null, null, 0, null, null, '1', '0', '22BD906C0C4F0C71E050A8C0210522C7', null, '0', null);

      insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
      values ('刷新标志', null, null, null, null, '刷新标志', '22BD906C0C530C71E050A8C0210522C7', null, 4000, 3, 'NEEDUPDATE', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '1', '0', '1', 1, '刷新标志', '1', 5, null, null, 0, null, null, '1', '0', '22BD906C0C4F0C71E050A8C0210522C7', null, '0', null);

      insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
      values ('专项ID', null, null, null, null, '专项ID', '22BD906C0C540C71E050A8C0210522C7', null, 32, 3, 'SPFID', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '1', '0', '1', 1, '专项ID', '1', 6, null, null, 0, null, null, '1', '0', '22BD906C0C4F0C71E050A8C0210522C7', null, '0', null);

      insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
      values ('财政核定金额', null, null, null, null, '财政核定金额', '22BD906C0C550C71E050A8C0210522C7', null, 24, 3, 'AUDITVALUE', '0', null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '1', '0', '1', 1, '财政核定金额', '1', 7, null, null, 6, null, null, '1', '0', '22BD906C0C4F0C71E050A8C0210522C7', null, '0', null);

      insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
      values ('单位', null, null, '1', null, '单位', '22BD906C0C560C71E050A8C0210522C7', null, 32, 6, 'AGENCYID', null, '10401', '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '1', '1', '0', '0', '0', '1', '0', '0', 1, '单位', '0', 4, null, null, 0, '4', 0, '1', '0', '22BD906C0C4F0C71E050A8C0210522C7', null, '0', null);

    END IF;

END;
--创建一级项目核定金额表
