DECLARE
  a integer;
   V_BAKCOL INT;
BEGIN

  SELECT COUNT(*) INTO a FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'P#SPF_T_PBASEINFO' AND COLUMN_NAME = 'ISADD';
  IF a = 0 THEN
    EXECUTE IMMEDIATE Q'{ alter table P#spf_t_Pbaseinfo add ISADD CHAR(1) DEFAULT '0'}';
  END IF;
  delete from dict_t_factor t where t.TABLEID = (select tableid from dict_t_model where dbtablename = 'SPF_T_PBASEINFO') and DBCOLUMNNAME = 'ISADD';
  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID) 
values 
(null, null, null, null, null, null, '2829E50C44DC488FE050A8C021052043', null, 1, 3, 'ISADD', '''0''', null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '0', 1, '是否追加', '1', 44, null, null, 0, '0', null, '1', '0', '9FC09B974CCE4342BB190FA2A47D4B20', null, '0', null);
   SELECT COUNT(*) INTO V_BAKCOL  FROM User_Tables WHERE TABLE_NAME = UPPER('P#spf_t_Pbaseinfo_BAK');
   SELECT COUNT(*) INTO a   FROM COLS  WHERE TABLE_NAME = UPPER('P#spf_t_Pbaseinfo_BAK')    AND COLUMN_NAME = UPPER('ISADD');
   IF V_BAKCOL=1 AND a = 0 THEN
          EXECUTE IMMEDIATE Q'{ alter table P#spf_t_Pbaseinfo_BAK add ISADD CHAR(1) DEFAULT '0'}';
   END IF;
  sys_p_recreate_views('9FC09B974CCE4342BB190FA2A47D4B20');
END;
--项目基本表添加是否追加字段
