CREATE OR REPLACE PROCEDURE P_SPF_TRANSPOSE_ININDEX(P_SRC_TABLEID VARCHAR2,P_BILLDEFID VARCHAR2,P_TABLEID VARCHAR2) IS
    V_TABLE VARCHAR2(3000);
    V_SQL VARCHAR2(32760);
    V_VIEW_NAME VARCHAR2(30);
    V_CNNAME VARCHAR2(200);
    V_CNT NUMBER;
    V_EXISTS NUMBER;
    V_DEALTYPE VARCHAR2(16);
	  V_SUFIX VARCHAR2(30);
		V_COLLIST VARCHAR2(4000);
		V_POS NUMBER;
		V_CLOB CLOB;
		V_IDLIST VARCHAR2(32000);
  BEGIN

    --源表转置表
    --P_TABLEID源表转置ID
    SELECT DBTABLENAME,NAME,DEALTYPE INTO V_TABLE,V_CNNAME ,V_DEALTYPE FROM DICT_T_MODEL WHERE TABLEID = P_SRC_TABLEID;
    V_VIEW_NAME := V_TABLE||'_TP';
    V_CNNAME := V_CNNAME||'(指标记账转置)';
		
    IF V_DEALTYPE<>'5*02' THEN
       raise_application_error(-20001,'来源表dealtype不是项目资金计划表.tableid:'||P_SRC_TABLEID);
       return ;
    END IF;
		
		SELECT APPROVEDCOLS INTO V_CLOB FROM DICT_T_BILLDEF WHERE GUID = P_BILLDEFID;
		V_POS := NVL(DBMS_LOB.INSTR(V_CLOB,'"id":'),0);
		V_IDLIST := '';
		IF V_POS > 0 THEN
			V_IDLIST := TRIM(DBMS_LOB.SUBSTR(V_CLOB,4000,V_POS + 5));
			V_IDLIST := TRIM(LEADING '"'  FROM V_IDLIST);
			V_POS := INSTR(V_IDLIST,'"');
			IF V_POS > 0 THEN
				V_IDLIST := SUBSTR(V_IDLIST,1,V_POS - 1);
			END IF;
		END IF;


    SELECT COUNT(*) INTO V_EXISTS FROM DICT_T_MODEL WHERE TABLEID = P_TABLEID;
    IF V_EXISTS = 0 THEN
			SELECT MAX(SUBSTR(DBTABLENAME,-3)) INTO V_SUFIX FROM P#DICT_T_MODEL WHERE REGEXP_LIKE(DBTABLENAME,'^'||V_VIEW_NAME||'[0-9]{3}$');
		  V_SUFIX := NVL(TRIM(V_SUFIX),'000');
		  V_VIEW_NAME := V_VIEW_NAME||TRIM(TO_CHAR(TO_NUMBER(V_SUFIX) + 1,'000'));
			--生成DICT_T_MODEL
      INSERT INTO DICT_T_MODEL(APPID, BGTLVL, DBTABLENAME, DEALTYPE, EXTPROP, INPUTLVL, ISADD, ISMAN, ISPARTITION, ISRESERVED, ISSHOW, ISTASK, ISSUMTAB, MAINUPTAB, NAME, ORDERID, RELATAB, REMARK, SECUSQL, INITSQLTIME, SHORTTITLE, SUITID, TABLEID, TABLETYPE,ISBAK,ISALLDISTRICT)
      SELECT APPID, BGTLVL,V_VIEW_NAME DBTABLENAME,'', RPAD('0',100,'0') EXTPROP, INPUTLVL, ISADD, ISMAN, ISPARTITION,'0' ISRESERVED,'1' ISSHOW,'0' ISTASK, ISSUMTAB, MAINUPTAB, V_CNNAME NAME, ORDERID, RELATAB, REMARK, SECUSQL,'1' INITSQLTIME, SHORTTITLE, SUITID, P_TABLEID TABLEID, '2' TABLETYPE,'0' ISBAK,ISALLDISTRICT
      FROM DICT_T_MODEL
      WHERE TABLEID = P_SRC_TABLEID;
			
			--生成DICT_T_FACTOR
			V_CNT := 0;
			INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
			SELECT '项目ID', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 32, 3, 'PROJECTID',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '项目ID', '1', V_CNT + 1, NULL, NULL, 0, '0', NULL, '1', '0', P_TABLEID, NULL,  '0', NULL FROM DUAL
			WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='PROJECTID' );

			INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
			SELECT '经济科目', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 32, 3, 'EXPECOID',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '经济科目', '1', V_CNT + 2, NULL, NULL, 0, '0', NULL, '1', '0', P_TABLEID, NULL,  '0', NULL FROM DUAL
			WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='EXPECOID' );

			INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
			SELECT '年份', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 32, 3, 'FINYEAR',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '年份', '1', V_CNT + 3, NULL, NULL, 0, '0', NULL, '1', '0', P_TABLEID, NULL,  '0', NULL FROM DUAL
			WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='FINYEAR' );

			INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
			SELECT '区划ID', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 32, 3, 'DISTRICTID',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '区划ID', '1', V_CNT + 4, NULL, NULL, 0, '0', NULL, '1', '0', P_TABLEID, NULL,  '0', NULL FROM DUAL
			WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='DISTRICTID' );


			INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
			SELECT '处理类型', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 32, 3, 'DEALTYPE',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '处理类型', '1', V_CNT + 5, NULL, NULL, 0, '0', NULL, '1', '0', P_TABLEID, NULL,  '0', NULL FROM DUAL
			WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='DEALTYPE' );

			INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
			SELECT '项目名称', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 32, 3, 'PROJNAME',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '项目名称', '1', V_CNT + 6, NULL, NULL, 0, '0', NULL, '1', '0', P_TABLEID, NULL,  '0', NULL FROM DUAL
			WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='PROJNAME' );

			INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
			SELECT '项目编码', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 32, 3, 'PROJCODE',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '项目编码', '1', V_CNT + 7, NULL, NULL, 0, '0', NULL, '1', '0', P_TABLEID, NULL,  '0', NULL FROM DUAL
			WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='PROJCODE' );

			INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
			SELECT '单位ID', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 32, 3, 'AGENCYID',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '单位ID', '1', V_CNT + 8, NULL, NULL, 0, '0', NULL, '1', '0', P_TABLEID, NULL,  '0', NULL FROM DUAL
			WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='AGENCYID' );

			INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
			SELECT '功能科目', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 32, 3, 'EXPFUNCID',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '功能科目', '1', V_CNT + 9, NULL, NULL, 0, '0', NULL, '1', '0', P_TABLEID, NULL,  '0', NULL FROM DUAL
			WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='EXPFUNCID' );

			INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
			SELECT 'SPFID', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 32, 3, 'SPFID',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, 'SPFID', '1', V_CNT + 10, NULL, NULL, 0, '0', NULL, '1', '0', P_TABLEID, NULL,  '0', NULL FROM DUAL
			WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='SPFID' );

			INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
			SELECT '部门ID', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 32, 3, 'DEPTID',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '部门ID', '1', V_CNT + 11, NULL, NULL, 0, '0', NULL, '1', '0', P_TABLEID, NULL,  '0', NULL FROM DUAL
			WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='DEPTID' );

			INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
			SELECT '项目类别', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 32, 3, 'PROJTYPE',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '项目类别', '1', V_CNT + 12, NULL, NULL, 0, '0', NULL, '1', '0', P_TABLEID, NULL,  '0', NULL FROM DUAL
			WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='PROJTYPE' );

			INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
			SELECT '金额', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 24, 2, 'AMOUNT',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '金额', '1', V_CNT + 13, NULL, NULL, 6, '0', NULL, '1', '0', P_TABLEID, NULL,  '0', NULL FROM DUAL
			WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='AMOUNT' );

			--INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
			--  SELECT '数据类型', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 32, 3, 'DATATYPE',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '数据类型', '1', V_CNT + 1, NULL, NULL, 0, '0', NULL, '1', '0', P_TABLEID, NULL,  '0', NULL FROM DUAL
			--WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='DATATYPE' );
			   
			INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
			SELECT 'DATAKEY', null, null, null, null, null,  RAWTOHEX(SYS_GUID()), null, 32, 3, 'DATAKEY', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, 'DATAKEY', '1', V_CNT + 14, null, null, 0, '0', null, '1', '0', P_TABLEID, null, '0', NULL FROM DUAL
			WHERE NOT EXISTS(SELECT 1 FROM DICT_T_FACTOR  WHERE TABLEID=P_TABLEID AND DBCOLUMNNAME='DATAKEY' );
			
			V_CNT := V_CNT + 14;
			V_IDLIST := ','||V_IDLIST||',';
			V_COLLIST := '';
			FOR C_COL IN (SELECT TABLEID,COLUMNID,DBCOLUMNNAME FROM DICT_T_FACTOR WHERE INSTR(V_IDLIST,','||COLUMNID||',') > 0 AND ISLEAF = '1'
				AND DBCOLUMNNAME NOT IN ('PROJECTID','EXPECOID','FINYEAR','AMOUNT','PROJNAME','PROJCODE','AGENCYID','DEALTYPE','ISINDEX','DISTRICTID','EXPFUNCID','SPFID','DEPTID','PROJTYPE','STATUS','DBVERSION','DATAKEY')) LOOP
				V_CNT := V_CNT + 1;
				V_COLLIST := V_COLLIST||'I.'||C_COL.DBCOLUMNNAME||',';
				INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
				SELECT ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, RAWTOHEX(SYS_GUID()) COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, V_CNT ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, '0' SUPERID,P_TABLEID TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID
				FROM DICT_T_FACTOR WHERE TABLEID = C_COL.TABLEID AND COLUMNID = C_COL.COLUMNID;
			END LOOP;
     
		ELSE
			SELECT DBTABLENAME INTO V_SUFIX FROM DICT_T_MODEL WHERE TABLEID = P_TABLEID;
      IF NOT REGEXP_LIKE(V_SUFIX,'^'||V_VIEW_NAME||'[0-9]{3}$') THEN
        SELECT MAX(SUBSTR(DBTABLENAME,-3)) INTO V_SUFIX FROM P#DICT_T_MODEL WHERE REGEXP_LIKE(DBTABLENAME,'^'||V_VIEW_NAME||'[0-9]{3}$')
        AND (PROVINCE,YEAR) NOT IN (SELECT GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') PROVINCE,GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') YEAR FROM DUAL)
        AND STATUS = '1';
        V_SUFIX := NVL(TRIM(V_SUFIX),'000');
        V_VIEW_NAME := V_VIEW_NAME||TRIM(TO_CHAR(TO_NUMBER(V_SUFIX) + 1,'000'));
        UPDATE DICT_T_MODEL SET DBTABLENAME = V_VIEW_NAME WHERE TABLEID = P_TABLEID;
      ELSE
        V_VIEW_NAME := V_SUFIX;
      END IF;
			
			--删掉在设置信息中去掉的列
			V_IDLIST := ','||V_IDLIST||',';
			DELETE FROM DICT_T_FACTOR WHERE TABLEID = P_TABLEID AND DBCOLUMNNAME NOT IN (
			SELECT DBCOLUMNNAME FROM DICT_T_FACTOR WHERE INSTR(V_IDLIST,','||COLUMNID||',') > 0  AND ISLEAF = '1'
			UNION
			SELECT DBCOLUMNNAME FROM DICT_T_FACTOR WHERE TABLEID = P_TABLEID AND ISLEAF = '1' AND DBCOLUMNNAME IN ('PROJECTID','EXPECOID','FINYEAR','AMOUNT','PROJNAME','PROJCODE','AGENCYID','DEALTYPE','ISINDEX','DISTRICTID','EXPFUNCID','SPFID','DEPTID','PROJTYPE','STATUS','DBVERSION','DATAKEY'));
			
			--增加设置信息中增加的列
			SELECT MAX(ORDERID) INTO V_CNT FROM DICT_T_FACTOR WHERE TABLEID = P_TABLEID;
			FOR C_COL IN (SELECT TABLEID,COLUMNID,DBCOLUMNNAME FROM DICT_T_FACTOR WHERE  TABLEID = P_TABLEID 
				AND INSTR(V_IDLIST,','||COLUMNID||',') > 0  AND ISLEAF = '1'
				AND DBCOLUMNNAME NOT IN (SELECT DBCOLUMNNAME FROM DICT_T_FACTOR WHERE TABLEID = P_TABLEID AND ISLEAF = '1')) LOOP
				V_CNT := V_CNT + 1;
				INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
				SELECT ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, RAWTOHEX(SYS_GUID()) COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, V_CNT ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, '0' SUPERID,P_TABLEID TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID
				FROM DICT_T_FACTOR WHERE TABLEID = C_COL.TABLEID AND COLUMNID = C_COL.COLUMNID;
			END LOOP;
        
			V_CNT := 14;
			V_COLLIST := '';
			FOR C_COL IN (SELECT TABLEID,COLUMNID,DBCOLUMNNAME FROM DICT_T_FACTOR WHERE TABLEID = P_TABLEID AND ISLEAF = '1' AND DBCOLUMNNAME NOT IN ('PROJECTID','EXPECOID','FINYEAR','AMOUNT','PROJNAME','PROJCODE','AGENCYID','DEALTYPE','ISINDEX','DISTRICTID','EXPFUNCID','SPFID','DEPTID','PROJTYPE','STATUS','DBVERSION','DATAKEY')
				ORDER BY ORDERID) LOOP
				V_COLLIST := V_COLLIST||'I.'||C_COL.DBCOLUMNNAME||',';
				V_CNT := V_CNT + 1;
				UPDATE DICT_T_FACTOR SET ORDERID = V_CNT WHERE TABLEID = C_COL.TABLEID AND COLUMNID = C_COL.COLUMNID;
			END LOOP;
    END IF;

    V_SQL :=  'CREATE OR REPLACE VIEW '||V_VIEW_NAME||' AS '||Q'{
    select * from (
        select i.PROJECTID,
               i.EXPECOID,
               i.FINYEAR,
               i.ADDINDEXNUM AMOUNT,
               p.PROJNAME,
               p.PROJCODE,
               (case when 
                      a.DISTRICTID=f.DISTRICTID  and a.divtype='0'  then p.AGENCYID
                    when
                      a.DISTRICTID=f.DISTRICTID  and (a.divtype = '3' or a.divtype = '4')  then f.FIRAGENCYID
                    when 
                      a.DISTRICTID<>f.DISTRICTID then a.DISTRICTID
                end) AGENCYID,   
                (case when 
                      a.DISTRICTID=f.DISTRICTID  and a.divtype='0' then '1'
                    when
                      a.DISTRICTID=f.DISTRICTID  and (a.divtype = '3' or a.divtype = '4') then '2'
                    when 
                      a.DISTRICTID<>f.DISTRICTID then '3'
                end) DEALTYPE,             
               PB.ISINDEX,
               f.DISTRICTID,
               i.EXPFUNCID,
               f.SPFID,
               f.DEPTID,
               pt.PROJTYPE,
               i.STATUS,
               i.DBVERSION,
							 }'||V_COLLIST||Q'{
               i.datakey
          from p#Spf_t_Pinvestplan i,
               spf_t_pbaseinfo   p,
               spf_t_fbaseinfo   f,
               SPF_T_PROJECTTYPE pt,
               code_t_agency_spf a,
               SPF_T_PBASESTATUS PB
         where i.ISPLANVALID = '1'
           and p.PROJECTID=PB.PROJECTID
           and i.PROJECTID = p.PROJECTID
           and p.SPFID = f.SPFID
           and f.PROJTYPEID = pt.PROJTYPEID
           and PB.ISINDEX='1'
           and p.AGENCYID=a.GUID )

 }';
 /*
   dbms_output.put_line(v_sql);
 */
BEGIN
    EXECUTE IMMEDIATE V_SQL;

exception
  when others then
     rollback;
		 dbms_output.put_line(v_sql);
     raise_application_error(-20001,'执行存储过程失败,原因是:'||sqlerrm);
END;
END P_SPF_TRANSPOSE_ININDEX;
--P_SPF_TRANSPOSE_ININDEX
