CREATE OR REPLACE VIEW SPF_V_FBASEINFO AS
SELECT
       A.SPFID,
       A.SPFNAME  SPFNAME,
       A.SPFCODE,
       A.AGENCYID,
       A.PROJTYPEID,
       A.FIRAGENCYID,
       A.DEPTID,
       A.DISTRICTID,
       A.ISRELEASE,
       A.APPROVALTYPE,
       A.ISGROVPROC,
       A.FUNDLEVEL,
       a.DATAKEY,
       a.ISTEMP
  FROM SPF_V_FMAIN A
--DF_SPF_V_FBASEINFO
