BEGIN
  --添加表处理类型
  DELETE FROM DICT_T_DEALTYPE WHERE DEALID IN ('A6','A7');
  
  --新增表处理类型
  INSERT INTO DICT_T_DEALTYPE (APPID, DEALID, DEALNAME, ORDERID, NEEDCONFIG, ISUNIQUE)
  VALUES ('SPF', 'A6', '专项一级项目控制数', 86, '0', '0');

  INSERT INTO DICT_T_DEALTYPE (APPID, DEALID, DEALNAME, ORDERID, NEEDCONFIG, ISUNIQUE)
  VALUES ('SPF', 'A7', '项目二级项目控制数', 87, '0', '0');
  
  --删除表处理类型默认值
  DELETE FROM DICT_T_DEFAULTCOL WHERE DEALID in( 'A6','A7');
  
  --新增表处理类型默认值
  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A6', 1, '行标志', 'DATAKEY', 3, 32, null, null, '1', '1', '50F1BD151F6E7BB4E0533906A8C059A5', '1', 'sys_guid()', null, '080001', '0', '0');

  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A6', 2, '专项唯一标识', 'SPFID', 3, 32, null, null, '0', '1', '50F1BD151F6F7BB4E0533906A8C059A5', '1', null, null, null, '0', '0');

  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A6', 3, '预算单位', 'AGENCYID', 3, 32, null, null, '0', '1', '50F1BD151F707BB4E0533906A8C059A5', '2', null, null, '10401', '0', '0');

  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A6', 3, '排序序号', 'ORDERID', 1, 9, null, null, '0', '1', '50F5F5FC0C4F1412E0533906A8C0E65A', '2', null, null, null, '0', '0');

  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A6', 3, '财年', 'FINYEAR', 3, 4, null, null, '0', '1', '50F5F5FC0C501412E0533906A8C0E65A', '1', null, null, null, '0', '0');

  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A6', 4, '预算单位', 'AGENCYID', 3, 32, null, null, '0', '1', '50F5F5FC0C511412E0533906A8C0E65A', '1', null, null, null, '0', '0');

  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A6', 5, '财政处室ID', 'FINANCE_ID', 3, 32, null, null, '0', '1', '50F5F5FC0C521412E0533906A8C0E65A', '1', null, null, null, '0', '0');

  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A6', 6, '部门ID', 'DEPT_ID', 3, 32, null, null, '0', '1', '50F5F5FC0C531412E0533906A8C0E65A', '1', null, null, null, '0', '0');

  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A7', 1, '行标志', 'DATAKEY', 3, 32, null, null, '1', '1', '50F1BD151F717BB4E0533906A8C059A5', '1', 'sys_guid()', null, '080001', '0', '0');

  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A7', 2, '项目唯一标识', 'PROJECTID', 3, 32, null, null, '0', '1', '50F1BD151F727BB4E0533906A8C059A5', '1', null, '0', null, '0', '0');

  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A7', 3, '财年', 'FINYEAR', 3, 4, null, null, '0', '1', '512D05E520796EC8E0533906A8C03245', '1', null, null, null, '0', '0');

  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A7', 4, '预算单位', 'AGENCYID', 3, 32, null, null, '0', '1', '512D05E5207A6EC8E0533906A8C03245', '1', null, null, null, '0', '0');

  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A7', 5, '财政处室ID', 'FINANCE_ID', 3, 32, null, null, '0', '1', '512D05E5207B6EC8E0533906A8C03245', '1', null, null, null, '0', '0');

  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A7', 6, '部门ID', 'DEPT_ID', 3, 32, null, null, '0', '1', '512D05E5207C6EC8E0533906A8C03245', '1', null, null, null, '0', '0');

  INSERT INTO DICT_T_DEFAULTCOL (DEALID, ORDERID, NAME, DBCOLUMNNAME, DATATYPE, DATALENGTH, SCALE, CSID, ISPRIMARY, ISRESERVE, GUID, STATUS,DEFAULTVALUE, ISLOGICKEY, DEID, ISVISIBLE, ISUPDATE)
  VALUES ('A7', 7, '专项唯一标识', 'SPFID', 3, 32, null, null, '0', '1', '512D05E5207D6EC8E0533906A8C03245', '1', null, null, null, '0', '0');

END;
--添加表处理类型(专项一级项目控制数AND项目二级项目控制数)
