declare 
  v_column number;
  v_pk number;
  v_str VARCHAR(2);
  v_index number;
begin
  --判断   专项资金附件表   AGENCYID 是否存在
  select count(1) into v_column from user_tab_columns t
    where t.TABLE_NAME = 'P#SPF_T_FATTACH'
      and t.COLUMN_NAME = 'AGENCYID';
      
  if v_column > 0 then
    
    --判断是否是 主键
    select count(1)
      into v_pk
      from user_cons_columns t
     WHERE t.constraint_name = 'PK_P#SPF_T_FATTACH';

    if v_pk > 0 then
      --删除联合主键
      execute immediate Q'{
        alter table P#SPF_T_FATTACH
          drop constraint PK_P#SPF_T_FATTACH cascade
      }';
    end if;
    
    select count(1) into v_index from user_indexes uo where uo.index_NAME='PK_P#SPF_T_FATTACH';
    if v_index > 0 then 
    --删除索引
      execute immediate Q'{
        drop index PK_P#SPF_T_FATTACH
      }';
    end if;
    
    --添加联合主键
    execute immediate Q'{
      alter table P#SPF_T_FATTACH
        add constraint PK_P#SPF_T_FATTACH primary key (PROVINCE, YEAR, STATUS, DATAKEY)
    }';
      
    SELECT w.NULLABLE
      INTO v_str
      FROM user_tab_columns w
     WHERE w.TABLE_NAME = 'P#SPF_T_FATTACH'
       AND w.COLUMN_NAME = 'AGENCYID';
    
    IF v_str = 'N' THEN
        --设置字段可以为空
    execute immediate Q'{
      alter table P#SPF_T_FATTACH modify AGENCYID  null
    }';
    END IF;
    --清空表字段数据
    execute immediate Q'{
      update P#SPF_T_FATTACH set AGENCYID = null
    }';
    --删除字段
    execute immediate Q'{
      alter table P#SPF_T_FATTACH drop column AGENCYID
    }';
    
    --删除 dict_t_factor 表   AGENCYID 字段
    delete from dict_t_factor t where t.columnid='B4C3176E9A02476898A271EF56439F8E';
  
    
  end if;
  
  -- 删除  专项资金附件表  视图
  delete from dict_t_model t where t.tableid='06CAC5F4FF6748AD893A81BEB6E0EA7E';
  
  --  删除  专项资金附件表  dict_t_factor
  delete from dict_t_factor t where t.tableid='06CAC5F4FF6748AD893A81BEB6E0EA7E';
  
  
  --  添加  专项资金附件表  视图
  insert into dict_t_model (APPID, BGTLVL, DBTABLENAME, DEALTYPE, EXTPROP, INPUTLVL, ISADD, ISMAN, ISPARTITION, ISRESERVED, ISSHOW, ISTASK, ISSUMTAB, MAINUPTAB, NAME, ORDERID, RELATAB, REMARK, SECUSQL, INITSQL, INITSQLTIME, SHORTTITLE, STATUS, SUITID, TABLEID, TABLETYPE, TABSWHERE, ISBAK, ISALLDISTRICT, ISALLYEAR, DESCFILE)
  values ('SPF', null, 'SPF_T_FATTACH', '4*04', '0000000000000000000000000000000', '1', '0', '0', '1', '0', '1', null, '0', null, '专项资金附件表', 28, null, null, null, null, '1', null, '1', '8288F140A88F4CCB8FF5BD9B4B28DCEF', '06CAC5F4FF6748AD893A81BEB6E0EA7E', '1', null, '0', '1', '0', null);
  
  
  --  添加  专项资金附件表  dict_t_factor
  
  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '是否倒挤行', '08A7CE8A41BA43DDB67B2B14FE629F7E', null, 1, 3, 'ISDJ', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '0', '0', '1', 1, '是否倒挤行', '1', 13, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, '09A1A5D61BB1475187A7C71812B4DDDA', null, 32, 3, 'FJLB', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '0', '0', '1', '0', '0', '0', '1', '0', '0', 1, '附件类别', '1', 22, null, null, null, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '是否其中项', '10E4A46888D9460281730BB7B8F5FCC9', null, 1, 3, 'ISQZX', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '0', '0', '1', 1, '是否其中项', '1', 12, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, '13713DD909DD42A8B2C489EEB8E3EE3A', null, 200, 3, 'FIRATTNAME', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '0', '0', '1', '0', '0', '0', '1', '0', '0', 1, '附件大类', '1', 19, null, null, null, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '单元是否可录', '228282C34A484E97B5F85823B8E1326C', null, 1000, 3, 'CELLSECU', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '0', '0', '1', 1, '单元是否可录', '1', 10, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '级次码', '22AD1A46D7EE4EA9A7FB2CB942F3A6D8', null, 1, 1, 'LEVELNO', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '0', '0', '1', 1, '层次码', '1', 6, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '是否可修改', '31E9370B64064198B0A9D0CF37C68AF3', null, 1, 3, 'ISUPDATE', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '0', '0', '1', 1, '是否可修改', '1', 14, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '是否模板', '36AE978538CA4746AE68CA4E9DB7C0B3', null, 1, 3, 'ISTEMPLATE', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '0', '0', '1', 1, '是否模板', '1', 16, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '同步状态', '3E998796C9B149FAA038C087251A4DB4', null, 1, 3, 'SYNSTATUS', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '0', '0', '1', 1, '同步状态', '1', 11, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, '448CDA22D09343E2BCA5C315BFB3DD3C', null, 1, 3, 'ISPUBLIC', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '0', '0', '1', '0', '0', '0', '1', '0', '0', 1, '是否公开', '1', 25, null, null, null, '0', null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '原始编码', '5924135DDD1A4E9382CC1E67A2720398', null, 32, 3, 'ORIGCODE', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '0', '0', '1', 1, '原始编码', '1', 15, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '是否可以插入下级', '627F4FD3BA6B443AA89482B98E0A1333', null, 1, 3, 'ISINSERT', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '0', '0', '1', 1, '是否可插入', '1', 8, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '末级编码', '6A8C3D4111EB410C956CD0793705158C', null, 1, 3, 'ISLEAF', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '0', '0', '1', 1, '是否末级', '1', 7, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '财政级次', '7C11D3C1D6584034A9E34367BD22190C', null, 1, 3, 'BGTLVL', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '0', '0', '1', '0', '0', '0', '1', '0', '0', 1, '财政级次', '1', 1, null, null, null, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, '7EE7B2FD0BDA4AE5A4FDBA9A4FF33AF9', null, 4, 3, 'FINYEAR', 'to_char(sysdate,''YYYY'')', null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '0', '0', '1', '0', '0', '0', '1', '0', '0', 1, '财年', '1', 21, null, null, null, '2', null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '浮动表的显示列', '86112F97E46B4C96BCFA33842FFFD21C', null, 100, 3, 'FDCODE', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '0', '0', '1', 1, '浮动表显示列', '1', 5, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '专项附件', '975711E265664A90BBAE6DD96C436A06', null, 32, 3, 'ATTACHID', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '1', '0', '1', '0', '1', 1, '专项附件', '1', 24, null, null, 0, 'C', null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '专项ID', '9F150E14B24A4068A825A1D4AA20A644', null, 32, 3, 'SPFID',  null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '1', '0', '0', '0', '0', 1, '专项唯一标识', '1', 18, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '附件名称', 'A1E89E6DA9D04A35A21B803F89D60655', null, 200, 3, 'ATTNAME', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '1', '0', '1', '0', '1', 1, '附件名称', '1', 26, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, 'A3426DA7F47F4621B16083DC6395A025', null, 4000, 3, 'NEEDUPDATE', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '0', '0', '1', '0', '0', '0', '1', '0', '0', 1, '刷新标志', '1', 20, null, null, null, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '行标识', 'B214CD330E334B4BA15431F7F1F3C066', null, 32, 3, 'DATAKEY', 'sys_guid()', '080001', '0000000000000000000000000000000', null, null, null, null, '0', '0', '0', '1', '1', '0', '0', '0', '1', '0', '0', 1, '行标志', '0', 2, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '附件细类', 'BF9276C68B8643C2BBF2BD8D2CB48CDD', null, 32, 3, 'DETCLASSID', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '1', '0', '0', '0', '0', 1, '附件细类', '1', 23, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '排序序号', 'C0D9498FD5964A07845FDE5BFA16D323', null, 9, 1, 'ORDERID', '0', null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '1', '0', '0', '0', '0', 1, '排序序号', '1', 4, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '上级编码', 'DD0B09F91AC245929188C2CD797BAD36', null, 32, 3, 'SUPERID', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '0', '0', '1', 1, '上级编码', '1', 17, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, '模板标识', 'FCAE0B1A91B6467186918EBA25A41611', null, 32, 3, 'TEMPLATEID', null, null, null, null, null, null, null, '0', '0', null, '0', '1', '0', '1', '0', '0', '0', '1', 1, '模板标识', '1', 9, null, null, 0, null, null, '1', '0', '06CAC5F4FF6748AD893A81BEB6E0EA7E', null, '0', null);


  --删除  项目附件表   dict_t_model
  delete from dict_t_model t where t.tableid='F6A4E2F5DF1E96F7E040A8C0200352B4';
  --添加  项目附件表   dict_t_model
  insert into Dict_t_Model (APPID, BGTLVL, DBTABLENAME, NAME, TABLEID, DEALTYPE, EXTPROP, INPUTLVL, ISADD, ISMAN, ISPARTITION, ISRESERVED, ISSHOW, ISTASK, ISSUMTAB, MAINUPTAB, ORDERID, RELATAB, REMARK, SECUSQL, INITSQL, INITSQLTIME, SHORTTITLE, STATUS, SUITID, TABLETYPE, TABSWHERE, ISBAK, ISALLDISTRICT, ISALLYEAR, ISEXCELIMP, DESCFILE)
  values ('SPF', '1', 'SPF_T_PATTACH', '项目附件表', 'F6A4E2F5DF1E96F7E040A8C0200352B4', '5*04', '0000000000000000000000000000000', '3', '0', '0', '1', '1', '1', '0', '0', null, 0, null, null, null, '<CLOB>', null, '项目附件表', '1', 'B29F2474AA8F40938D299880CFB87BEF', '1', null, '1', '0', '0', null, null);
  
  
  --删除   项目附件表   dict_t_factor 数据
  delete from dict_t_factor t where t.TABLEID ='F6A4E2F5DF1E96F7E040A8C0200352B4';

  --添加  项目附件表   dict_t_factor 数据
  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, '0D91D5735BF44943BFCA0902B1F17132', null, 1, 3, 'ISUPDATE', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '是否可更新', '1', 66, null, null, 0, null, null, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, '189B0250072B4189A0DCD6274CCC1D44', null, 32, 3, 'SUPERID', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '上级编码', '1', 59, null, null, 0, null, null, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, '294C5D2A1CF349D5B6E4D5F352ADE465', null, 1, 3, 'ISTEMPLATE', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '是否模板', '1', 65, null, null, 0, null, null, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, '3DF6ADEE5AE5456CA32E87F4E43BDAB3', null, 1, 3, 'ISQZX', null, null, '00000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '是否其中项', '1', 67, null, null, 0, null, null, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, '73E282D73CAA4FA1946C38D209252947', null, 200, 3, 'FDCODE', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '浮动编码', '1', 64, null, null, 0, null, null, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, 'B87E23FFAED446C28E5468BFF3E6C80E', null, 1, 3, 'ISDJ', null, null, '00000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '是否倒挤行', '1', 68, null, null, 0, null, null, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, 'F33BF9AA1E8C48A3A9D94734054659AD', null, 32, 3, 'TEMPLATEID', null, null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '模板标识', '1', 58, null, null, 0, null, null, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, '1', null, null, 'F6A4E2F5DF1F96F7E040A8C0200352B4', null, 1, 3, 'BGTLVL', null, null, '00000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '1', '0', '1', '0', '0', 1, '财政级次', '1', 2, null, null, 0, '0', 0, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, '1', null, null, 'F6A4E2F5DF2096F7E040A8C0200352B4', null, 32, 3, 'DATAKEY', 'sys_guid()', null, '0000000000000000000000000000000', null, null, null, null, '0', '0', '1', '1', '1', '0', '1', '0', '1', '0', '0', 1, '行标识', '0', 6, null, null, 0, '0', 0, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, 'F6A4E2F5DF2296F7E040A8C0200352B4', null, 9, 1, 'ORDERID',  '1', null, '00000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '1', '0', '1', '0', '0', 1, '排序序号', '1', 50, null, null, 0, '0', 0, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, '1', null, null, 'F6A4E2F5DF2396F7E040A8C0200352B4', null, 32, 3, 'PROJECTID', null, null, '00000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '1', '0', '1', '0', '0', 1, '项目ID', '0', 57, null, null, 0, '0', 0, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, '1', null, null, 'F6A4E2F5DF2E96F7E040A8C0200352B4', null, 1000, 3, 'TEMPLETREMARK', null, null, '00000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '0', 1, '附件模板说明', '1', 42, null, null, 0, '0', 0, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, '5|doc,docx,xls,xlsx,jpg,pdf', '附件大小不能超过5兆（M）', 'F6A5CEE48FD76D02E040A8C0200352B5', null, 32, 3, 'ATTACHID',  null, null, '00000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '项目附件', '1', 19, null, null, 0, 'C', 250, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, '1', null, null, 'F6A5CEE48FD86D02E040A8C0200352B6', null, 1000, 3, 'MEMO', null, null, '00000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '附件说明', '1', 26, null, null, 0, '0', 300, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, 'F6A5CEE48FD96D02E040A8C0200352B7', '1F61620487DA498B8BD0F2D015054BEB', 1, 6, 'ISMUST', '0', null, '00000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '0', 1, '是否必须', '1', 43, null, null, 0, '4', 0, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, 'F6A5CEE48FDC6D02E040A8C0200352B8', null, 32, 3, 'TEMPLETID', null, null, '00000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '附件模板', '1', 18, null, null, 0, 'C', 200, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, '1', null, null, 'F6A5CEE48FDE6D02E040A8C0200352B9', null, 200, 3, 'ATTACHNAME', null, null, '00000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '附件名称', '1', 17, null, null, 0, '0', 200, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, 'F7988D561EC0854DE040A8C020036751', null, 9, 1, 'LEVELNO', '0', null, '00000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '级次码', '1', 48, null, null, 0, '0', 0, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, 'F7988D561EC1854DE040A8C020036751', null, 1, 3, 'ISINSERT', '''0''', null, '00000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '是否可插入下级', '1', 45, null, null, 0, '0', 0, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  insert into dict_t_factor (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT, PARENTNODECANCHECK, XLSXCOLUMNID)
  values (null, null, null, null, null, null, 'F799A45F9C6E7035E040A8C020036AEE', null, 1, 3, 'ISLEAF', null, null, '00000000000000000000000000000000', null, null, null, null, '0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', 1, '是否末级', '1', 46, null, null, 0, '0', 0, '1', '0', 'F6A4E2F5DF1E96F7E040A8C0200352B4', null, '0', null);

  --刷新视图
  sys_p_recreate_views('06CAC5F4FF6748AD893A81BEB6E0EA7E');  --专项资金附件表
  
  sys_p_recreate_views('F6A4E2F5DF1E96F7E040A8C0200352B4');  --项目附件表
  
end;
--专项资金附件表删除AGENCYID字段and专项项目
