
DECLARE
  V_COUNT_REPORT INT;
V_COUNT_ISSUED INT;
BEGIN
SELECT COUNT(*)
  into V_COUNT_REPORT 
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'P#SPF_T_BUSINESSCHECKDEF'
   AND COLUMN_NAME = 'ISREPORTCHECK';
    IF V_COUNT_REPORT = 0 
    THEN 
     EXECUTE IMMEDIATE Q'{ALTER TABLE P#SPF_T_BUSINESSCHECKDEF ADD ISREPORTCHECK char(1)}'; 
     end if;
SELECT COUNT(*)
  into V_COUNT_ISSUED 
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'P#SPF_T_BUSINESSCHECKDEF'
   AND COLUMN_NAME = 'ISSUEDCHECK';
    IF V_COUNT_ISSUED= 0 
    THEN 
     EXECUTE IMMEDIATE Q'{ALTER TABLE P#SPF_T_BUSINESSCHECKDEF ADD ISSUEDCHECK char(1)}'; 
  END IF;
  EXECUTE IMMEDIATE Q'/CREATE OR REPLACE VIEW SPF_T_BUSINESSCHECKDEF AS
SELECT CHECKID,
         BUSINESSTYPE,
         ERRORTYPE,
         ISUSE,
         ISMIDCHECK,
         ISADDCHECK,
         ISSAVECHECK,
          ISREPORTCHECK,
           ISSUEDCHECK,
         CHECKTYPE,
         ISDIRECT,
         LDIRECTCOL,
         RDIRECTCOL,
         BUDGETLEVEL,
         NAME,
         STATUS,
         GUID,
         ORDERID,
         OBJECTID,
         PROCESSID,
         TYPEFLAG,
         DBVERSION,
         ROLEID
    FROM P#SPF_T_BUSINESSCHECKDEF
   WHERE PROVINCE = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID')
     AND YEAR = GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR')
     AND STATUS = '1'/';
END;
--给审核配置加是否上报下发时审核字段