BEGIN
UPDATE P#DICT_T_MODELCODE
   set DYNAMICWHERE = 'guid in (SELECT COLUMN_VALUE FROM TABLE(F_SPF_GETAGENCYDLPOWER(''$SPFID$'', ''$PROJECTID$''))) order by code'
 WHERE DBTABLENAME = 'CODE_T_AGENCY_SPFDL'
   AND tableid = '223267AA7D472B22E050A8C021057ED5';
END;
--项目代录代码表修改
