i integer;
begin
select count(table_name) into i  from user_tables t where t.table_name = 'EFM_T_INSTALLLOG';
 if i = 0 then 
   EXECUTE IMMEDIATE Q'{CREATE TABLE EFM_T_INSTALLLOG
   (LOGID VARCHAR2(32 BYTE) DEFAULT SYS_GUID() NOT NULL , 
    OBJECTNAME VARCHAR2(30 BYTE), 
    OBJECTTYPE VARCHAR2(32 BYTE), 
	ISSUCCESS CHAR(1 BYTE) DEFAULT '1', 
	SQLTEXT CLOB, 
	ERROINFO CLOB, 
	OBJECTCOMMENT VARCHAR2(200 BYTE), 
	DBVERSION TIMESTAMP (6) DEFAULT SYSDATE
   )}';
   EXECUTE IMMEDIATE Q'{CREATE INDEX IDX_EFM_T_INSTALLLOG ON EFM_T_INSTALLLOG (ISSUCCESS)}';
   EXECUTE IMMEDIATE Q'{CREATE UNIQUE INDEX PK_EFM_T_INSTALLLOG ON EFM_T_INSTALLLOG (LOGID)}';
   EXECUTE IMMEDIATE Q'{ALTER TABLE EFM_T_INSTALLLOG ADD CONSTRAINT PK_EFM_T_INSTALLLOG PRIMARY KEY (LOGID)}';
   EXECUTE IMMEDIATE Q'{CREATE PROCEDURE COMPILE_INVALID IS
     BEGIN
       DBMS_UTILITY.COMPILE_SCHEMA(USER, FALSE);
     END COMPILE_INVALID;}';
   EXECUTE IMMEDIATE Q'{CREATE OR REPLACE PROCEDURE EXEC_INSTALLSQL(P_ID VARCHAR2) AUTHID CURRENT_USER IS
       V_CLOB CLOB;
     BEGIN
       EXECUTE IMMEDIATE 'SELECT SQLTEXT  FROM EFM_T_INSTALLLOG WHERE LOGID = :1' INTO V_CLOB USING P_ID;
       EXECUTE IMMEDIATE V_CLOB;
     END EXEC_INSTALLSQL;}';
 end if;