DECLARE 
 i INT;
 BEGIN
SELECT COUNT(1) INTO i FROM user_objects t WHERE t.OBJECT_NAME = 'F_GET_BGTSUMMARYINFO';
IF i > 0 THEN
  EXECUTE IMMEDIATE 'DROP FUNCTION F_GET_BGTSUMMARYINFO';
END IF;
END;

--É¾³ý²»ÓÃµÄFunction
