begin
delete from Dict_t_Settingtabinfo where GUID = '37BD2DDBD5056CABE053BE01A8C00A9A';
insert into Dict_t_Settingtabinfo (GUID,DBTABLENAME,NAME,REMARK,TABSWHERE,APPID,YEARPART,TASKPART,PROVINCEPART,INITIALIZE,ISLEAD,CHANGEDISTRICT) 
values ('37BD2DDBD5056CABE053BE01A8C00A9A','P#BGT_T_SETHIDDENCOLUMN','用户列隐藏设置表','录入界面用户修改化列隐藏设置','','BGT','1','0','1','0','0','');
end;--BGT_T_SETHIDDENCOLUMN登记
