DECLARE
  V_SQL VARCHAR2(32000);
  V_CNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_CNT FROM USER_TAB_COLS WHERE TABLE_NAME = 'P#DICT_T_SETTINGBUSIINFO' AND COLUMN_NAME = 'PROVINCE';
  IF V_CNT < 1 THEN
    RETURN;
  END IF;
V_SQL := 'CREATE TABLE T_TMP_SETTINGBUSIINFO AS 
SELECT APPID, DATAKEY, NAME, ORDERID, STATUS, URL, IS_AJAX,SYSTIMESTAMP DBVERSION FROM(
SELECT APPID, DATAKEY, NAME, ORDERID, STATUS, URL, IS_AJAX
 FROM P#DICT_T_SETTINGBUSIINFO)';
EXECUTE IMMEDIATE V_SQL;

V_SQL := 'ALTER TABLE T_TMP_SETTINGBUSIINFO MODIFY STATUS DEFAULT '1'';
EXECUTE IMMEDIATE V_SQL;

V_SQL := 'DROP TABLE P#DICT_T_SETTINGBUSIINFO';
EXECUTE IMMEDIATE V_SQL;
V_SQL := 'RENAME T_TMP_SETTINGBUSIINFO TO P#DICT_T_SETTINGBUSIINFO';
EXECUTE IMMEDIATE V_SQL;
V_SQL := 'ALTER TABLE P#DICT_T_SETTINGBUSIINFO ADD CONSTRAINT PK_DICT_T_SETTINGBUSIINFO  PRIMARY KEY(STATUS,DATAKEY)';
EXECUTE IMMEDIATE V_SQL;
V_SQL := Q'{CREATE OR REPLACE VIEW DICT_T_SETTINGBUSIINFO AS
SELECT APPID, DATAKEY, DBVERSION, NAME, ORDERID, STATUS, URL, IS_AJAX
  FROM P#DICT_T_SETTINGBUSIINFO
 WHERE STATUS = '1'}';
EXECUTE IMMEDIATE V_SQL;
V_SQL := Q'{CREATE OR REPLACE TRIGGER TR_P#DICT_T_SETTINGBUSIINFO
 BEFORE INSERT OR UPDATE ON P#DICT_T_SETTINGBUSIINFO FOR EACH ROW 
BEGIN 
  IF INSERTING THEN 
    :NEW.DBVERSION:=CASE WHEN TO_CHAR(:NEW.DBVERSION,'YYYY-MM-DD') ='2012-01-01' THEN TO_DATE('2012-01-01','YYYY-MM-DD') ELSE SYSTIMESTAMP END;
  END IF; 
  IF (TO_CHAR(:NEW.DBVERSION,'YYYY-MM-DD') ='2012-01-01' AND ((UPDATING AND UPDATING('DBVERSION')) OR INSERTING )) THEN 
    RETURN ; 
  END IF; 
  IF UPDATING THEN 
    :NEW.DBVERSION:=SYSTIMESTAMP; 
  END IF; 
END  TR_P#DICT_T_SETTINGBUSIINFO;}';

EXECUTE IMMEDIATE V_SQL;
END;

--修改P#BIL_T_MENUBILLTYPE表为非分区表
