BEGIN
  
UPDATE P#BGT_T_CHECKDEF A
   SET CREATEBGTLEVEL =
       (SELECT B.LEVELNO FROM CODE_T_DISTRICT B WHERE B.CODE = A.PROVINCE)
 WHERE STATUS = '1';

UPDATE P#BGT_T_BUSINESSCHECKDEF C
   SET CREATEBGTLEVEL =
       (SELECT B.LEVELNO FROM CODE_T_DISTRICT B WHERE B.CODE = C.PROVINCE)
 WHERE STATUS = '1';

END;

--更新审核规则创建级次
