DECLARE 
  v_i NUMBER(10);
  v_name VARCHAR2(30);
  v_type VARCHAR2(30);
BEGIN
  v_name := 'BGT_T_MONEYCOUPLING';
  SELECT nvl((SELECT object_type FROM user_objects WHERE object_name = v_name),'') INTO v_type FROM dual;
  IF v_type = 'TABLE' THEN
    EXECUTE IMMEDIATE 'DROP TABLE '|| v_name;
  END IF;
   IF v_type = 'VIEW' THEN
    EXECUTE IMMEDIATE 'DROP VIEW '|| v_name;
    EXECUTE IMMEDIATE 'DROP TABLE P#'|| v_name;
  END IF;
  
  EXECUTE IMMEDIATE 'CREATE TABLE BGT_T_MONEYCOUPLING (GUID VARCHAR2(32) DEFAULT SYS_GUID(),SPFID VARCHAR2(32),ISFUNCTION CHAR(1),ISECONOMY CHAR(1))';
  
  EXECUTE IMMEDIATE 'alter table BGT_T_MONEYCOUPLING add year CHAR(4) not null';
  EXECUTE IMMEDIATE 'alter table BGT_T_MONEYCOUPLING add province VARCHAR2(9) not null'; 
  EXECUTE IMMEDIATE 'alter table BGT_T_MONEYCOUPLING add dbversion TIMESTAMP(6) default sysdate'; 
  EXECUTE IMMEDIATE 'alter table BGT_T_MONEYCOUPLING add status CHAR(1) default 1';
  
  SELECT COUNT(1) INTO v_i FROM USER_OBJECTS WHERE OBJECT_NAME = 'PKG_MULTYEAR';

 
  EXECUTE IMMEDIATE Q'{CALL PKG_MULTYEAR.Secu_SP_MANY_Y_CZ_Do('BGT_T_MONEYCOUPLING')}';
  
  
  EXECUTE IMMEDIATE 'alter table P#BGT_T_MONEYCOUPLING add constraint PK_BGT_T_MONEYCOUPLING primary key (province,year,status,GUID)';
END;--moneyCouplingTable
