BEGIN

DELETE FROM  DICT_T_SETTINGTABINFO WHERE DBTABLENAME IN ('P#BGT_T_TRANSFERPAYSETTING');
 
insert into DICT_T_SETTINGTABINFO (GUID, DBTABLENAME, NAME, REMARK, APPID, STATUS, YEARPART, TASKPART, PROVINCEPART, INITIALIZE)
values ('4DF5745049D40D13E0533A06A8C064D1', 'P#BGT_T_TRANSFERPAYSETTING', '转移支付地区设置表', '转移支付地区设置表', 'bas', '1', '1', '0', '1', '0');

END;
--P#BGT_T_TRANSFERPAYSETTING添加到SETTING表
