CREATE OR REPLACE FUNCTION F_GET_FORMULA_QUOTA_VAL(P_TABLEID VARCHAR2,P_DBTABLENAME VARCHAR2,P_FINYEAR VARCHAR2,P_AGENCYID VARCHAR2,P_PROJTYPEID VARCHAR2,P_EXPECOID VARCHAR2,P_COLID VARCHAR2)
RETURN NUMBER
IS
  V_SQL VARCHAR2(32000);
  V_RET NUMBER;
  V_TABLE VARCHAR2(30);
  V_TABLEID VARCHAR2(32);
  V_FORMULA VARCHAR2(32000);
  V_CNT NUMBER;
--替换字符串中类似于@COLUMN_NAME@的参数为P_TABLE中的列名，并加上P_TABLE指定的P_ALIAS别名前缀,如：P_ALIAS.COLUMN_NAME
  FUNCTION REPLACE_PARAMETER(P_DATA VARCHAR2,P_TABLE VARCHAR2,P_ALIAS VARCHAR2) RETURN VARCHAR2 IS
    V_START NUMBER;
    V_END NUMBER;
    V_LEN NUMBER;
    V_PRE VARCHAR2(100);
    V_COL VARCHAR2(100);
    V_DATA VARCHAR2(30000);
  BEGIN
    IF P_DATA IS NULL THEN
      RETURN P_DATA;
    END IF;
    V_DATA := P_DATA;
    IF P_ALIAS IS NULL THEN
      V_PRE := '';
    ELSE
      V_PRE := P_ALIAS||'.';
    END IF;
    LOOP
      V_START := INSTR(V_DATA,'@');
      EXIT WHEN  V_START < 1;
      V_END := INSTR(V_DATA,'@',V_START + 1);
      IF V_END < 1 THEN
        EXIT;
      END IF;
      V_LEN := V_END - V_START - 1;
      V_COL := UPPER(TRIM(SUBSTR(V_DATA,V_START + 1,V_LEN)));
      SELECT COUNT(*) INTO V_LEN FROM USER_TAB_COLUMNS WHERE TABLE_NAME = P_TABLE AND COLUMN_NAME = V_COL;
      IF V_LEN > 0 THEN
        V_DATA := REPLACE(V_DATA,'@'||V_COL||'@',V_PRE||V_COL);
      END IF;
    END LOOP;
    RETURN V_DATA;
  END REPLACE_PARAMETER;
BEGIN
  V_TABLE := P_DBTABLENAME;
  V_TABLEID:=P_TABLEID;
  --SELECT TABLEID,DBTABLENAME INTO V_TABLEID,V_TABLE FROM DICT_T_MODEL WHERE DEALTYPE = '2201';
  --先判断项目类别与经济科目有无对应关系
  SELECT COUNT (*) INTO V_CNT FROM CAL_T_OUTWINDOWSET WHERE TABLEID = V_TABLEID AND (AGENCYID = P_AGENCYID OR AGENCYID = '*') AND PROJTYPEID = P_PROJTYPEID AND EXPECOID= P_EXPECOID AND FUNDSOURCEID = P_COLID;
  IF V_CNT < 1 THEN
    RETURN 0;
  END IF;
  SELECT NVL((SELECT FORMULASQL FROM (
  SELECT X.FORMULASQL FORMULASQL,ROW_NUMBER() OVER(ORDER BY Y.AGENCYID DESC) RN
  FROM CAL_T_FORMULA X,CAL_T_OUTWINDOWSET Y
  WHERE X.FORMULAID (+)= Y.FORMULAID AND Y.TABLEID = V_TABLEID
  AND (Y.AGENCYID = P_AGENCYID OR Y.AGENCYID = '*') AND Y.PROJTYPEID =P_PROJTYPEID
  AND Y.EXPECOID=P_EXPECOID AND Y.FUNDSOURCEID = P_COLID
  ) T WHERE RN = 1),'') INTO V_FORMULA FROM DUAL;
  V_FORMULA := DBMS_LOB.SUBSTR(V_FORMULA,32000);
  IF V_FORMULA IS NULL THEN
    RETURN 0;
  END IF;
  V_FORMULA := REPLACE_PARAMETER(V_FORMULA,V_TABLE,'TXYZ');
  V_SQL := 'SELECT NVL(('||V_FORMULA||'),0) FROM (SELECT '''||P_AGENCYID||''' AGENCYID,'''||P_EXPECOID||''' EXPECOID,'''||P_PROJTYPEID||''' PROJTYPEID,'''||P_FINYEAR||''' FINYEAR FROM DUAL) TXYZ';
  IF V_SQL IS NOT NULL THEN
    EXECUTE IMMEDIATE V_SQL INTO V_RET;
  ELSE
    RETURN 0;
  END IF;
  RETURN V_RET;
END F_GET_FORMULA_QUOTA_VAL;
--01_F_GET_FORMULA_QUOTA_VAL
