CREATE OR REPLACE VIEW BGT_V_DISTRICTLEVEL AS
  SELECT '0' CODE, '退回上一步' NAME FROM DUAL
  UNION ALL
  SELECT '1' CODE, '中央' NAME FROM DUAL WHERE PKG_CONSTANTS.GETDEFAULTPROVINCE <> '8700'
  UNION ALL
  SELECT '2' CODE, '省' NAME FROM DUAL  WHERE PKG_CONSTANTS.GETDEFAULTPROVINCE <> '8700'
  UNION ALL
  SELECT '3' CODE, '市' NAME FROM DUAL  WHERE PKG_CONSTANTS.GETDEFAULTPROVINCE <> '8700'
  UNION ALL
  SELECT '4' CODE, '县' NAME FROM DUAL  WHERE PKG_CONSTANTS.GETDEFAULTPROVINCE <> '8700'

--回退级次视图-地区
