Begin
Delete From P#Synch_t_Setting Where PHYSDBNAME='P#BGT_T_CHART';
Insert into p#Synch_t_Setting (PROVINCE,YEAR,PHYSDBNAME, SYNCHORDER, SYNCHCONDITION, PKCOL, SYNCHEDHANDLER, SYNCHRECOGCOL, TABLETYPE, MAXROW, NETTYPE, REMARK, STATUS, DIRECTION, FILTERCOL, ISALWAYSEXPORT)
SELECT TT.DISTRICTID,TT.YEAR,'P#BGT_T_CHART', 51, null, 'PROVINCE,YEAR,GUID', null, 'DBVERSION', '1', 100000, null, null, '1', 'O',  '', '0' From Pub_t_Partition_Divid  tt Where tt.year!='*';
End;
--登记P#BGT_T_CHART到下发设置表
