BEGIN

DELETE FROM  DICT_T_SETTINGTABINFO WHERE DBTABLENAME IN ('P#BGT_T_CUSTOMCONDITION', 'P#BGT_T_CUSTOMSORT');
 
insert into DICT_T_SETTINGTABINFO (GUID, DBTABLENAME, NAME, REMARK, APPID, STATUS, YEARPART, TASKPART, PROVINCEPART, INITIALIZE)
values ('4F8D09F70E7867BDE0533A06A8C041EF', 'P#BGT_T_CUSTOMCONDITION', '高级查询设置表', '高级查询设置表', 'bgt', '1', '1', '0', '1', '1');

insert into DICT_T_SETTINGTABINFO (GUID, DBTABLENAME, NAME, REMARK, APPID, STATUS, YEARPART, TASKPART, PROVINCEPART, INITIALIZE)
values ('4F8D09F70E7B67BDE0533A06A8C041EF', 'P#BGT_T_CUSTOMSORT', '高级排序设置表', '高级排序设置表', 'bgt', '1', '1', '0', '1', '1');

sys_p_addpartition_all('P#BGT_T_CUSTOMCONDITION');
sys_p_addpartition_all('P#BGT_T_CUSTOMSORT');

END;
--自定交查询添加到SETTING表
