BEGIN
  DELETE FROM P#CODE_T_PERSONSTATUS
   WHERE GUID = '4FD7F77AD5191B0AE0533A06A8C01DFA';
  DELETE FROM P#CODE_T_PERSONSTATUS
   WHERE GUID = '4FD7F77AD51A1B0AE0533A06A8C01DFA';
  DELETE FROM P#CODE_T_PERSONSTATUS
   WHERE GUID = '4FD7F77AD51C1B0AE0533A06A8C01DFA';
  DELETE FROM P#CODE_T_PERSONSTATUS
   WHERE GUID = '4FD7F77AD51D1B0AE0533A06A8C01DFA';
  DELETE FROM P#CODE_T_PERSONSTATUS
   WHERE GUID = '4FD7F77AD51E1B0AE0533A06A8C01DFA';

  INSERT INTO P#CODE_T_PERSONSTATUS
    (GUID, CODE, ISLEAF, LEVELNO, NAME, SUPERGUID, PROVINCE, YEAR)
    SELECT '4FD7F77AD5191B0AE0533A06A8C01DFA',
           '001',
           '1',
           '1',
           '在职转离退',
           '0',
           TT.DISTRICTID,
           TT.YEAR
      FROM PUB_T_PARTITION_DIVID TT
     WHERE TT.YEAR != '*';
  INSERT INTO P#CODE_T_PERSONSTATUS
    (GUID, CODE, ISLEAF, LEVELNO, NAME, SUPERGUID, PROVINCE, YEAR)
    SELECT '4FD7F77AD51A1B0AE0533A06A8C01DFA',
           '002',
           '1',
           '1',
           '死亡',
           '0',
           TT.DISTRICTID,
           TT.YEAR
      FROM PUB_T_PARTITION_DIVID TT
     WHERE TT.YEAR != '*';
  INSERT INTO P#CODE_T_PERSONSTATUS
    (GUID, CODE, ISLEAF, LEVELNO, NAME, SUPERGUID, PROVINCE, YEAR)
    SELECT '4FD7F77AD51C1B0AE0533A06A8C01DFA',
           '003',
           '1',
           '1',
           '调出',
           '0',
           TT.DISTRICTID,
           TT.YEAR
      FROM PUB_T_PARTITION_DIVID TT
     WHERE TT.YEAR != '*';
  INSERT INTO P#CODE_T_PERSONSTATUS
    (GUID, CODE, ISLEAF, LEVELNO, NAME, SUPERGUID, PROVINCE, YEAR)
    SELECT '4FD7F77AD51D1B0AE0533A06A8C01DFA',
           '004',
           '1',
           '1',
           '辞退',
           '0',
           TT.DISTRICTID,
           TT.YEAR
      FROM PUB_T_PARTITION_DIVID TT
     WHERE TT.YEAR != '*';
  INSERT INTO P#CODE_T_PERSONSTATUS
    (GUID, CODE, ISLEAF, LEVELNO, NAME, SUPERGUID, PROVINCE, YEAR)
    SELECT '4FD7F77AD51E1B0AE0533A06A8C01DFA',
           '005',
           '1',
           '1',
           '错误数据',
           '0',
           TT.DISTRICTID,
           TT.YEAR
      FROM PUB_T_PARTITION_DIVID TT
     WHERE TT.YEAR != '*';
END;
--INIT_CODE_T_PERSONSTATUS
