CREATE OR REPLACE VIEW BGT_T_OARELATION AS
SELECT DBVERSION, DOCID, GUID, ORGID, REMARK, STATUS, TASKID, TASKTYPE, USERID
                    FROM P#BGT_T_OARELATION
                   WHERE STATUS = '1'
--BGT_T_OARELATION去掉年度过滤
