Begin
  --录入对象对应审核对象
Delete From P#Synch_t_Setting Where PHYSDBNAME='P#BGT_T_INPUTRELATONMODEL';
Insert into p#Synch_t_Setting (PROVINCE,YEAR,PHYSDBNAME, SYNCHORDER, SYNCHCONDITION, PKCOL, SYNCHEDHANDLER, SYNCHRECOGCOL, TABLETYPE, MAXROW, NETTYPE, REMARK, STATUS, DIRECTION, FILTERCOL, ISALWAYSEXPORT)
SELECT TT.DISTRICTID,TT.YEAR,'P#BGT_T_INPUTRELATONMODEL', 51, null, 'PROVINCE,YEAR,GUID', null, 'DBVERSION', '1', 100000, null, null, '1', 'O',  '(INPUTTABLEID IN (@TABLEID@) OR INPUTTABLEID IN (@TABLEID@))', '0' From Pub_t_Partition_Divid  tt Where tt.year!='*';
--视图对应物理对象
Delete From P#Synch_t_Setting Where PHYSDBNAME='P#BGT_T_VIEWRELATIONTABLE';
Insert into P#Synch_t_Setting (PROVINCE,YEAR,PHYSDBNAME, SYNCHORDER, SYNCHCONDITION, PKCOL, SYNCHEDHANDLER, SYNCHRECOGCOL, TABLETYPE, MAXROW, NETTYPE, REMARK, STATUS, DIRECTION, FILTERCOL, ISALWAYSEXPORT)
SELECT TT.DISTRICTID,TT.YEAR,'P#BGT_T_VIEWRELATIONTABLE', 51, null, 'PROVINCE,YEAR,GUID', null, 'DBVERSION', '1', 100000, null, null, '1', 'O',  '(VIEWID IN (@TABLEID@) OR VIEWID IN (@TABLEID@))', '0' From Pub_t_Partition_Divid  tt Where tt.year!='*';
End;
--下发录入对象和视图对应物理表设置表
