DECLARE
  V_CNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_CNT FROM USER_OBJECTS WHERE OBJECT_NAME = 'BGT_T_OADOCSOURCE';
  IF V_CNT < 1 THEN
    EXECUTE IMMEDIATE '
        CREATE TABLE BGT_T_OADOCSOURCE
        (
          DOCID     VARCHAR2(32),
          SOURCEDOCID    VARCHAR2(32),
          AGENCYID    VARCHAR2(32),
          REMARK    VARCHAR2(100),
          GUID      VARCHAR2(32) DEFAULT SYS_GUID() NOT NULL,
          DBVERSION TIMESTAMP(6) DEFAULT SYSDATE,
          STATUS    CHAR(1) DEFAULT 1 NOT NULL
        )';
        EXECUTE IMMEDIATE 'ALTER TABLE BGT_T_OADOCSOURCE ADD CONSTRAINT PK_BGT_T_OADOCSOURCE  PRIMARY KEY (GUID)';
        SYS_P_PARTITION_TABLE('BGT_T_OADOCSOURCE');
        
        EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW BGT_T_OADOCSOURCE AS
							SELECT AGENCYID, DBVERSION, DOCID, GUID, REMARK, SOURCEDOCID, STATUS
							  FROM P#BGT_T_OADOCSOURCE
							 WHERE  STATUS = '1'}';
    END IF;
END;
--BGT_T_OADOCSOURCE_CREATE
