DECLARE
v_i NUMBER(2);
BEGIN
    SELECT COUNT(1)  INTO v_i FROM USER_CONSTRAINTS  WHERE table_name = 'P#BIL_T_BILLTYPE' AND constraint_name = 'PK_BIL_T_BILLTYPE';
    IF v_i > 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE P#BIL_T_BILLTYPE DROP CONSTRAINT PK_BIL_T_BILLTYPE CASCADE DROP INDEX'; 
    END IF; 
    SELECT COUNT(1) INTO v_i FROM USER_INDEXES WHERE INDEX_NAME = 'PK_BIL_T_BILLTYPE';
     IF v_i > 0 THEN 
      EXECUTE IMMEDIATE 'DROP INDEX PK_BIL_T_BILLTYPE';
     END IF;
     EXECUTE IMMEDIATE 'ALTER TABLE P#BIL_T_BILLTYPE ADD CONSTRAINT PK_BIL_T_BILLTYPE PRIMARY KEY(PROVINCE, STATUS, BILLTYPEID)';
END;
--通用单据表修改主键
