DECLARE 
V_COUNT NUMBER;

BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'P#BGT_T_OARELATIONCOPY';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE Q'{
    CREATE TABLE BGT_T_OARELATIONCOPY
    (
      DOCID     VARCHAR2(32),
      TASKID    VARCHAR2(32),
      USERID    VARCHAR2(32),
      ORGID     VARCHAR2(32),
      REMARK    VARCHAR2(100),
      GUID      VARCHAR2(32) DEFAULT SYS_GUID() NOT NULL,
      TASKTYPE  CHAR(1) DEFAULT '0',
      ISGOBACK  CHAR(1) DEFAULT '0'
    )
    
    }';
    EXECUTE IMMEDIATE Q'{ALTER TABLE BGT_T_OARELATIONCOPY  ADD CONSTRAINT PK_BGT_T_OARELATIONCOPY  PRIMARY KEY (GUID) }';
    SYS_P_PARTITION_TABLE('BGT_T_OARELATIONCOPY');
  END IF;
  
  SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'P#BGT_T_OARUNPATH';
    IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE Q'{
    CREATE TABLE BGT_T_OARUNPATH
    (
      DOCID     VARCHAR2(32),
      TASKID    VARCHAR2(32),
      USERID    VARCHAR2(32),
      ORGID     VARCHAR2(32),
      DATAAGENCYID VARCHAR2(32),
      REMARK    VARCHAR2(100),
      GUID      VARCHAR2(32) DEFAULT SYS_GUID() NOT NULL,
      SENDTIME TIMESTAMP(6) DEFAULT SYSDATE,
      TARGETAGENCYID  VARCHAR2(32)
    )
    
    }';
    EXECUTE IMMEDIATE Q'{ALTER TABLE BGT_T_OARUNPATH  ADD CONSTRAINT PK_BGT_T_OARUNPATH  PRIMARY KEY (GUID, TARGETAGENCYID) }';
    SYS_P_PARTITION_TABLE('BGT_T_OARUNPATH');
  END IF;
  
  EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW BGT_T_OARELATIONCOPY AS 
                       SELECT DBVERSION,DOCID,GUID,ISGOBACK,ORGID,REMARK,STATUS,TASKID,TASKTYPE,USERID FROM P#BGT_T_OARELATIONCOPY WHERE STATUS='1' }';
                       
  EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW BGT_T_OARUNPATH AS
                       SELECT DATAAGENCYID,DBVERSION,DOCID,GUID,ORGID,REMARK,SENDTIME,STATUS,TARGETAGENCYID,TASKID,USERID FROM P#BGT_T_OARUNPATH WHERE STATUS='1' }';
  
END;
--按单位回退文_创建表
