CREATE OR REPLACE TRIGGER STND_P#CAL_T_AGSTANDGRADE_TR
AFTER DELETE OR UPDATE OR INSERT ON P#CAL_T_AGSTANDGRADE FOR EACH ROW
DECLARE
  V_STNDID VARCHAR2(32);
  V_NEEDUPDATE VARCHAR2(4000);
  V_SQL VARCHAR2(4000);
  V_NEWID VARCHAR2(32) := '#NONE#';
BEGIN
  IF DELETING THEN
    V_STNDID := :OLD.STANDARDID;
  END IF;

  IF UPDATING('YEAR') OR UPDATING('PROVINCE') OR UPDATING('AGENCYID') OR UPDATING('GRADEID') OR UPDATING('STANDARDID') OR UPDATING('STATUS') THEN
    V_STNDID := :OLD.STANDARDID;
    V_NEWID := :NEW.STANDARDID;
  ELSE
    RETURN;
  END IF;
  
  IF INSERTING AND :NEW.STATUS = '1' THEN
    V_NEWID := :NEW.STANDARDID;
  END IF;

  FOR C_COL IN (SELECT X.AGENCYID,X.PROJTYPEID,X.EXPECOID,Z.DBCOLUMNNAME,T.DBTABLENAME
    FROM CAL_T_OUTWINDOWSET X,CAL_T_FORMULA Y,DICT_T_FACTOR Z,DICT_T_MODEL T
    WHERE X.FORMULAID = Y.FORMULAID AND Y.TABLEID = Z.TABLEID AND X.FUNDSOURCEID = Z.COLUMNID AND T.TABLEID = Y.TABLEID  
		AND X.AGENCYID IS NOT NULL AND Z.ISLEAF = '1' 
		AND (Y.STANDARDID LIKE '%'||V_STNDID||',%' OR Y.STANDARDID LIKE '%'||V_NEWID||',%')) LOOP
    V_NEEDUPDATE := ','||C_COL.DBCOLUMNNAME||',6,';
    IF C_COL.AGENCYID = '*' THEN
      V_SQL := 'UPDATE '||C_COL.DBTABLENAME||' SET NEEDUPDATE = NEEDUPDATE||'''||V_NEEDUPDATE||'''
      WHERE PROJTYPEID = :2 AND EXPECOID = :3  AND NVL(INSTR(NEEDUPDATE,'''||V_NEEDUPDATE||'''),0) < 1';
      EXECUTE IMMEDIATE V_SQL USING C_COL.PROJTYPEID,C_COL.EXPECOID;
    ELSE
      V_SQL := 'UPDATE '||C_COL.DBTABLENAME||' SET NEEDUPDATE = NEEDUPDATE||'''||V_NEEDUPDATE||'''
      WHERE AGENCYID = :1 AND PROJTYPEID = :2 AND EXPECOID = :3  AND NVL(INSTR(NEEDUPDATE,'''||V_NEEDUPDATE||'''),0) < 1';
      EXECUTE IMMEDIATE V_SQL USING C_COL.AGENCYID,C_COL.PROJTYPEID,C_COL.EXPECOID;
    END IF;
  END LOOP;
END STND_P#CAL_T_AGSTANDGRADE_TR;
--STND_P#CAL_T_AGSTANDGRADE_TR
