INSERT INTO BGT_T_OARUNPATH
  (DOCID,
   GUID,
   ORGID,
   TASKID,
   DATAAGENCYID,
   TARGETAGENCYID,
   USERID)
  SELECT DOCID,
         GUID,
         ORGID,
         (SELECT TASKID
            FROM BGT_T_OARELATION T2
           WHERE T2.DOCID = T1.DOCID
             AND TASKTYPE = '0' AND ROWNUM < 2) TASKID,
         TASKID DATAAGENCYID,
         TASKID TARGETAGENCYID,
         USERID
    FROM BGT_T_OARELATION T1
    WHERE NOT EXISTS (SELECT 1 FROM BGT_T_OARUNPATH T3 WHERE T3.GUID = T1.GUID)
--³õÊ¼»¯Ô¤Ëã¹ì¼£±í
