CREATE OR REPLACE PROCEDURE P_CREATE_VIEW_FUND_SPLIT(P_SRC_TABLEID VARCHAR2,P_DEST_TABLEID VARCHAR2) IS
  V_SQL VARCHAR2(32760);
  V_ID VARCHAR2(32);
  V_TABLE VARCHAR2(30);
  V_COLNAME VARCHAR2(30);
  V_COLLIST VARCHAR2(4000);
  V_VIEW_NAME VARCHAR2(30);
  V_CNNAME VARCHAR2(200);
  V_CNT NUMBER;
  TYPE R_ID_NAME IS RECORD (COLUMNID VARCHAR2(32),DBCOLUMNNAME VARCHAR2(30));
  TYPE R_LIST IS TABLE OF R_ID_NAME;
  V_COLARRAY R_LIST;
  V_INDEX BINARY_INTEGER;
BEGIN
  
  SELECT DBTABLENAME,NAME INTO V_TABLE,V_CNNAME FROM DICT_T_MODEL WHERE TABLEID = P_SRC_TABLEID;
  V_CNNAME := V_CNNAME||'(资金拆分)';
  V_VIEW_NAME := V_TABLE||'_SP';
  
  INSERT INTO DICT_T_MODEL(APPID, BGTLVL, DBTABLENAME, DEALTYPE, EXTPROP, INPUTLVL, ISADD, ISMAN, ISPARTITION, ISRESERVED, ISSHOW, ISTASK, ISSUMTAB, MAINUPTAB, NAME, ORDERID, RELATAB, REMARK, SECUSQL, INITSQLTIME, SHORTTITLE, SUITID, TABLEID, TABLETYPE,ISBAK,ISALLDISTRICT)
  SELECT APPID, BGTLVL,V_VIEW_NAME DBTABLENAME, 'D1' DEALTYPE, RPAD('0',100,'0') EXTPROP, INPUTLVL, ISADD, ISMAN, ISPARTITION,'0' ISRESERVED,'1' ISSHOW,'0' ISTASK, ISSUMTAB, MAINUPTAB, V_CNNAME NAME, ORDERID, RELATAB, REMARK, SECUSQL,'1' INITSQLTIME, SHORTTITLE, SUITID, P_DEST_TABLEID TABLEID, '2' TABLETYPE,'0' ISBAK,ISALLDISTRICT
  FROM DICT_T_MODEL
  WHERE TABLEID = P_SRC_TABLEID AND NOT EXISTS(SELECT 1 FROM DICT_T_MODEL WHERE TABLEID = P_DEST_TABLEID);
  --先保存已经存在的末级列ID
  SELECT COLUMNID,DBCOLUMNNAME BULK COLLECT INTO V_COLARRAY FROM DICT_T_FACTOR WHERE TABLEID = P_DEST_TABLEID;
  --删除
  DELETE FROM DICT_T_FACTOR WHERE TABLEID = P_DEST_TABLEID;
  INSERT INTO DICT_T_FACTOR(ALIAS,BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, ISBANDCOL, OPENWINDOWTYPE,ISKEY,ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE,LEVELNO, NAME,NULLABLE, ORDERID, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS,SUPERID,TABLEID)
  SELECT ALIAS,BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, ISBANDCOL, OPENWINDOWTYPE,ISKEY,ISLEAF,ISREGEX,ISRESERVE,ISSUM,ISUPDATE,ISVIRTUAL,ISVISIBLE,LEVELNO, NAME,NULLABLE,ROWNUM ORDERID, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS,SUPERID,P_DEST_TABLEID TABLEID
  FROM DICT_T_FACTOR 
  WHERE TABLEID = P_SRC_TABLEID;
  
  V_CNT := SQL%ROWCOUNT;
  
  SELECT CONNSTRA(DBCOLUMNNAME||',') INTO V_COLLIST FROM DICT_T_FACTOR WHERE TABLEID = P_DEST_TABLEID AND ISLEAF = '1';
  
  FOR C_COL IN (SELECT DISTINCT Y.TOBASECOL,Z.DATATYPE,Z.DATALENGTH,Z.SCALE,Z.SHOWFORMAT,Z.SHOWWIDTH,Z.DEFAULTVALUE,Z.COLUMNID,Z.BANDCOLUMNID,Z.ISBANDCOL,Z.BANDREFDWCOL FROM BGT_V_PUBFUNDSOURCE X, EXP_S_PROJINVEST Y, DICT_T_FACTOR Z
                WHERE X.FUNDSOURCEID = Y.FUNDSOURCEID  AND Y.TOBASECOL = Z.DBCOLUMNNAME AND Z.TABLEID = P_SRC_TABLEID  AND Z.ISLEAF = '1') LOOP
    V_COLNAME := C_COL.TOBASECOL;
    V_CNT := V_CNT + 1;
    INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
    VALUES ('已安排', C_COL.BANDCOLUMNID, C_COL.BANDREFDWCOL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, C_COL.DATALENGTH, C_COL.DATATYPE, V_COLNAME,C_COL.DEFAULTVALUE, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL,C_COL.ISBANDCOL, '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '已安排', '1', V_CNT, NULL, NULL, C_COL.SCALE, C_COL.SHOWFORMAT, C_COL.SHOWWIDTH, '1',C_COL.COLUMNID, P_DEST_TABLEID, NULL,  '0', NULL);
    
    V_CNT := V_CNT + 1;
    INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
    VALUES ('本次安排', C_COL.BANDCOLUMNID, C_COL.BANDREFDWCOL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, C_COL.DATALENGTH, C_COL.DATATYPE, 'C_'||V_COLNAME,C_COL.DEFAULTVALUE, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL,C_COL.ISBANDCOL, '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, '本次安排', '1', V_CNT, NULL, NULL, C_COL.SCALE, C_COL.SHOWFORMAT, C_COL.SHOWWIDTH, '1', C_COL.COLUMNID, P_DEST_TABLEID, NULL,  '0', NULL);
    
    V_COLLIST := V_COLLIST||'CAST(0 AS NUMBER(24,6)) C_'||V_COLNAME||',';
    
    UPDATE DICT_T_FACTOR SET ISLEAF = '0',DBCOLUMNNAME = '',DATATYPE = 4 WHERE TABLEID = P_DEST_TABLEID AND COLUMNID = C_COL.COLUMNID; 
  END LOOP;
  
  --处理COLUMNID和SUPERID,BANDCOLUMNID
  FOR C_COL IN (SELECT COLUMNID,DBCOLUMNNAME,SUPERID,BANDCOLUMNID FROM DICT_T_FACTOR WHERE TABLEID = P_DEST_TABLEID) LOOP
    V_ID := RAWTOHEX(SYS_GUID());
    UPDATE DICT_T_FACTOR SET COLUMNID = V_ID WHERE TABLEID = P_DEST_TABLEID AND COLUMNID = C_COL.COLUMNID;
    UPDATE DICT_T_FACTOR SET SUPERID = V_ID WHERE TABLEID = P_DEST_TABLEID AND SUPERID = C_COL.COLUMNID;
    UPDATE DICT_T_FACTOR SET BANDCOLUMNID = V_ID WHERE TABLEID = P_DEST_TABLEID AND BANDCOLUMNID = C_COL.COLUMNID;
  END LOOP;
  
  INSERT INTO DICT_T_FACTOR (ALIAS, BANDCOLUMNID, BANDREFDWCOL, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME,  DEFAULTVALUE, DEID, EXTPROP, FRMCOLID, FRMTABID, HREFLOC, HREFPARMID, ISBANDCOL, ISHREF, OPENWINDOWTYPE, ISKEY, ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE, LEVELNO, NAME, NULLABLE, ORDERID, REGEXPR, REGEXPRINFO, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS, SUPERID, TABLEID, VIRCONTEXT,  PARENTNODECANCHECK, XLSXCOLUMNID)
  VALUES ('USABLENUM', NULL, NULL, NULL, NULL, NULL, RAWTOHEX(SYS_GUID()), NULL, 24, 2, 'USABLENUM',  NULL, NULL, '0000000000000000000000000000000', NULL, NULL, NULL, NULL, '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', 1, 'USABLENUM', '1', V_CNT + 2, NULL, NULL, 6, '0', NULL, '1', '0', P_DEST_TABLEID, NULL,  '0', NULL);
      
  
  V_INDEX := V_COLARRAY.FIRST;
  --处理缓存的列
  WHILE V_INDEX <= V_COLARRAY.LAST LOOP
    UPDATE DICT_T_FACTOR SET COLUMNID = V_COLARRAY(V_INDEX).COLUMNID 
      WHERE TABLEID = P_DEST_TABLEID AND DBCOLUMNNAME = V_COLARRAY(V_INDEX).DBCOLUMNNAME
       AND ISLEAF = '1';
    V_INDEX := V_COLARRAY.NEXT(V_INDEX);
  END LOOP;
  
  --SELECT CONNSTRA(DBCOLUMNNAME||',') INTO V_COLLIST FROM DICT_T_FACTOR WHERE TABLEID = P_DEST_TABLEID AND ISLEAF = '1';
  --V_COLLIST := TRIM(TRAILING ',' FROM V_COLLIST);
  V_SQL := 'CREATE OR REPLACE VIEW '||V_VIEW_NAME||' AS 
SELECT '||V_COLLIST||'CAST(0 AS NUMBER(24,6)) USABLENUM
FROM '||V_TABLE;
    EXECUTE IMMEDIATE V_SQL;
    
  RETURN;
END P_CREATE_VIEW_FUND_SPLIT;
--自动生成资金拆分表
