begin
DELETE FROM dict_t_dealtype  where DEALID='A0*03';
insert into dict_t_dealtype (APPID, DEALID, DEALNAME, ORDERID, NEEDCONFIG) values ('BGT', 'A0*03', '综合视图展示表', 2, '0');

DELETE DICT_T_DEFAULTCOL WHERE DEALID = 'A0*03';
INSERT INTO DICT_T_DEFAULTCOL(DEALID,ORDERID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,CSID,ISPRIMARY,ISRESERVE,GUID,STATUS,DBVERSION,DEFAULTVALUE,ISLOGICKEY,DEID)
SELECT 'A0*03',ORDERID,NAME,DBCOLUMNNAME,DATATYPE,DATALENGTH,SCALE,CSID,ISPRIMARY,ISRESERVE,sys_guid(),STATUS,DBVERSION,DEFAULTVALUE,ISLOGICKEY,DEID FROM DICT_T_DEFAULTCOL WHERE dealid = 'A0';

end;
--新增综合视图展示表160121郑桥
