DECLARE 
  v_i NUMBER(10);
  v_name VARCHAR2(30);
BEGIN
  v_name := 'BGT_T_CONFIRMFUNC';
  SELECT COUNT(1) INTO v_i FROM user_objects WHERE object_name = v_name AND object_type = 'TABLE';
  IF v_i > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE '|| v_name;
  END IF;

  
  EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW BGT_T_CONFIRMFUNC AS
  SELECT GUID, BILLDEFNAME NAME, '0' SUPERGUID, '1' ISLEAF, '' CODE FROM DICT_T_BILLDEF WHERE APPID = 'BGT'}';
         
END;
--…˙≥…BGT_T_CONFIRMFUNC ”Õº
