declare
--BGT_T_BUSINESSCHECKDEF 添加FLOWDIRECTION  和 AGENCYIDPASS  字段
v_n1 number(8):=0;
v_n2 number(8):=0;
begin

--业务审核定义加字段  
--添加FLOWTYPE 流程类型 上报,下发,横向
select count(0) into v_n1 from  user_tab_columns tab where tab.TABLE_NAME='P#BGT_T_BUSINESSCHECKDEF' and tab.COLUMN_NAME='FLOWDIRECTION';
if v_n1=0 then 
   execute immediate 'ALTER TABLE P#BGT_T_BUSINESSCHECKDEF add  FLOWDIRECTION VARCHAR2(10) default ''111''';
End if;

--添加AGENCYIDPASS 单位参数否传递
select count(0) into v_n2 from  user_tab_columns tab where tab.TABLE_NAME='P#BGT_T_BUSINESSCHECKDEF' and tab.COLUMN_NAME='AGENCYIDPASS';
if v_n2=0 then 
   execute immediate 'ALTER TABLE P#BGT_T_BUSINESSCHECKDEF add  AGENCYIDPASS CHAR(1) default ''1''';
End if;

--刷新视图
if v_n1=0 Or v_n2=0 then 
  execute immediate Q'{CREATE OR REPLACE VIEW BGT_T_BUSINESSCHECKDEF AS
SELECT AGENCYIDPASS,FLOWDIRECTION,CREATEBGTLEVEL,BUDGETLEVEL,BUSINESSTYPE,CHECKID,CHECKTYPE,DBVERSION,ERRORTYPE,EXPCATEGORY,GUID,ISADDCHECK,ISDIRECT,ISMIDCHECK,ISSAVECHECK,ISUSE,LDIRECTCOL,NAME,ORDERID,RDIRECTCOL,STATUS from P#BGT_T_BUSINESSCHECKDEF where PROVINCE=Global_MultYear_CZ.Secu_f_GLOBAL_PARM('DIVID') and Year=Global_MultYear_CZ.Secu_f_GLOBAL_PARM('YEAR') AND STATUS='1'}';
End if;

end;
--BGT_T_BUSINESSCHECKDEF添加FLOWDIRECTION和agencyIDPass字段
