DECLARE 
v_count NUMBER(10);
BEGIN
  SELECT COUNT(1) INTO v_count FROM User_Tab_Cols WHERE table_Name = 'P#EXP_S_PROJINVEST' AND column_Name = 'VALUERATIO';
  IF v_count = 0 THEN 
    EXECUTE IMMEDIATE Q'{ALTER TABLE P#EXP_S_PROJINVEST ADD VALUERATIO NUMBER(18,4) DEFAULT 1}';
  END IF;
  EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW EXP_S_PROJINVEST AS
          SELECT BGTLVL,DBVERSION,FUNDSOURCEID,FUNDSOURCENAME,ISLEAF,LEVELNO,STATUS,SUPERID,TOBASECOL,TOBASETAB,TOPROJCOL,TOPROJTAB,FUNDTYPE,CODE,VALUERATIO
          FROM P#EXP_S_PROJINVEST
          WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
END;--曹坤_资金来源对应列新增金额系统设置
