DECLARE 
v_count NUMBER(10);
BEGIN
  SELECT COUNT(1) INTO v_count FROM User_Tab_Cols WHERE table_Name = 'P#EXP_S_PROJINVEST' AND column_Name = 'GUID';
  IF v_count = 0 THEN 
    EXECUTE IMMEDIATE Q'{ALTER TABLE P#EXP_S_PROJINVEST  ADD GUID VARCHAR2(32) DEFAULT SYS_GUID()}';
  END IF;
  EXECUTE IMMEDIATE Q'{CREATE OR REPLACE VIEW EXP_S_PROJINVEST AS
SELECT DBVERSION,FUNDSOURCEID,STATUS,TOBASECOL,VALUERATIO,GUID
FROM P#EXP_S_PROJINVEST
WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'
}';
END;
--资金来源对应物理列表新增guid列20151123郑桥
