declare
v_n number(8) :=0;
begin 
SELECT count(0) into v_n FROM user_tab_columns WHERE upper(TABLE_NAME)='P#BGT_T_CHECKDEF' and upper(column_name)='USERDISTRICTID'; 
if v_n=0 then
execute immediate Q'{alter table P#BGT_T_CHECKDEF add USERDISTRICTID varchar(32)}';
execute immediate Q'{CREATE OR REPLACE VIEW BGT_T_CHECKDEF AS
 SELECT APPID,BUDGETLEVEL,CHECKEXCELSQL,CHECKID,CHECKSORTID,CHECKSQL,CHECKTYPE,DBVERSION,DEFNAME,ERRORDEF,LCOMPCOL,LDESC,LEFTGROUP,LMODELID,LQUERY,PUBGROUP,RCOMPCOL,RDESC,RELATYPE,RIGHTGROUP,RMODELID,RQUERY,SERID,SHOWTEXT,USERDISTRICTID,STATUS
 FROM P#BGT_T_CHECKDEF WHERE PROVINCE=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') AND YEAR=GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') AND STATUS='1'}';
end if;
end;
--给P#BGT_T_CHECKDEF添加分区字段
