DECLARE
v_i NUMBER(2);
BEGIN
    SELECT COUNT(1) INTO v_i FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_P#BGT_T_ZCXMMXB_3';
    IF v_i > 0 THEN 
      EXECUTE IMMEDIATE 'DROP INDEX IDX_P#BGT_T_ZCXMMXB_3';
    END IF;
    EXECUTE IMMEDIATE 'create index IDX_P#BGT_T_ZCXMMXB_3 on P#BGT_T_ZCXMMXB (YEAR, STATUS, SPFID, DBVERSION)';
END;--ÐÞ¸ÄBGT_T_ZCXMMXBË÷Òý
