BEGIN

DELETE FROM  DICT_T_SETTINGTABINFO WHERE DBTABLENAME IN ('P#CODE_T_PERSONSTATUS');
 
insert into DICT_T_SETTINGTABINFO (GUID, DBTABLENAME, NAME, REMARK, APPID, STATUS, YEARPART, TASKPART, PROVINCEPART, INITIALIZE)
values ('506DF78AE49D0578E0533A06A8C035DB', 'P#CODE_T_PERSONSTATUS', '人员状态代码表', '人员状态代码表', '*', '1', '1', '0', '1', '1');

DELETE FROM  DICT_T_SETTINGTABINFO WHERE DBTABLENAME IN ('P#BGT_T_PERSONMOVE');
 
insert into DICT_T_SETTINGTABINFO (GUID, DBTABLENAME, NAME, REMARK, APPID, STATUS, YEARPART, TASKPART, PROVINCEPART, INITIALIZE)
values ('50784D03C42F5292E0533A06A8C0AA5D', 'P#BGT_T_PERSONMOVE', '人员状态转换设置表', '人员状态转换设置表', '*', '1', '1', '0', '1', '1');

END;
--人员状态代码表添加到分区设置表
