BEGIN

DELETE FROM  DICT_T_SETTINGTABINFO WHERE DBTABLENAME IN ('P#BGT_T_CHART');
 
insert into DICT_T_SETTINGTABINFO (GUID, DBTABLENAME, NAME, REMARK, APPID, STATUS, YEARPART, TASKPART, PROVINCEPART, INITIALIZE)
values ('4E1E8E8B244E71DDE0533A06A8C0076B', 'P#BGT_T_CHART', '图表SQL登记', '图表SQL登记', 'bgt', '1', '1', '0', '1', '1');

END;
--登记P#BGT_T_CHART到SETTING表
