CREATE OR REPLACE PROCEDURE P_CREATE_VIEW_COLIDATA(P_APPID VARCHAR2) IS
  V_SQL VARCHAR2(32760);
  V_COLLIST VARCHAR2(4000);
  V_VIEW_NAME VARCHAR2(30);
  V_CNNAME VARCHAR2(200);
  P_SRC_TABLEID VARCHAR2(32);
  P_SRC_SUITID VARCHAR2(32);
  P_DEST_TABLEID VARCHAR2(32);
	V_SUFIX VARCHAR2(30);
BEGIN
  --支出项目明细表的tableID
  SELECT TABLEID,SUITID into P_SRC_TABLEID,P_SRC_SUITID FROM DICT_T_MODEL WHERE DEALTYPE = '2101';
  if P_SRC_TABLEID is null or P_SRC_SUITID is null then
    return;
  end if;
  V_CNNAME := '预算编制总表';
  V_VIEW_NAME := P_APPID||'_V_COLIDATA';
  --获取预算编制总表的tableID，如果没有查到，则生成一个
  SELECT NVL((SELECT TABLEID FROM DICT_T_MODEL WHERE APPID = P_APPID AND DEALTYPE = 'D0'),'') INTO P_DEST_TABLEID FROM DUAL;
  if P_DEST_TABLEID is null THEN
		SELECT MAX(SUBSTR(DBTABLENAME,-3)) INTO V_SUFIX FROM P#DICT_T_MODEL WHERE REGEXP_LIKE(DBTABLENAME,'^'||V_VIEW_NAME||'[0-9]{3}$');
		V_SUFIX := NVL(TRIM(V_SUFIX),'000');
		V_VIEW_NAME := V_VIEW_NAME||TRIM(TO_CHAR(TO_NUMBER(V_SUFIX) + 1,'000'));
		
    insert into DICT_T_MODEL (APPID, BGTLVL, DBTABLENAME, DBVERSION, DEALTYPE, EXTPROP, INPUTLVL, ISADD, ISMAN, ISPARTITION, ISRESERVED, ISSHOW, ISTASK, ISSUMTAB, MAINUPTAB, NAME, ORDERID, RELATAB, REMARK, SECUSQL, INITSQL, INITSQLTIME, SHORTTITLE, STATUS, SUITID, TABLEID, TABLETYPE, TABSWHERE, ISBAK, INSERTVERSION, ISALLDISTRICT, ISALLYEAR, INITSQLBTNNAME, ISEXCELIMP, DESCFILE)
    values (P_APPID, null, V_VIEW_NAME, sysdate(), 'D0', '0000000000000000000000000000000', '3', null, null, '0', '0', '1', '0', '0', null, V_CNNAME, 305, null, null, null, null, '1', null, '1', P_SRC_SUITID, sys_guid(), '2', null, '0',  sysdate(), '0', '0', null, null, null);
    SELECT TABLEID into P_DEST_TABLEID FROM DICT_T_MODEL WHERE APPID = P_APPID AND DEALTYPE = 'D0';
	ELSE
		SELECT DBTABLENAME INTO V_SUFIX FROM DICT_T_MODEL WHERE TABLEID = P_DEST_TABLEID;
    IF NOT REGEXP_LIKE(V_SUFIX,'^'||V_VIEW_NAME||'[0-9]{3}$') THEN
      SELECT MAX(SUBSTR(DBTABLENAME,-3)) INTO V_SUFIX FROM P#DICT_T_MODEL WHERE REGEXP_LIKE(DBTABLENAME,'^'||V_VIEW_NAME||'[0-9]{3}$')
      AND (PROVINCE,YEAR) NOT IN (SELECT GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('DIVID') PROVINCE,GLOBAL_MULTYEAR_CZ.SECU_F_GLOBAL_PARM('YEAR') YEAR FROM DUAL)
      AND STATUS = '1';
      V_SUFIX := NVL(TRIM(V_SUFIX),'000');
      V_VIEW_NAME := V_VIEW_NAME||TRIM(TO_CHAR(TO_NUMBER(V_SUFIX) + 1,'000'));
      UPDATE DICT_T_MODEL SET DBTABLENAME = V_VIEW_NAME WHERE TABLEID = P_DEST_TABLEID;
    ELSE
      V_VIEW_NAME := V_SUFIX;
    END IF;
  end if;
  
  --删除 不在 默认列管理表 中的列 和 不在 政府资金来源 中的列
  DELETE FROM DICT_T_FACTOR 
  WHERE TABLEID = P_DEST_TABLEID
  and trim(DBCOLUMNNAME) not in (select trim(DBCOLUMNNAME) from dict_t_defaultcol c where dealid = 'D0')
  and trim(DBCOLUMNNAME) not in (select trim(Y.TOBASECOL) from FASP_V_PUBBGTSOURCE X, EXP_S_PROJINVEST Y where X.GUID = Y.FUNDSOURCEID);
  --从默认列管理表中取数据
  INSERT INTO DICT_T_FACTOR( ALIAS, BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, ISBANDCOL, OPENWINDOWTYPE,ISKEY,ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE,LEVELNO, NAME, NULLABLE, ORDERID, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS,SUPERID,TABLEID)
  select null, null, null, name, sys_guid(), csid, datalength, datatype, trim(dbcolumnname), defaultvalue, dealid, '0', '0', islogickey, '1', '0', isreserve, '0', isupdate, isvisible, '1', name, '1', orderid, scale, null, null, null, status, '0', P_DEST_TABLEID TABLEID
  from dict_t_defaultcol c 
  where dealid = 'D0'
  and trim(DBCOLUMNNAME) not in (select trim(DBCOLUMNNAME) from DICT_T_FACTOR WHERE TABLEID = P_DEST_TABLEID);
  --取支出项目明细表BGT_T_ZCXMMXB的政府资金来源列
  INSERT INTO DICT_T_FACTOR (ALIAS,BGTLVL, COLFORMAT, COLTIPS, COLUMNID, CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, ISBANDCOL, OPENWINDOWTYPE,ISKEY,ISLEAF, ISREGEX, ISRESERVE, ISSUM, ISUPDATE, ISVIRTUAL, ISVISIBLE,LEVELNO, NAME,NULLABLE, ORDERID, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS,SUPERID,TABLEID)
  SELECT ALIAS,BGTLVL, COLFORMAT, COLTIPS, sys_guid(), CSID, DATALENGTH, DATATYPE, DBCOLUMNNAME, DEFAULTVALUE, DEID, ISBANDCOL, OPENWINDOWTYPE,ISKEY,'1',ISREGEX,ISRESERVE,'0','0',ISVIRTUAL,'1','1', NAME,NULLABLE,50, SCALE, SHOWFORMAT, SHOWWIDTH, STATUS,'0', P_DEST_TABLEID TABLEID
  FROM DICT_T_FACTOR 
  WHERE TABLEID = P_SRC_TABLEID
  and trim(DBCOLUMNNAME) in (select trim(Y.TOBASECOL) from FASP_V_PUBBGTSOURCE X, EXP_S_PROJINVEST Y where X.GUID = Y.FUNDSOURCEID)
  and trim(DBCOLUMNNAME) not in (select trim(DBCOLUMNNAME) from DICT_T_FACTOR WHERE TABLEID = P_DEST_TABLEID AND DBCOLUMNNAME IS NOT NULL);

  SELECT substr(CONNSTRA(DBCOLUMNNAME||', '''' '), 0, length(CONNSTRA(DBCOLUMNNAME||', '''' ')) - 5) INTO V_COLLIST FROM DICT_T_FACTOR WHERE TABLEID = P_DEST_TABLEID AND ISLEAF = '1';

  V_SQL := 'CREATE OR REPLACE VIEW '||V_VIEW_NAME||' AS SELECT '''' '||V_COLLIST||' FROM DUAL';
    EXECUTE IMMEDIATE V_SQL;
  RETURN;
END P_CREATE_VIEW_COLIDATA;

--P_CREATE_VIEW_COLIDATA
