DECLARE 
V_COUNT NUMBER;

BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'P#SECU_T_TASKTYPE';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE Q'{
    CREATE TABLE SECU_T_TASKTYPE
    (
      YEAR         CHAR(4) NOT NULL,
      PROVINCE     VARCHAR2(9) NOT NULL,
      APPID        VARCHAR2(32) NOT NULL,
      MANID        VARCHAR2(32) NOT NULL,
      TASKTYPEID     VARCHAR2(32) NOT NULL,
      MANTYPE      CHAR(1) DEFAULT 1 NOT NULL,
      STATUS       CHAR(1) DEFAULT 1 NOT NULL,
      GUID         VARCHAR2(32) DEFAULT SYS_GUID() NOT NULL,
      DBVERSION    TIMESTAMP(6) DEFAULT SYSDATE
    )
    
    }';
    EXECUTE IMMEDIATE Q'{ALTER TABLE SECU_T_TASKTYPE ADD CONSTRAINT PK_SECU_T_TASKTYPE PRIMARY KEY (APPID, MANTYPE, MANID, TASKTYPEID, GUID) }';
    SYS_P_PARTITION_TABLE('SECU_T_TASKTYPE');
  END IF;
   
END;
--用户角色对应任务类型
