DECLARE
  V_CNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_CNT FROM USER_OBJECTS WHERE OBJECT_NAME = 'BGT_T_KEEPCOUNT_TIME';
  IF V_CNT < 1 THEN
    EXECUTE IMMEDIATE '
CREATE TABLE BGT_T_KEEPCOUNT_TIME(
  PROVINCE VARCHAR2(9),
  YEAR VARCHAR2(4),
  OPERATION_TYPE VARCHAR2(30),
  LAST_OPERATION_TIME TIMESTAMP(6),
  CONSTRAINT PK_BGT_T_KEEPCOUNT_TIME PRIMARY KEY(PROVINCE,YEAR,OPERATION_TYPE)
)';
    END IF;
END;

--Ôö¼Ó±íBGT_T_KEEPCOUNT_TIME
