
package com.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IBpmnCommonService", targetNamespace = "http://webservice.bpmn.hq.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBpmnCommonService {


    /**
     * 
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userId", targetNamespace = "http://webservice.bpmn.hq.com/", className = "com.client.UserId")
    @ResponseWrapper(localName = "userIdResponse", targetNamespace = "http://webservice.bpmn.hq.com/", className = "com.client.UserIdResponse")
    public String userId(
        @WebParam(name = "userId", targetNamespace = "")
        String userId);

    /**
     * 
     * @param model
     * @return
     *     returns com.client.Model
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "initBpmnData", targetNamespace = "http://webservice.bpmn.hq.com/", className = "com.client.InitBpmnData")
    @ResponseWrapper(localName = "initBpmnDataResponse", targetNamespace = "http://webservice.bpmn.hq.com/", className = "com.client.InitBpmnDataResponse")
    public Model initBpmnData(
        @WebParam(name = "model", targetNamespace = "")
        Model model);

    /**
     * 
     * @return
     *     returns java.util.List<com.client.BpmnTemplateDef>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "initBpmnTemplateDef", targetNamespace = "http://webservice.bpmn.hq.com/", className = "com.client.InitBpmnTemplateDef")
    @ResponseWrapper(localName = "initBpmnTemplateDefResponse", targetNamespace = "http://webservice.bpmn.hq.com/", className = "com.client.InitBpmnTemplateDefResponse")
    public List<BpmnTemplateDef> initBpmnTemplateDef();

    /**
     * 
     * @param busiLog
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "receiveBusiLog", targetNamespace = "http://webservice.bpmn.hq.com/", className = "com.client.ReceiveBusiLog")
    @ResponseWrapper(localName = "receiveBusiLogResponse", targetNamespace = "http://webservice.bpmn.hq.com/", className = "com.client.ReceiveBusiLogResponse")
    public boolean receiveBusiLog(
        @WebParam(name = "busiLog", targetNamespace = "")
        List<ActBusiLogDomain> busiLog);

}
