
package com.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "webservice/common/bpmn", targetNamespace = "http://webservice.bpmn.hq.com/", wsdlLocation = "http://127.0.0.1:7002/hqbpmn/webservice/common/bpmn?wsdl")
public class Webservice_002fCommon_002fBpmn
    extends Service
{

    private final static URL WEBSERVICE_002FCOMMON_002FBPMN_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.client.Webservice_002fCommon_002fBpmn.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.client.Webservice_002fCommon_002fBpmn.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:7002/hqbpmn/webservice/common/bpmn?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:7002/hqbpmn/webservice/common/bpmn?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICE_002FCOMMON_002FBPMN_WSDL_LOCATION = url;
    }

    public Webservice_002fCommon_002fBpmn(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Webservice_002fCommon_002fBpmn() {
        super(WEBSERVICE_002FCOMMON_002FBPMN_WSDL_LOCATION, new QName("http://webservice.bpmn.hq.com/", "webservice/common/bpmn"));
    }

    /**
     * 
     * @return
     *     returns IBpmnCommonService
     */
    @WebEndpoint(name = "BpmnCommonServicePort")
    public IBpmnCommonService getBpmnCommonServicePort() {
        return super.getPort(new QName("http://webservice.bpmn.hq.com/", "BpmnCommonServicePort"), IBpmnCommonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBpmnCommonService
     */
    @WebEndpoint(name = "BpmnCommonServicePort")
    public IBpmnCommonService getBpmnCommonServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.bpmn.hq.com/", "BpmnCommonServicePort"), IBpmnCommonService.class, features);
    }

}
